### ISSUE TITLE
Calendar Interface

### ISSUE THREAD

**Issue by jethrokuan** [jethrokuan/org-roam#10]
A calendar view to see daily notes would be nice.

**Comment by dit7ya** [comment]
Are you talking about Roam's endless daily notes page or something else?

**Comment by jethrokuan** [comment]
Something like org's calendar view that shows days with daily notes and be able to quickly access them I guess

**Comment by ryjm** [comment]
I wonder if you could just have a thin layer over the `diary` library for the daily notes. You would have to account for each daily note being a headline vs a separate file, but it would be nice to avoid the buildup of files for each date.

**Comment by jethrokuan** [comment]
Do you foresee the file buildups to be a big issue? Typically they become a small proportion of the total note files. While the time complexity of building backlinks is linear in the number of files, it's also dependent on file size and complexity (using the org parser to get the AST, and filter out links). Keeping them as separate files also keeps the library simple.

**Comment by ryjm** [comment]
I was mainly thinking that hooking into the diary would make building out the calendar interface easy. Probably not that hard to do it from scratch though.

I do think it might be valuable to treat headlines and files in the same way (i.e everything under the header *Roam* would be treated the same as if it was in the file ` roam.org ( http://roam.org/ ) `), but that's a different discussion.

**Comment by jethrokuan** [comment]
Yeah, it seems like `calendar.el` doesn't have an easy way to plug in other sources of diary information. Pity. I'll think about it a bit more when this becomes higher priority.

> i.e everything under the header *Roam* would be treated the same as if it was in the file ` roam.org

This sounds like it would be confusing...

**Comment by anthrolisp** [comment]
Maybe have interoperability with [org-journal](https://github.com/bastibe/org-journal), which allows for different options for how to keep the journal entries (one per year, month, day, etc)

**Comment by jethrokuan** [comment]
Oh yeah, that should just work out of the box by default! Still no calendar view though, but I think I'm gonna do that.

**Comment by jethrokuan** [comment]
Okay yeah I confirmed that org-journal works neatly out of the box within org-roam. Here's my config:

```
(use-package org-journal
  :bind
  ("C-c n j" . org-journal-new-entry)
  :custom
  (org-journal-date-prefix "#+TITLE: ")
  (org-journal-file-format "%Y-%m-%d.org")
  (org-journal-dir "/home/jethro/Dropbox/org/braindump/org/")
  (org-journal-date-format "%A, %d %B %Y"))
```

And calendar view marking dates with entries:

![image](https://user-images.githubusercontent.com/1667473/73994424-6a8d8800-4990-11ea-8daf-42de989a177f.png)

**Comment by jethrokuan** [comment]
Closing as solved by org-journal.

**Comment by visika** [comment]
If anyone is having issues with org-journal headers (_outline-back-to-heading: Before first heading_ error), https://github.com/bastibe/org-journal/issues/182 could be helpful.
The problem arises when org-journal doesn't find a top level * entry.
Basically it separates the title attribute and the date entry, so org-journal finds at least one top level * entry.
