### ISSUE TITLE
How to handle file attachments?

### ISSUE THREAD

**Issue by Trevoke** [jethrokuan/org-roam#100]
I occasionally will want to attach a PDF or some other related file (heck, even a video game save file) to a roam file - is there a way to make sure org-roam handles the file / copies it to somewhere safe, or should I do this myself and link to the file from wherever I want it to be?

**Comment by jethrokuan** [comment]
> is there a way to make sure org-roam handles the file / copies it to somewhere safe

Not at the moment, but should be simple to add. I'm thinking 2 functions:

1. `org-roam-download`: given link (web), download file into org-roam storage.
2. `org-roam-insert-attachment`: default to looking for file at org-roam storage, but when file is selected outside of org-roam storage, copies it to storage, and uses a relative link.

**Comment by Trevoke** [comment]
Those both sound perfect :)

**Comment by poligen** [comment]
It is possible to do that by using the built-in feature in `Org-mode`. you can use [org attach](https://orgmode.org/manual/Attachments.html) to do that. 
You can generate a custom id under every orgmode item; while you attach a file on it, it will save it on a directory(you can sync the directory through dropbox or syncthing.
- a video tutorial about org [attachement](https://www.youtube.com/watch?v=KMlp9HUJI3s&list=PLVtKhBrRV_ZkPnBtt_TD1Cs9PJlU0IIdE&index=23)
- [automatically generate custom_id](https://writequit.org/articles/emacs-org-mode-generate-ids.html), you can follow the instruction to put it on your emacs init.el(or your config file)

- and you set your attach-id-dir `(setq  org-attach-id-dir "~/your/dir/path/")`

**Comment by jethrokuan** [comment]
I'd never heard of `org-attach`. I took a look, and I think it does indeed provide the required functionality. It's good to default on Org's built-in functionality.
