### ISSUE TITLE
Word wrapping in org-roam buffer

### ISSUE THREAD

**Issue by nmartin84** [jethrokuan/org-roam#101]
text from the backlink is not using word wrapping, leaving text truncated off screen. Example attached 😄 
https://i.imgur.com/ayoPg6p.png

**Comment by jethrokuan** [comment]
This is feels like personal preference, but I turn wrapping on for me. Emacs already has in-built functionality for that via `truncate-lines`:

![image](https://user-images.githubusercontent.com/1667473/74624034-de464680-5181-11ea-997b-f5d885ae296e.png)

Here's what I do in my `init.el`:

```
(setq-default truncate-lines t)

(defun jethro/truncate-lines-hook ()
  (setq truncate-lines nil))

(add-hook 'text-mode-hook 'jethro/truncate-lines-hook)
```

**Comment by jethrokuan** [comment]
I'm going to close this because I don't think it is org-roam's responsibility to control this behaviour.
