### ISSUE TITLE
Feature: Customize the org template used for `org-roam-insert`

### ISSUE THREAD

**Issue by leothelocust** [jethrokuan/org-roam#114]
Maybe this is already built in somewhere but missing documentation, but I'm hoping to configure the initial org file that is created when triggering the `org-roam-insert` function.

In essence, I might want something more fleshed out like the following:
```txt
#+TITLE:   My New Note
#+STARTUP: showall
#+AUTHOR:  blah blah
... etc

---

* Metadata:
** Tags: 
** Links:
... etc
```
instead of the default:
```txt
#+TITLE: My New Note
```

Thanks for the great project!!! Loving this so far!
-Levi

**Comment by jethrokuan** [comment]
I think this is a great idea. I'd deprecate `org-roam-autopopulate-title`, and have something like `org-roam-insert-template` instead.

I already do what you're suggesting, in a convoluted fashion. I have this in my `init.el`:

```
(defun jethro/deft-insert-boilerplate ()
    (interactive)
    (let ((setupfile (jethro/org-get-prop "SETUPFILE"))
          (title (jethro/org-get-prop "TITLE")))
      (when (and (not setupfile)
                 (not (s-match "hugo_setup"
                               (file-name-sans-extension
                                (buffer-file-name (current-buffer)))))
                 (not (s-match "private"
                               (file-name-sans-extension
                                (buffer-file-name (current-buffer))))))
        (goto-char (point-min))
        (insert "#+SETUPFILE:./hugo_setup.org\n")
        (insert "#+HUGO_SECTION: zettels\n")
        (insert (format "#+HUGO_SLUG: %s\n" (jethro/title-to-id (or title "EDITME"))))
        (goto-char (point-max)))))
```

which is evaluated in the directory containing my org files in via directory local variables.

**Comment by leothelocust** [comment]
Thanks @jethrokuan 

Okay, so I understand the dir-locals part, but how do you call this function? Do you just call `jethro/deft-insert-boilerplate` instead of `org-roam-insert`?

Also, may I ask what you have in `#+SETUPFILE: ./hugo_setup.org`?  I'm not familiar with the `SETUPFILE` variable.  Also, how do you keep that `hugo_setup.org` out of the search cache?

Thanks,
-Levi

**Comment by jethrokuan** [comment]
It's called as part of the dir-locals setup:

https://github.com/jethrokuan/braindump/blob/master/org/.dir-locals.el

My `hugo_setup.org` is here:

https://github.com/jethrokuan/braindump/blob/master/org/hugo_setup.org

nothing much, just some common setup for ox-hugo.

>  Also, how do you keep that hugo_setup.org out of the search cache?

I don't. It doesn't affect anything.
