### ISSUE TITLE
[QUESTION] Any suggestions on getting Graph SVG links working in Chrome on Mac OS?

### ISSUE THREAD

**Issue by seandavi** [jethrokuan/org-roam#115]
The org-roam graph renders file and opens in chrome. However, the roam:/// links are not registered, so they never open. I recognize this is not an org-roam problem, but perhaps one of the Mac users of org-roam has a suggested solution.

Thanks for exposing org-roam to us all.

**Comment by leothelocust** [comment]
@seandavi what did you use for the  `org-roam-graph-viewer`? The following is not working for me.

```elisp
(setq org-roam-graph-viewer "/Applications/Google\ Chrome.app/Contents/MacOS/Google Chrome")
```

**Comment by seandavi** [comment]
A nice trick on the Mac is to use `/usr/bin/open` to open arbitrary files. If Chrome is not the assigned SVG viewer, you can try something like this:

https://www.dummies.com/computers/macs/mac-operating-systems/how-to-assign-a-file-type-to-an-application-in-mac-os-x-lion/

that will change the handler for a given file or file type.

**Comment by jethrokuan** [comment]
According to the [org-protocol documentation](https://orgmode.org/worg/org-contrib/org-protocol.html#org4166fc4), this should help:

https://github.com/neil-smithline-elisp/EmacsClient.app

but there's the issue of using a shell script to open the roam links as well. I don't have a Mac so I can't try it.

**Comment by seandavi** [comment]
Thanks for the doc link, @jethrokuan. I'll post back if/when I get something working. It sounds like it will be similar to your Linux instructions, so hopefully not too bad.

**Comment by leothelocust** [comment]
@seandavi @jethrokuan 

[Platypus](https://github.com/sveinbjornt/Platypus) or [duti](https://github.com/moretension/duti) might be a good alternative to the "zip" file [EmacsClient.app](https://github.com/neil-smithline-elisp/EmacsClient.app).

**Platypus** 
Pros:
* You can create native apps for MacOS and associate URI schemes

Cons:
* (haven't tried it yet)


**duti**
Pros:
* cli interface to associate URI schemes with apps

Cons:
* public domain w/few updates in recent years

**Comment by naistran** [comment]
Thanks @leothelocust for suggesting [Platypus](https://github.com/sveinbjornt/Platypus)!

I've managed to get `roam://` links opened on MacOS with the following steps:

1. Create an executable `launch-emacs.sh` script:

```sh
#!/usr/bin/env bash
/usr/local/bin/emacsclient --no-wait "${1#*:}"
```

2. Install and launch Platypus

```
$ brew cask install platypus
```

3. Platypus settings:

- `App Name`: `OrgRoam`
- `Script Type`: `env` and `/usr/bin/env`
- `Script Path`: `/path/to/your/launch-emacs.sh`
- Tick `Accept dropped items` and click `Settings`
- Tick `Accept dropped files`
- Tick `Register as URI scheme handler`
- Add `roam` as a protocol.
- Create the app.

If you're using Chrome, by default it asks to confirm to use our `OrgRoam` app every time you click the link.

This could be annoying — you can make Chrome show a checkbox you can tick to always use the app without confirming:

```
$ defaults write com.google.Chrome ExternalProtocolDialogShowAlwaysOpenCheckbox -bool true
```

**Comment by jethrokuan** [comment]
Nice, I suppose this is also dependent on how Emacs was installed (you seem to have it at `/usr/local/bin`, and have successfully setup `emacsclient`. This, I was never able to do when I used a mac :smile:

**Comment by seandavi** [comment]
Here is my `/usr/local/bin`. It includes a bit from the emacs-for-mac installer and emacsclient from homebrew. The homebrew version works by itself, also. 

```
$ ls -lah /usr/local/bin/emacs*                                                                                                                                                                                       ─╯
lrwxr-xr-x  1 sdavis2  admin    82B Jan 30 23:30 /usr/local/bin/emacs -> /usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/Emacs.app/Contents/MacOS/Emacs.sh
lrwxr-xr-x  1 sdavis2  admin    55B Jan 30 23:20 /usr/local/bin/emacs-26.3 -> ../Cellar/emacs-mac/emacs-26.3-z-mac-7.8/bin/emacs-26.3
lrwxr-xr-x  1 sdavis2  admin    56B Jan 30 23:20 /usr/local/bin/emacsclient -> ../Cellar/emacs-mac/emacs-26.3-z-mac-7.8/bin/emacsclient
```

**Comment by leothelocust** [comment]
@naistran thanks for the pro-tip about the
```sh
defaults write com.google.Chrome ExternalProtocolDialogShowAlwaysOpenCheckbox -bool true
``` 
part!!! I've been dying trying to figure out how to make those prompts go away!

**Comment by naistran** [comment]
Indeed it just has to be an absolute path to `emacsclient`. I had just `emacsclient` initially but it seems the packaged script inside the created Platypus app couldn't access `PATH`.

**Comment by seandavi** [comment]
Thanks, @naistran and @leothelocust. Looks like there is a pretty complete recipe.

**Comment by ryanobjc** [comment]
I had to change the ${1#*:} -> ${1} in the 'launch-emacs.sh' because it was stripping off the org-protocol: prefix and thus org-protocol & org-roam-protocol didn't work.

**Comment by jethrokuan** [comment]
The instructions described in this issue are old, `emacsclient $1` is sufficient now.
