### ISSUE TITLE
org-roam-directory doesn't persist

### ISSUE THREAD

**Issue by bdarcus** [jethrokuan/org-roam#120]
### Description

It's possible i"m just missing something, as I have a pretty superficial understanding of emacs, but I am seeing that if I set the `org-roam-directory` variable in my init file (I'm using spacemacs), it will properly load. 

But then, if I open an org file, it will revert to default (`~/org`).

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/e84ab1de9a9f00213a9037a82365cc9fca753c5d

**Comment by jethrokuan** [comment]
`it will revert to default (~/org).`

This is actually not the default. I'm guessing you have something else messing with your `org-roam-directory` variable.

**Comment by bdarcus** [comment]
OK, thanks; will see if I can track it down.

**Comment by bdarcus** [comment]
I fixed this by setting the `org-directory variable` (whose default is `~/.org) in my init.

**Comment by aneeshsathe** [comment]
@bdarcus would it be possible to share your installation steps for spacemacs? Quite a few people are facing issues (mostly due to being new to emacs/spacemacs) and would be grateful for the directions! 

Thanks! :)

**Comment by honza** [comment]
```diff
diff --git a/layers/+emacs/org/packages.el b/layers/+emacs/org/packages.el
index d76e102cd..3581a8b30 100644
--- a/layers/+emacs/org/packages.el
+++ b/layers/+emacs/org/packages.el
@@ -45,7 +45,9 @@
         (ox-jira :toggle org-enable-jira-support)
         (org-trello :toggle org-enable-trello-support)
         (org-sticky-header :toggle org-enable-sticky-header)
-        ))
+        (org-roam :location (recipe :fetcher github
+                                    :repo "jethrokuan/org-roam"
+                                    :branch "develop"))))
 
 (defun org/post-init-company ()
   (spacemacs|add-company-backends :backends company-capf :modes org-mode))
@@ -810,3 +812,23 @@ Headline^^            Visit entry^^               Filter^^                    Da
     :defer t
     :init
     (add-hook 'org-mode-hook 'org-sticky-header-mode)))
+
+(defun org/init-org-roam ()
+  (use-package org-roam
+    :defer t
+    :commands (org-roam org-roam-insert org-roam-find-file)
+    :init
+    (progn
+
+      (with-eval-after-load 'org
+        (add-hook 'org-mode-hook 'org-roam-mode)
+        (add-hook 'after-init-hook 'org-roam--build-cache-async))
+
+      (spacemacs/declare-prefix "aoi" "org-roam")
+      (spacemacs/set-leader-keys
+        "aoir" 'org-roam
+        "aoii" 'org-roam-insert
+        "aoif" 'org-roam-find-file)
+
+      (setq spacemacs-org-roam-mode-map (copy-keymap spacemacs-org-mode-map))
+      (spacemacs//init-leader-mode-map 'org-roam-mode 'spacemacs-org-roam-mode-map))))
```

**Comment by honza** [comment]
I think I'll wait until org-roam stabilizes a bit more before attempting to add it to upstream spacemacs.

**Comment by jethrokuan** [comment]
> I think I'll wait until org-roam stabilizes a bit more before attempting to add it to upstream spacemacs.

Yeah, things are likely to change again.

**Comment by bdarcus** [comment]
> > I think I'll wait until org-roam stabilizes a bit more before attempting to add it to upstream spacemacs.
> 
> Yeah, things are likely to change again.

Do you have in mind when it would be good to upstream to spacemacs (which would be awesome!)? When it's included in MELPA? Some other point in the future?

**Comment by jethrokuan** [comment]
> Do you have in mind when it would be good to upstream to spacemacs (which would be awesome!)? When it's included in MELPA? Some other point in the future?

When the version number hits `1.0.0`, I don't know how far away that will be, I'd say in a month or so. Basically there's still a bit of technical debt to clean up which may require some breaking changes (like org-roam-mode becoming a global mode)
