### ISSUE TITLE
Question: multiple emacs instances

### ISSUE THREAD

**Issue by alanz** [jethrokuan/org-roam#123]
I generally run multiple emacs instances on my laptop, rather than using emacsclient.

I just noticed the "org roam cache loaded" notice on a second instance.

What bad things can happen in this scenario?

**Comment by jethrokuan** [comment]
The caches will not be a consistent view of your roam files. For example, if you created a file in one Emacs instance, the cache in the second instance won't know of it. 

Basically it's bad.

**Comment by alanz** [comment]
Ok.  My intention is to only `roam` in the one instance, so hopefully the impact will be manageable.

**Comment by jethrokuan** [comment]
Then that's fine, as long as you don't mix them up.
