### ISSUE TITLE
Convert text selection to org-roam link

### ISSUE THREAD

**Issue by jdiez17** [jethrokuan/org-roam#127]
### Brief Abstract

Can we add a function to convert a selected block of text into an org-roam note?
 
### Long Description

When writing a note it may not always be clear if I should add a link to an existing or empty org-roam note. Often when I reread what I wrote, I think it makes sense to link to a "quaternion" (e.g.) page. So what I do is delete the word "quaternion" and then type  `C-c n i quaternion`. 

It would be better if I could select the word "quaternion" and run a command to convert it to an org-roam page and link.

### Please check the following:
- [X] No similar feature requests

**Comment by herbertjones** [comment]
Can possibly be accomplished by changing `org-roam-insert`.  Example:
```elisp
(defun org-roam-insert (prefix)
  "Find an org-roam file, and insert a relative org link to it at point.

If PREFIX, downcase the title before insertion."
  (interactive "P")
  (let* ((region (and (region-active-p)
                      ;; following may lose active region, so save it
                      (cons (region-beginning) (region-end))))
         (completions (mapcar (lambda (file)
                                (list (org-roam--get-title-or-slug file)
                                      file))
                              (org-roam--find-all-files)))
         (title (completing-read "File: " completions nil nil
                                 (when region
                                   (buffer-substring-no-properties
                                    (car region) (cdr region)))))
         (absolute-file-path (or (cadr (assoc title completions))
                                 (org-roam--make-new-file-path (org-roam--get-new-id title) t)))
         (current-file-path (-> (or (buffer-base-buffer)
                                    (current-buffer))
                                (buffer-file-name)
                                (file-truename)
                                (file-name-directory))))
    (unless (file-exists-p absolute-file-path)
      (org-roam--make-file absolute-file-path title))
    (when region ;; Remove previously selected text.
      (goto-char (car region))
      (delete-char (- (cdr region) (car region))))
    (insert (format "[[%s][%s]]"
                    (concat "file:" (file-relative-name absolute-file-path
                                                        current-file-path))
                    (format org-roam-link-title-format (if prefix
                                                           (downcase title)
                                                         title))))))
```

**Comment by jethrokuan** [comment]
Give me a while, I'm making a big change.

**Comment by jethrokuan** [comment]
@herbertjones I've made hopefully what would be the (second) last big user-facing API change, and the installation instructions have been changed slightly. Would you like to test/PR the updated `org-roam-insert` on latest `develop`?

**Comment by jdiez17** [comment]
I tried @herbertjones' version of `org-roam-insert` on the latest develop and can confirm it works nicely :). However, it still requires the user to press `Return` to close the minibuffer created by `completing-read`. I would prefer to just invoke an action that inserts the link without confirmation. Perhaps it can be done with the universal argument before calling `org-roam-insert`? (I'm a complete n00b when it comes to emacs scripting, so please forgive me if that makes no sense)

**Comment by jethrokuan** [comment]
I think it's good to prompt, especially to figure out when a similar note already exists.

**Comment by jdiez17** [comment]
Actually I agree with you on that. Then the next feature related to inserting links that would be cool to have is some kind of drop-down menu showing matching org-roam notes, like Roam Research does. I guess we should create an issue for that feature as well?

**Comment by herbertjones** [comment]
There's two ways to handle the linked text.  One replaces the link description with the title of the page.  The other way is to keep what was highlighted, and make that the description of the link.  I think I prefer the second version.  Let me know what you prefer.

Use title: https://github.com/herbertjones/org-roam/blob/insert_with_region/org-roam.el#L298

Keep region as description: https://github.com/herbertjones/org-roam/blob/insert_with_region_keep_text/org-roam.el#L298

**Comment by jethrokuan** [comment]
The second, for me.
