### ISSUE TITLE
backup files in org-roam-directory are picked up

### ISSUE THREAD

**Issue by wjhun** [jethrokuan/org-roam#129]
After editing and saving a newly-created note in org-roam, the backup file (ending in '~') is recognized as a note.

To reproduce:

1. C-c n f to create a new note
2. Edit note title and save. Observe backup file in org-roam-directory.
3. C-c n g to produce a graph
4. Note that both the updated title and the default title (20200219102359) both show up. The latter is a link to the backup file (20200219102359.org~)
5. Manually delete the backup file in org-roam-directory and run C-c n g again.
6. The old note no longer shows up. 

Perhaps it would be useful to have a variable with a list of patterns to ignore within org-roam-directory (similiar to .gitignore).

- Emacs (`C-h v emacs-version`): v25.1.1
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/edbe34a1

**Comment by jethrokuan** [comment]
@wjhun can you confirm that you're on that commit? This was reported in #96, and subsequently fixed with #98 . I created a temp file and checked.

Also, the default title is no longer just the timestamp, so this suggests to me you're not on that commit.

**Comment by wjhun** [comment]
Yes, thank you. I messed up the package update in straight. It didn't help that I was in emacsclient and avoiding a daemon restart. Sorry for the noise.

This project looks promising, and I'm looking forward to using it in earnest.
