### ISSUE TITLE
Have two separte variables indicating where files are read and where new files are created.

### ISSUE THREAD

**Issue by jmburgos** [jethrokuan/org-roam#140]
Brief Abstract
Have two separte variables indicating where files are read and where new files are created.
### Long Description
Now the path stored in the variable "org-roam-directory" serves two purposes:
a) To indicate where new org-roam files are written, and
b) To indicate the base of the folder tree where org-roam searches for files.  According to the documentation, "every Org file, at any level of nesting, within /path/to/org/ is considered part of the Org-roam ecosystem".

I would like to have the option to have new files written in a particular folder within the org-roam ecosystem.  For example, I would like to have all files under` ~/Documents/` to be searched by org-roam, but have new files created in the folder `~/Documents/org_roam_files/`.

The rationale is that people often already have many org files with notes in some kind of folder structure, for example related to different projects, or note files created using helm-bibtex.  It would be useful to include all these in the org-roam ecosystem (by adding bi-directional links, for example), while at the same time keeping the folder structure tidy and not having "orphan" org-roam files in the base of folder tree.

Thank you for org-roam by the way!

**Comment by jethrokuan** [comment]
I've added and did a bit of manual testing, hope that works for you.

**Comment by jmburgos** [comment]
Wow, that was fast! Thanks, works like a charm.
