### ISSUE TITLE
make it recursive?

### ISSUE THREAD

**Issue by nmartin84** [jethrokuan/org-roam#15]
Hi, first thanks for making this! It's a great idea and could solve lots of problems. I have come across one issue and I think this is crucial as a lot of users may end up cross referencing their notes along with task items. If you nest files in directories, it breaks the backlinks and org-roam fails to find entries. You can add multiple directories to `org-roam-directories` and it'll work, but the hyperlinks in the org-roam buffer are broken and point to invalid file paths.

**Comment by jethrokuan** [comment]
Hey, yup! This is a bug, and a result of some really poorly written code. Expect a fix in a couple of hours.

**Comment by jethrokuan** [comment]
Reopening for now, but should be fixed in master. Let me know if you still face problems.

**Comment by jethrokuan** [comment]
Looks like there's still a small issue with the default directory of the org-roam buffer not being updated. 

Another problem is that the preview content links will then not always be clickable (since they are relative to the backlinked file's directory).

**Comment by jethrokuan** [comment]
The first problem, at least, should be resolved. No easy way to solve the second.

**Comment by nmartin84** [comment]
Great, will be testing today and will report back if there's still issues!

**Comment by nmartin84** [comment]
Commit [c57376a](https://github.com/jethrokuan/org-roam/commit/c57376ae662ac5ea53ed0f7a83260fae78c2515a) fixed the recursive functionality, but looks like a separate issue cropped up. 

Commit [09128bc](https://github.com/jethrokuan/org-roam/commit/09128bc9b287b692c3dbc615ea24158cdc377aa9) broke something where the org-roam buffer is longer displaying any results when you call org-roam. I found a way around the problem by calling org-roam-mode, and then the results will display, but it doesn't update in real time when you swap to another file.

**Comment by jethrokuan** [comment]
Hi, thanks for testing. Org-roam usage has changed after that commit: org-roam mode adds a local `post-command-hook`. So now it is necessary to:

`(add-hook 'org-mode-hook 'org-roam-mode)`

Which should make add the update function to all org-mode buffers. This reduces the number of buffers the post-command hook runs on. The installation instructions had been updated to match this new behaviour.

**Comment by visuelledata** [comment]
On the latest version I'm having issues with the org-roam buffer, it's not displaying results. I added the changed stuff to my [.emacs file](https://github.com/visuelledata/emacs/blob/master/.emacs) without success.

**Comment by jethrokuan** [comment]
> On the latest version I'm having issues with the org-roam buffer, it's not displaying results. I added the changed stuff to my [.emacs file](https://github.com/visuelledata/emacs/blob/master/.emacs) without success.

Have you reloaded your Emacs after adding that in? Any error messages? What's the output of:

`(org-roam--find-all-files)`

**Comment by visuelledata** [comment]
@jethrokuan 
I can't run `org-roam--find-all-files`.

**Comment by jethrokuan** [comment]
> @jethrokuan
> I can't run `org-roam--find-all-files`.

It's not an interactive command. The easiest way to run it is to run `M-x eval-expression` or `M-:` and type `(org-roam--find-all-files)`. If everything works, you should see a list your org files there.

**Comment by visuelledata** [comment]
Okay it lists all files without errors.

**Comment by jethrokuan** [comment]
@visuelledata are things working now? Have you restarted your emacs post the config change?

**Comment by visuelledata** [comment]
Sorry for not being clear! 

The buffer still isn't displaying anything. Restarted emacs, using the latest commit, and I'm still using the same .emacs file.

**Comment by jethrokuan** [comment]
@visuelledata let me PM you on reddit

**Comment by nmartin84** [comment]
Awesome, thanks for the clarification! New commit is looking good, i'm going to close this issue out now. Keep up the awesome work!
