### ISSUE TITLE
emacs svg viewer functionality not working

### ISSUE THREAD

**Issue by bdarcus** [jethrokuan/org-roam#150]
### Description

On #145, not sure if this is a bug, or something I'm just missing (like, do I need to configure anything, or should this "just work"?), but when I run show graph, it won't use the emacs viewer; will only load the file in Firefox. 

This is using v0.1.2.

### Versions
- Emacs: v26.3 (on Fedora)
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/bfb81e194a22b73fbba4892bf5f67ae54264c56a

**Comment by jethrokuan** [comment]
It uses Emacs only as a fallback, not the other way around.

**Comment by bdarcus** [comment]
Why? Is there something wrong with the internal viewer?

And is there a way for me to tell it not to use Firefox, and the fallback
instead?

**Comment by juergenhoetzel** [comment]
> Why? Is there something wrong with the internal viewer?

It doesn't provide clickable `roam://` links. 

Anyway: the behavior should be documented in the docstring.

**Comment by tuborgman** [comment]
Testing on my both macs, when choosing show graph it doesn't open Firefox or Chrome, but just open svg file in text xml mode in emacs. I'm using Doom Emacs.

**Comment by juergenhoetzel** [comment]
> Testing on my both macs, when choosing show graph it doesn't open Firefox or Chrome, but just open svg file in text xml mode in emacs. I'm using Doom Emacs.

`imagemagick-enabled-types` might be missing `SVG` on your setup?

**Comment by tuborgman** [comment]
You mean `imagemagick-register-types` ?  It is there, if so. 

And, btw, plantuml works nicely - I think it is also using the same engine.

**Comment by tuborgman** [comment]
UPD: managed to get SVG opened in firefox by setting `(setq org-roam-graph-viewer "/Applications/Firefox.app/Contents/MacOS/firefox")`. It looks like `(executable-find "firefox")` is not working properly on my macs.

**Comment by juergenhoetzel** [comment]
> UPD: managed to get SVG opened in firefox by setting `(setq org-roam-graph-viewer "/Applications/Firefox.app/Contents/MacOS/firefox")`. It looks like `(executable-find "firefox")` is not working properly on my macs.

Most likeley firefox is not in your Emacs `exec-path`: [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) may help

**Comment by mtravers** [comment]
On Mac, I did this which gets around the issues with `executable-find` 

`ln -s /Applications/Firefox.app/Contents/MacOS/firefox-bin /usr/local/bin/firefox`

**Comment by alphapapa** [comment]
> It doesn't provide clickable `roam://` links.

FYI, it is possible to make SVG's clickable in Emacs.  I did this with `org-graph-view`, and it works pretty well.  Sometimes the clickable areas are not quite aligned properly, but I haven't figured out why, and I wonder if it might be a bug in Emacs that could be reported and fixed.  But it works well enough to be useful, and it's much faster than loading in a browser.

**Comment by bdarcus** [comment]
> Anyway: the behavior should be documented in the docstring.

If I understand right, that means I can set the variable to define a different viewer. 

But how would one specify the emacs viewer?

> FYI, it is possible to make SVG's clickable in Emacs.

This would be great.

**Comment by jethrokuan** [comment]
I'd like to have the default be Emacs too, but I've found it to work poorly/not work at all. Especially with my giant SVGs. If moving to emacs, the `roam://` links could just be `file:///` links, which would be neat
