### ISSUE TITLE
Feature: Refactor the code to create the list of backlinks to its own function

### ISSUE THREAD

**Issue by benide** [jethrokuan/org-roam#154]
### Brief Abstract
Refactor the code for creating the list of backlinks so it can be used in custom export commands, or where ever else someone might find it useful.

### Long Description
I've been trying to figure out how to nicely navigate around my notes both in org-roam and in my ox-hugo export. The way you describe tags in #84 is fantastic for use within emacs, but using `#+hugo_tags:` is better for navigating in the export.

I think the best solution to this is to (exclusively) use the tagging solution you describe in #84, but then have a function available like `(defun org-roam-collect-backlinks (file) ...)`. This could then be used in whatever way org-roam users want, for example, 
```elisp
(defun my/custom-roam-export (file)
  ;; copy file to new buffer
  ;; use `org-roam-collect-backlinks` to insert backlink list according to some rules
  ;; finally, use `org-hugo--export-file-to-md`)
```

I think including a function specifically for a custom ox-hugo export would be a bit out of scope for this project, which is why I only am suggesting refactoring the code for getting backlinks. However, this is exactly how I would use it, and looking at https://braindump.jethro.dev, I think it would work well on your site too!

### Proposed Implementation
It looks like the relevant code is around [here](https://github.com/jethrokuan/org-roam/blob/d02d48e5598fc9da0448a0b1396a4cad40f71917/org-roam.el#L513). It probably wouldn't take very long to just refactor this into it's own function.

### Please check the following:
* [x]  No similar feature requests

**Comment by jethrokuan** [comment]
I'm not sure how useful this will be, but here's a function that does that:

```
(defun org-roam-collect-backlinks ()
  "Return a hashtable of file -> baclinks, for external use."
  (let ((ht (make-hash-table :test #'equal)))
    (maphash (lambda (file backlinks)
               (puthash file (hash-table-keys backlinks) ht))
             org-roam-backward-links-cache)
    ht))
```

**Comment by benide** [comment]
Cool, thanks. Jumping off from that, the code for the `org-roam-update` function, and learning some elisp, I've come up with the thing I was trying to explain. The first function works as expected, and now I just need to fill in the line with the comment to finish this idea up.

```elisp
(defun my/collect-backlinks-string (file)
  (org-roam--ensure-cache-built)
  (if-let
      ((backlinks (hash-table-keys (gethash file org-roam-backward-links-cache))))
      (-reduce-from
       (lambda (x file-from)
	 (concat x (format "** [[file:%s][%s]]\n"
			   file-from
			   (org-roam--get-title-or-slug file-from))))
       "\n\n* Backlinks\n"
       backlinks)
    ""))

(defun my/roam-export (file)
  (interactive)
  (let ((backlinks (my/collect-backlinks-string file))
	()) ; create buffer `buf' and insert `backlinks' somewhere
    (org-hugo--export-to-md buf)))
```
