### ISSUE TITLE
org-roam-find-file does not accept spaces

### ISSUE THREAD

**Issue by alanz** [jethrokuan/org-roam#155]
### Brief Abstract

org-roam-find-file does not accept spaces

### Long Description

Invoking `org-roam-find-file` via the standard key binding `C-c n f` prompts for a name. It does not allow you to enter spaces for the name, as it pops up a message `[sole completion]` instead.

BUT, if you copy a region of text as a title, and paste it in the input area, it does create a file, with the spaces replaced by `_`.

It should be possible to do the same process manually.

**Comment by jethrokuan** [comment]
> It does not allow you to enter spaces for the name, as it pops up a message [sole completion] instead.

This is some setting controlled by whatever you are using for `completing-read`: `ido`, `helm`, `ivy`, or `selectrum`. It's not something that org-roam handles.

**Comment by alanz** [comment]
Thanks. I am running vanilla completion at the moment, will look at using an alternative.
