### ISSUE TITLE
Having roam links be a different color from other links (external links).

### ISSUE THREAD

**Issue by yangnom** [jethrokuan/org-roam#161]
### Brief Abstract
It would be nice if the roam links stood out from other links, like website links and links to other org-mode files

### Long Description
I found 

> By default, links are inserted with the title as the link description. This can make them hard to distinguish from external links. If you wish, you may choose add special indicators for Org-roam links by tweaking org-roam-link-title-format, for example:

`(setq org-roam-link-title-format "R:%s")`
in the documentation, but it'd be nicer to have the links stand out with a different color rather than have some distinguishing letters attached to the link.  Maybe there is an emacs way of doing this with that I don't know.

It might also be nice if instead of having a variable(?) for noting org-roam links, there was a variable for marking _non_org-roam links, something like

`(setq org-roam-non-link-title-format)` or something.  I apologize as I'm not a programmer and am barely capable of using emacs in general (though I boldy try)

### Please check the following:
- [ ] No similar feature requests

**Comment by jethrokuan** [comment]
I agree that this would be nice. This should be achievable via heuristic font-locking. That is, if we assume that every `file:` link with a relative path, and a `.org` or `.org.pgp` extension is a roam link.

**Comment by l3kn** [comment]
`org-link-set-parameters` has a `:face` property that can be either a face or a function returning a face based on the link's path. This function could check if the path is part of org-roam and return a custom face or fall back to the `org-link` face.

Using the `:activate-func`, you could also place an overlay (e.g. with a "R" in it) in front of the link
without changing `org-roam-link-title-format`.

See http://kitchingroup.cheme.cmu.edu/blog/2016/11/04/New-link-features-in-org-9/ for more information on the new link features.

**Comment by jethrokuan** [comment]
Thanks @l3kn , this is very helpful.

**Comment by jethrokuan** [comment]
This should be added now.

**Comment by yangnom** [comment]
Firstly, wow, and thank you so much for adding this so quickly!
In the documentation it now says

> You may also choose to simply style the link differently, by customizing org-roam-link-face (M-x customize-face org-roam-link)

which is great, but it would be nice to have an example of the code you could put in a `config.el` file that showed setting the links to gold, or bold, or any other things.

I'm pretty sure this type of stuff is trivial, but for someone like me who is just learning, this can be a _very_ valuable little tidbit that can be applied to other customizations I'm trying to learn.

just this little
`(setq org-roam-link-title-format "R:%s")` was extraordinarily helpful!

I don't mean to be demanding, I'm just trying to give input on what it's like being an absolute novice if you care to cater to the likes of us 😄

**Comment by jethrokuan** [comment]
I provided an example in https://github.com/jethrokuan/org-roam/pull/162, if you really want to move that configuration to your `init.el`.

In any case, I think `customize-face` is a perfectly good interface to use to customize faces... especially for novices.
