### ISSUE TITLE
org-roam-insert not making new files. 

### ISSUE THREAD

**Issue by visuelledata** [jethrokuan/org-roam#17]
It's inserting links to existing files, but not making new files.   
  
Error message:  
`Symbol's function definition is void: make-empty-file`

**Comment by jethrokuan** [comment]
Looks like `make-empty-file` was only introduced in Emacs 27.1. I'll introduce a poly-fill.

```
make-empty-file is an interactive compiled Lisp function in
‘files.el’.

(make-empty-file FILENAME &optional PARENTS)

  Probably introduced at or before Emacs version 27.1.
```

**Comment by jethrokuan** [comment]
I think I've merged a fix. Let me know if that works for you.

**Comment by visuelledata** [comment]
Works!
