### ISSUE TITLE
Melpa release

### ISSUE THREAD

**Issue by rasendubi** [jethrokuan/org-roam#171]
### Brief Abstract
Would you like to upload org-roam to melpa? That would make it much easier for users to install.

### Please check the following:
- [x] No similar feature requests

**Comment by jethrokuan** [comment]
This will be deferred until `org-roam`'s API and usage is sufficiently stable.

**Comment by jethrokuan** [comment]
A PR to melpa has been made at https://github.com/melpa/melpa/pull/6738

**Comment by jethrokuan** [comment]
MELPA PR went through!
