### ISSUE TITLE
cool idea! some feedback

### ISSUE THREAD

**Issue by wrycode** [jethrokuan/org-roam#174]
Hi @jethrokuan 

I'm trying to build a personal wiki with Org-mode and I independently came to many of the same conclusions about note-taking. 

I was excited about org-roam, especially after [this quote](https://blog.jethro.dev/posts/introducing_org_roam/):

> First, in org-roam, the ordinary org file-link syntax is used. Contrast this with org-brain which uses org heading IDs, and zetteldeft that uses a special indicator. Org-roam is a plug-and-play solution that should work with existing Org files. This means org-roam can remain small, and its behaviour is predictable (it’s just 300 LOC now).

Using normal org functions (like the link syntax) is great. It's why I use [deft](https://jblevins.org/projects/deft/). I don't want to deviate much (if at all) from vanilla org for obvious reasons. 

I don't want new files to have a timestamp identifier _in the filename_. I tried to use templates to accomplish this like this:
```lisp
(defun my-org-roam-no-timestamp-in-title (title)
    (let ((slug (org-roam--title-to-slug title)))
      (format "%s" slug)))

(setq org-roam-templates
    (list (list "default" (list :file #'my-org-roam-no-timestamp-in-title
:content "#+TITLE: ${title}"))))
```
That works, but there may be a better way to do it, maybe that information should go on the configuration page.

Anyway, at this point I decided to deviate from Org-roam's workflow - I agree with the premise of breaking writing and note taking into individual interlinked memes, but I prefer to use Org's ID property. They allow me to rename or move headlines without breaking links, and filenames can be identifiers for the meme or a collection of memes or something else (renaming them doesn't change anything). 

Using deft and some fragile yet functional keyboard macros I can add all the linking functionality I need
```lisp
(local-set-key (kbd "C-c w l") #'region-to-meme) ;; turn selected text into a link to existing/new file using deft
(local-set-key (kbd "C-c w m") #'copy-meme-id) ;; copy id of the top-level heading for searching
(local-set-key (kbd "C-c w s") #'copy-section-id))) ;; copy id of current section for searching
```

The last two return an ID that I can then search using [helm-org-rifle](https://github.com/alphapapa/org-rifle). This is my hacked-together version of the "backlinks", but it's not ideal. How difficult would it be to add an org-roam option to support this workflow? I want a "backlinks" buffer that shows both file and ID links to either the top or current heading. 

I'm open to working on this if it's a feature that belongs in Org-roam and you can point me in the right direction. If not, no worries.

**Comment by jethrokuan** [comment]
> That works, but there may be a better way to do it, maybe that information should go on the configuration page.

Nope, that is the way to do it, or you could patch/override the original function.

> They allow me to rename or move headlines without breaking links

Renaming and moving notes will unlikely get first-class support. It's not how Zettelkasten works, and I find it unnecessary.

> How difficult would it be to add an org-roam option to support this workflow? I want a "backlinks" buffer that shows both file and ID links to either the top or current heading.

It'd be pretty much a rewrite, I think. 

I think there are a number of people who want to use IDs like you. You're free to fork off Org-roam to support the ID workflow though.

**Comment by wrycode** [comment]
>Renaming and moving notes will unlikely get first-class support. It's not how Zettelkasten works, and I find it unnecessary.

Fair enough, but I expect it's a feature people are going to bother you about until you clarify that in the README. Zettelkasten is only one of several workflows supported by Roam research, and Roam itself supports renaming links. 

This is anecdotal, but I often start writing about a concept before I have a name for it.

>I think there are a number of people who want to use IDs like you. You're free to fork off Org-roam to support the ID workflow though.

If I do that I'll certainly refer to your work. Before I close this, do you want me to put that `org-roam-no-timestamp-in-title` thing in the configuration document?

**Comment by jethrokuan** [comment]
> Roam itself supports renaming links.

There's already some machinery around renaming and deleting files actually. Renamed files will cause links to also be renamed, same as Roam. But this doesn't extend to Org outline headers.

> Before I close this, do you want me to put that org-roam-no-timestamp-in-title thing in the configuration document?

Sure!

**Comment by alphapapa** [comment]
> The last two return an ID that I can then search using [helm-org-rifle](https://github.com/alphapapa/org-rifle). This is my hacked-together version of the "backlinks", but it's not ideal. How difficult would it be to add an org-roam option to support this workflow? I want a "backlinks" buffer that shows both file and ID links to either the top or current heading.

FYI, I'm adding a predicate to `org-ql` that matches against Org links, so you could do a query like `(org-ql-search `(link :target ,(file-name-nondirectory (buffer-file-name)))`, or something like that.  Should generally work better than doing those kinds of searches with `helm-org-rifle`.

**Comment by wrycode** [comment]
@alphapapa maybe I will switch to org-ql. Is there a way to add more context to the results like helm-org-rifle?

**Comment by alphapapa** [comment]
The link predicate is added: https://github.com/alphapapa/org-ql/commit/9a56141f6c2ff2b8c6f92f93a218f4935b8f0335

> Is there a way to add more context to the results like helm-org-rifle?

Not yet, unless you want to edit a little code yourself.  That feature is planned.  For now, that is a distinguishing feature of helm-org-rifle.

**Comment by mgarort** [comment]
Hi,

I just wanted to say, for the purpose of feedback, that I too start writing about a concept before I have a name for it. A lot of the time it is difficult enough to create an atomic note that encapsulates what you have in mind, so creating an appropriate title for it beforehand is even more challenging. i don't know if that's the purist zettelkasten way, but I do feel that being able to rename and delete notes would be a killer feature for me.

This would have some very useful applications: for instance, you could go back to the same note and polish it more as more information comes along. If you are a purist zettelkastener you may say that in this case you should just add another note. But well, sometimes it's just a very small addition and adding an entire new note would be overkill. If you have polished enough notes, you can use them not only in your zettelkasten but also at university, for example. And that doesn't mean they lose all their value for your zettelkasten.

These are just my 2 cents and obviously I may be wrong in general, but it is what would be ideal for my workflow.

Thanks.
