### ISSUE TITLE
org-roam links appear to break formatting of org-mode documents

### ISSUE THREAD

**Issue by anthonyclarka2** [jethrokuan/org-roam#180]
### Description

When I insert a link into an org-mode document with `org-roam-insert` the link is rendered in plain text with markup surrounding it.

If I comment out the org-roam init code in my `~/.spacemacs` and restart Emacs, then the document is rendered as in "expected results". Since the code that inherits the face customization is pretty simple, I'm kind of at a loss on how to further debug this. If I could be given some more pointers on where to look next or what to test, I'd be happy to chase this down further. Apologies for a possible waste of time.

#### Steps to Reproduce

Using the atom-one-dark-theme package.

org-roam-link face is set to inherit from org-link (as per default). org-link inherits from link which is defined as:

```lisp
  `(link ((t (:foreground ,atom-one-dark-blue :underline t :weight bold))))
```

Relevant sections of ~/.spacemacs:

```lisp
    ;; https://org-roam.readthedocs.io/en/develop/configuration/
    (use-package org-roam
      :after org
      :load-path "private/org-roam/"
      :hook 
      ((org-mode . org-roam-mode)
        (after-init . org-roam--build-cache-async) ;; optional!
        )
      :custom
      (org-roam-directory "~/Org/")
      :bind
      ("C-c n j" . org-journal-new-entry)
      ("C-c n l" . org-roam)
      ("C-c n t" . org-roam-today)
      ("C-c n f" . org-roam-find-file)
      ("C-c n i" . org-roam-insert)
      ("C-c n g" . org-roam-show-graph)
      ) ;; end of use-package org-roam
```

```lisp
  (custom-set-faces
  '(org-document-info ((t (:foreground "#828997" :slant italic :weight light))))
  '(org-level-1 ((t (:inherit outline-1 :slant italic :weight bold :height 1.2))))
  '(org-level-2 ((t (:inherit outline-2 :weight semi-bold :height 1.1))))
  )
```

#### Expected Results

https://i.imgur.com/hCJFTrY.png

#### Actual Results

https://i.imgur.com/MmWpGKK.png

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Spacemacs: https://github.com/syl20bnr/spacemacs/commit/733a3a8199cdd8b290c4b2864f2ed93aa262c136
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/d780b6ffd176fbbfe863c2fccfba0f29e1b60d0d

**Comment by anthonyclarka2** [comment]
If the face for `org-roam-link` is customized with `M-x customize-face` and set to:

```lisp
 '(org-roam-link ((t (:foreground "blue" :underline "blue" :weight bold))))
```

Then the link text is still displayed at plain text with markup as in https://i.imgur.com/MmWpGKK.png

Also notice the "NEXT" "TODO" org-level-2 entries below the "Text Text Text" line. They lose their color formatting but not the weight. It's weird, and I hope someone can point out what I can do to fix this :)

**Comment by jethrokuan** [comment]
You need to upgrade your org version to at least 9.0

**Comment by jayemar** [comment]
I believe I'm having the same issue.  I have emacs v27.0.50 and org-mode v9.1.9.  If org-roam-mode is disabled, links work as expected and can be expanded/closed using org-toggle-link-display; however, then the backlinks do not work.  If I have org-roam-mode enabled, backlinks work properly, but links are always shown as plain text with markup surrounding it as initially described.
When I call org-toggle-link-display, I receive the following message in my Messages buffer:
`Error during redisplay: (jit-lock-function 1) signaled (wrong-type-argument integer-or-marker-p nil)`

**Comment by anthonyclarka2** [comment]
I performed the following steps which fixed this issue for me in Spacemacs:

1. Backed up `~/.emacs.d/private`
1. Removed `~/.emacs.d/`
1. Ran `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
1. Switched to the develop branch of Spacemacs: `cd ~/.emacs.d; git checkout develop`
1. Restored `~/.emacs.d/private`
1. Started Emacs and opened an org-mode document.

That gave me org-mode 9.3.6.

Switching to the Spacemacs custom layer for org-roam didn't change the behaviour before this fix.

Thank you for your help, I really appreciate it!

**Comment by komali2** [comment]
I'm having this issue as well, with org 9.1.9. I'll see if updating fixes it.

**Comment by changs** [comment]
Hi. Upgrading `org` to `9.3.6-17-g389288-elpa ` fixed the problem for me.

**Comment by jayemar** [comment]
Upgrading org to 9.3.6 also fixed this for me.

**Comment by jethrokuan** [comment]
Maybe 9.0 is still too old. I can't find the part about `org-link-set-parameters` in the release notes as well, but I'm hesitant to require `9.3.6` as the minimum version.

**Comment by jethrokuan** [comment]
I'm going to gracefully enable this functionality for Org versions `>=9.2`, so things don't break for people on old Org versions.

**Comment by igoralmeida** [comment]
> I believe I'm having the same issue. I have emacs v27.0.50 and org-mode v9.1.9. If org-roam-mode is disabled, links work as expected and can be expanded/closed using org-toggle-link-display; however, then the backlinks do not work. If I have org-roam-mode enabled, backlinks work properly, but links are always shown as plain text with markup surrounding it as initially described.
> When I call org-toggle-link-display, I receive the following message in my Messages buffer:
> `Error during redisplay: (jit-lock-function 1) signaled (wrong-type-argument integer-or-marker-p nil)`

Same here with **org-version 9.2.5**. I can _almost_ get it to work by disabling org-roam-mode, toggling the link display a couple of times (apparently it then picks up the correct face), and reenabling org-roam-mode afterwards, but the backlinks buffer stops working (I will visit a note and the backlinks buffer will not update).

**Comment by komali2** [comment]
For what it's worth, the links work for me after I restart and do the steps mentioned in https://github.com/jethrokuan/org-roam/pull/133#issuecomment-591012743
