### ISSUE TITLE
Help me hide radio tags `<<<>>>` from roam node name

### ISSUE THREAD

**Issue by nazzacode** [jethrokuan/org-roam#1903]
### Brief Abstract
Ability to hide radio target syntax `<<<>>>` from an org-roam nodes `name` representation.

### Long Description
Hey there! I'm a big user of radio targets to create documents with a a quantity and automation of interlinking that is not really practical using org-roam (manual ID links) alone. However, radio-targets have a verbose syntax which interferes with my org-roam workflow and currently I am picking between the two on a per document basis. 

For example its can be problematic in, 

1. Reading the `org-roam-node-find` minibuffer.
![radio_roam1](https://user-images.githubusercontent.com/47322035/137040130-6db4ee09-2dc7-4efa-a238-7a05beb5b11b.png)

2. When inserting links with `org-roam-node-insert`
![radio_tags2](https://user-images.githubusercontent.com/47322035/137043625-185493c8-992f-4444-b859-39d89785515a.png)

3. Most frustratingly, when viewing graphs with `org-roam-ui` wich I use for presentations
 ![radio_tags3](https://user-images.githubusercontent.com/47322035/137140789-ef019d61-1b9a-4ac2-bfb2-cfdab3a7f004.png) 

I've seen from a previous request  (#1010) that radio tags are unlikely to be incorporated into org roam any time soon (which is a shame) but what I was wondering is if there is any way to hide/strip the radio tags syntax `<<<>>>` and `<<>>` in from the org-roam representation of the node name for prettier viewing. 

I feel like this should be possible and might just require applying a regex in the right place.

### Proposed Implementation (if any)
As you'll see from the first image in this post, its possible to hide radio tags in an emacs buffer [code shown here](https://emacs.stackexchange.com/questions/19230/how-to-hide-targets).

### Please check the following:
- [x] No similar feature requests

**Comment by natask** [comment]
@nazzacode My Apologies. The first result node in the your first picture is "Blockchains and Cryptocurrency > Wiki >  <<<Ethereum>>>". The text is indented, colored and I am guessing  ""Blockchains and Cryptocurrency > Wiki >" is the path(ancestor headline titles) to the headline `titled` "<<<Ethereum>>>". What configuration for org-roam variables like `org-roam-node-display-template`, `org-roam-node-annotation-function` leads to this outcome.

On the topic of this issue, There are two major ways to hide radio tags. One is to create a new function for `org-roam-node-display-template`. Another is to parse headline titles with <<<>>> removed. The former is going to only affect functions or libraries that depend on `org-roam-node-display-template` like `org-roam-node--format-entry`. I am not sure if it would affect org-roam-ui. The latter is global, it affects the database and any downstream library. I believe the latter is a better choice. For latter, you would want to look into the function `org-roam-db-insert-node-data` within file `org-roam-db.el`. 

override with the following function. you would need to rebuild you database after `(org-roam-v2-db-sync 'force)`. 

``` elisp
(cl-defun org-roam-v2-db-insert-node-data-h ()
  "Insert node data for headline at point into the Org-roam cache.
Hide radio tags."
  (when-let ((id (org-id-get)))
    (let* ((file (buffer-file-name (buffer-base-buffer)))
           (heading-components (org-heading-components))
           (pos (point))
           (todo (nth 2 heading-components))
           (priority (nth 3 heading-components))
           (level (nth 1 heading-components))
           (scheduled (org-roam-v2-db-get-scheduled-time))
           (deadline (org-roam-v2-db-get-deadline-time))
           (title (or (nth 4 heading-components)
                      (progn (lwarn 'org-roam-v2 :warning "Node in %s:%s:%s has no title, skipping..."
                                    file
                                    (line-number-at-pos)
                                    (1+ (- (point) (line-beginning-position))))
                             (cl-return-from org-roam-v2-db-insert-node-data))))
           (title (replace-regexp-in-string "<<<\\(.*?\\)>>>" "\\1" title)) ;remove radio tags
           (properties (org-entry-properties))
           (olp (org-get-outline-path nil 'use-cache))
           (title (org-link-display-format title)))
      (org-roam-v2-db-query!
       (lambda (err)
         (lwarn 'org-roam-v2 :warning "%s for %s (%s) in %s"
                (error-message-string err)
                title id file))
       [:insert :into nodes
        :values $v1]
       (vector id file level pos todo priority
               scheduled deadline title properties olp)))))
```

``` elisp
(advice-add  'org-roam-v2-db-insert-node-data :override  'org-roam-v2-db-insert-node-data-h)
```
in the future, can have a org roam variable holding a function that applies on title parsed. Then would only need to store the following lambda in the variable.

``` elisp
(setq org-roam-parse-node-title-transform (lambda (title) (replace-regexp-in-string "<<<\\(.*?\\)>>>" "\\1" title)))```

**Comment by nazzacode** [comment]
Wow. That was was amazing. Thank you.

Note: I used the 1st solution.

As for your initial questions: 

The value of `org-roam-node-display-template` is:
```elisp
(defcustom org-roam-node-display-template
  "${title:*} ${tags:10}"
  :group 'org-roam
  :type  'string)
```
and the value of `org-roam-node-annotation function` is: 
```
(defcustom org-roam-node-annotation-function #'org-roam-node-read--annotation
  :group 'org-roam
  :type 'function)
```
I'm not sure is this is helpful/still relevant. Note, I'm running doom-emacs with the `+roam2` flag enabled.

Thanks again!
