### ISSUE TITLE
Unable to link from :PROPERTIES: drawer.

### ISSUE THREAD

**Issue by teesloane** [jethrokuan/org-roam#195]
### Description

I am working to create my own templates for eventually compiling a site from org-roam. I'd like to have some meta information for each file that will eventually be parsed separately from the file's contents. It appears that using a properties drawer doesn't work with back linking.

#### Steps to Reproduce

- Open emacs
- Create a `parent.org` file
- Create `child1.org` file - add the following:

<details> 

```
#+TITLE: child1
#+DATE_CREATED: 2020-02-26--16-21
#+FILE_UNDER: research

* Meta
:PROPERTIES:
:file_under: [[file:parent_2020-02-26--16-22.org][parentº]]
:related: ?
:slug: ?
:END:
:LOGBOOK:
:END:
* Resources
* Notes
```

</details>

- create `child2.org` with the contents:

<details>

```
#+TITLE: child2
#+DATE_CREATED: 2020-02-26--16-21

* Meta
:PROPERTIES:
:file_under: ?
:related: ?
:slug: ?
:END:
:LOGBOOK:
:END:

[[file:parent_2020-02-26--16-22.org][parentº]]
```

</details>

#### Expected Results

`parent.org` is able to display backlinks to both `child1.org` and `child2.org`

#### Actual Results

`parent` only displays one of the backlinks.

### Versions
- Emacs (`C-h v emacs-version`): 
GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/b2dc9b33f6a852f70483113c8b69f00d3e23ca86

Screenshot:

<img width="1400" alt="Screen Shot 2020-02-26 at 4 25 20 PM" src="https://user-images.githubusercontent.com/12987958/75390036-9330df80-58b5-11ea-950e-ef9f0c6426cd.png">

**Comment by teesloane** [comment]
Additional information - how I have configured my use of the package:

```elisp
(defun org-roam--title-maker (project-type)
  "Is used to create the FILE NAME for an org-roam-file.
   Returns a func: used by the org-roam-template '(list :file <FUNC>)
   @param - project-type"
  (lambda (title)
    (let ((timestamp     (format-time-string "%Y-%m-%d--%H-%M" (current-time)))
          (slug (org-roam--title-to-slug title)))
      (if project-type
          (format "%s_%s_%s" project-type slug timestamp)
          (format "%s_%s" slug timestamp)))))

(defun get-string-from-file (filePath)
  "Return filePath's file content."
  (with-temp-buffer
    (insert-file-contents filePath)
    (buffer-string)))

(defun org-roam--content-template (project-type)
  "Generates the 'front-matter' of the org files for org-roam"
   (let* ((timestamp       (format-time-string "%Y-%m-%d--%H-%M" (current-time)))
          (nl              "\n")
          (title           "#+TITLE: ${title}")
          (date_created    (concat "#+DATE_CREATED: " timestamp))
          (base-template   (concat title nl date_created nl))
          (adv-template    (cond
                            ((string= project-type "default") (get-string-from-file "~/.doom.d/templates/org-roam-default.org"))
                            ((string= project-type "project") (get-string-from-file "~/.doom.d/templates/org-roam-project.org"))
                            ((string= project-type "research") (get-string-from-file "~/.doom.d/templates/org-roam-research.org"))
                            (t "")))
          (template         (concat base-template adv-template)))
     template))


(use-package! org-roam
  ;; :after org
  :hook (after-init . org-roam-mode)
  :config
  (setq-default
   org-roam-directory "~/Dropbox/wiki"
   org-roam-link-title-format "%sº" ;; appends a  `º` to each Roam link.
   org-roam-templates
   ;; templates for creating a new note.
   ;; FIXME: mapcar / macroize this
    (list (list "default"   (list :file (org-roam--title-maker nil)
                                  :content (org-roam--content-template "default")))
          (list "proj"      (list :file  (org-roam--title-maker "proj")
                                  :content (org-roam--content-template "project")))
          (list "research"  (list :file  (org-roam--title-maker "research")
                                  :content (org-roam--content-template "research")))
          (list "priv"      (list :file  (org-roam--title-maker "priv")
                                  :content (org-roam--content-template "priv")))))
  ;; (org-roam-mode)
  (org-roam--build-cache-async))
```

**Comment by jethrokuan** [comment]
Property drawers are treated a bit differently from normal drawers, and aren't parsed the same way. It'd be best if you changed it to just a normal drawer (anything but `PROPERTIES`), and backlinks will just work.

Also, I hope you're not investing too much time into the templating system, I'm going to move to relying on org-capture instead of rewriting one here.

**Comment by stefanv** [comment]
I was trying to get timestamps working, but reading through the above source: won't it give all the files the same timestamp?

#193 should make this trivial.

**Comment by teesloane** [comment]
> Property drawers are treated a bit differently from normal drawers, and aren't parsed the same way. It'd be best if you changed it to just a normal drawer (anything but `PROPERTIES`), and backlinks will just work.

That fixed it! Thanks!

> Also, I hope you're not investing too much time into the templating system, I'm going to move to relying on org-capture instead of rewriting one here.

All good — I've just been fiddling / using it as a reason to learn more elisp.
