### ISSUE TITLE
Documentation: duplicate files

### ISSUE THREAD

**Issue by stefanv** [jethrokuan/org-roam#197]
The documentation states:

> A common hassle is ensuring that files are uniquely named within the Org-roam directory.

Could I ask, when would this situation occur?  My guess is if you name a file one thing, but then change the title (inside the file) later on?

The manual provided a mechanism for switching timestamps in filenames off, but I didn't want to do that if there is a compelling reason to keep the default behavior.

**Comment by jethrokuan** [comment]
It'll only really happen when the title sanitizes to a filename that matches a current file. E.g. "Hello" and "hello". Basically it's rare, but timestamped filenames prevent that from ever happening.

**Comment by stefanv** [comment]
Thank you, I appreciate the clarification.

**Comment by stefanv** [comment]
(It does seem like the intent of the user, in that case, may have been to find the original file? Will think about it some more :)

**Comment by jethrokuan** [comment]
Yep, I haven't really figured it out yet either, but the timestamps on the files do give me some useful information at least.
