### ISSUE TITLE
ox-hugo export and roam links

### ISSUE THREAD

**Issue by yangnom** [jethrokuan/org-roam#201]
### Brief Abstract
It'd be good if org-roam links could succesfully be exported via ox-hugo

### Long Description
I've noticed that @jethrokuan is using ox-hugo as far as I can tell, but when I try to export an org-roam file with ox-hugo, the org-roam links break in the export.  It'd be cool if they didn't or maybe there's someway to have them not do so that I don't know about.  I'm also on master and not develop if something has changed...

### Please check the following:
- [ ] No similar feature requests

**Comment by jethrokuan** [comment]
Org-roam doesn't mess with exporting. I do use ox-hugo, and everything works. More details on what is failing would be helpful

**Comment by yangnom** [comment]
This is the org (org-roam) file I made
```
#+TITLE: export difficulties
#+HUGO_BASE_DIR: ~/www/me/



* My normal stuff, everything is nice
and then an org link to my [[file:20200223220645_emacs.org][emacs]] file which will export /funkily/
```

which got exported via ox-hugo as
```
+++
title = "export difficulties"
author = ["ynom"]
draft = false
+++

## My normal stuff, everything is nice {#my-normal-stuff-everything-is-nice}

and then an org link to my [emacs]({{< relref "20200223220645_emacs" >}}) file which will export _funkily_
```
and I got this error in terminal
```
ERROR 2020/02/28 03:02:00 [en] REF_NOT_FOUND: Ref "20200223220645_emacs": "/Users/ynom/www/me/content/posts/20200228025935_export_difficulties.md:9:36": page not found
Total in 9 ms
ERROR 2020/02/28 03:02:00 Rebuild failed:

ERROR 2020/02/28 03:02:00 Logged 1 error(s)
```
It very well could be something I am failing to do on my part with hugo or ox-hugo.

**Comment by jethrokuan** [comment]
You didn't export that `emacs` org file to md

**Comment by yangnom** [comment]
ahhhhh, I was hoping that it would just leave the word `emacs` without the link.  I guess I'll have to look into ox-hugo to see if there is an option for dealing with links to non-markdown non-url files.
Thank you.
