### ISSUE TITLE
Error (use-package): Failed to parse package org-roam: use-package: Unrecognized keyword: :straight

### ISSUE THREAD

**Issue by isfttr** [jethrokuan/org-roam#202]
### Description

Disclaimer: I'm using Doom Emacs configuration.

Following the installation steps for using `git clone` I chose the `.doom.d`, instead of the `.emacs.d` folder.

`
(use-package org-roam
      :load-path "elisp/"
      :hook
      (after-init . org-roam-mode)
      :straight (:host github :repo "jethrokuan/org-roam" :branch "develop")
      :custom
      (org-roam-directory "~/repositories/org/")
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n g" . org-roam-show-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))))
`

After reloading emacs, I get the following error:
`Error (use-package): Failed to parse package org-roam: use-package: Unrecognized keyword: :straight`

#### Steps to Reproduce

1. Load Emacs.
2. Open 'packages.el' on .doom.d folder, pasted the code above and saved it.
3. Reload Emacs and get error message `Error (use-package): Failed to parse package org-roam: use-package: Unrecognized keyword: :straight`

### Versions
- Emacs (`C-h v emacs-version`): v26.3

**Comment by bdarcus** [comment]
You might look at #179 for some ideas.

I'm no expert, but doom has the `usepackage!` wrapper, which actually uses straight behind the scenes.

**Comment by jethrokuan** [comment]
yeah I think it'll look something like this for doom emacs:

```
(package! org-roam
  :recipe (:host github :repo "jethrokuan/org-roam" :branch "develop"))

(use-package! org-roam
  :hook (after-init . org-roam-mode)
  :config
  (setq org-roam-directory "~/Notes/roam")

  (map!
   "C-c n l" #'org-roam
   "C-c n t" #'org-roam-today
   "C-c n f" #'org-roam-find-file
   "C-c n i" #'org-roam-insert
   "C-c n g" #'org-roam-show-graph
   )
  )
```

**Comment by ppmw99** [comment]
I am getting the same problem as isfttr (above) but I am using runemacs 26.3 on a Windows 10 PC. Any thoughts on how I can adapt this to run?   very keen on using this  (currently do everything in org-mode and deft )

**Comment by jethrokuan** [comment]
Does the snippet in the above comment not work?

I think it would be good to wait for a couple of days. I'm merging a big change (#200), and I think that will be better to figure out the installation process after that

**Comment by ppmw99** [comment]
I get   "symbol's function definition is void: package!"         loving the idea of using a db behind roam.

**Comment by jethrokuan** [comment]
I suppose you're not using Doom then. If you're on vanilla Emacs, I'd recommend using the straight package manager and use-package anyway, the setup instructions can be found on its README.

https://github.com/raxod502/straight.el

**Comment by isfttr** [comment]
> yeah I think it'll look something like this for doom emacs:
> 
> ```
> (package! org-roam
>   :recipe (:host github :repo "jethrokuan/org-roam" :branch "develop"))
> 
> (use-package! org-roam
>   :hook (after-init . org-roam-mode)
>   :config
>   (setq org-roam-directory "~/Notes/roam")
> 
>   (map!
>    "C-c n l" #'org-roam
>    "C-c n t" #'org-roam-today
>    "C-c n f" #'org-roam-find-file
>    "C-c n i" #'org-roam-insert
>    "C-c n g" #'org-roam-show-graph
>    )
>   )
> ```

I just tested and it worked. Thanks :+1:

**Comment by jethrokuan** [comment]
I'm going to close this issue. When this goes on MELPA, hopefully all the problems will go away, since it can be installed via `package-install` for regular users.

**Comment by raxod502** [comment]
I just wanted to comment because nobody seemed to have explained why the error message occurred in the first place. It's because `straight.el` needs to be loaded at runtime in order to be used via `use-package` with the `:straight` keyword. Otherwise that keyword simply won't be defined. I suspect that this problem came up because you were trying to use `straight.el` during runtime in Doom, which is (I believe) incorrect usage since Doom prefers to do all the package-management stuff separately before startup, and not load the package manager at runtime. Could be wrong though; I haven't tested anything and don't use Doom.
