### ISSUE TITLE
Graph generation fails if page title includes a double quote

### ISSUE THREAD

**Issue by alanz** [jethrokuan/org-roam#205]
### Description

If you create a node with a title of something like `Look into "Foo Bar"`, the filename is properly escaped, but when the `graph.dot` file is generated the double quotes are not escaped.

See discussion in https://github.com/jethrokuan/org-roam/pull/200#issuecomment-592949098

### Versions
- Emacs (`M-x version`): 
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-09-09, modified by Debian

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/0c2aaad3df9d1036255db9e629d407833c09b2e3

**Comment by alphapapa** [comment]
I had the same problem in org-graph-view: https://github.com/alphapapa/org-graph-view/issues/3#issuecomment-582564785.  A user mentioned an alternative way to do some of the code: https://github.com/alphapapa/org-graph-view/issues/5.  I tried it and it worked: https://github.com/alphapapa/org-graph-view/commit/13314338d70d2c19511efccc491bed3ca0758170  Maybe some of that info will be helpful here.  :)

**Comment by alanz** [comment]
Works for me now, thanks.
