### ISSUE TITLE
database not updated automatically

### ISSUE THREAD

**Issue by brabalan** [jethrokuan/org-roam#206]
### Description
Since switching to the new sql database, it does not seem to update automatically

#### Steps to Reproduce
- create a new file `foo` using `org-roam-insert`
- navigate to another roam file
- try to do `org-room-insert` with `foo`
- `foo` is not in the list of files proposed
- running `org-roam-build-database` solves the issue

### Versions
- Emacs (`C-h v emacs-version`): GNU Emacs 26.3 
- Org-roam commit: I don't know, as of today

**Comment by jethrokuan** [comment]
did you restart emacs after the switch?

**Comment by brabalan** [comment]
I did restart emacs. It does not seem to happen to every file, however, but I don't know how to trigger it.

**Comment by jethrokuan** [comment]
> foo is not in the list of files proposed

I can replicate this, it's because even though the file was created, the database wasn't updated for the created file.

**Comment by brabalan** [comment]
Thanks!

**Comment by zylinski** [comment]
I am experiencing an issue as described in the parent post. MELPA install. I do not have the command `org-roam-build-database`. I can create a file using `org-roam-find-file`. But, I need to restart my emacs to see it.

org-roam version 1.2.3

**Comment by d12frosted** [comment]
@zylinski try `org-roam-db-build-cache`

**Comment by d12frosted** [comment]
@zylinski btw, I advice to checkout [Getting Started][1] section of the documentation 😸 It describes how to build the cache and describes when the cache is automatically built (and how to configure that). 

[1]: https://www.orgroam.com/manual.html#Getting-Started

**Comment by pajot** [comment]
I am experiencing this same problem. The cache updates only if I run org-roam-db-build-cache manually. I do not see any activity otherwise, not even an error. (I have tried running toggle-debug-on-error.)

**Comment by albreche** [comment]
> I am experiencing this same problem. The cache updates only if I run org-roam-db-build-cache manually. I do not see any activity otherwise, not even an error. (I have tried running toggle-debug-on-error.)

same problem here,  emacs-29.1, org-roam 2.2.2, org-roam-db-on-save set to t and db updated at each emacs startup

**Comment by kascesar** [comment]
Same here
