### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by anthrolisp** [jethrokuan/org-roam#21]
This is awesome. Thank you. A couple of questions:
- Do you keep your TODO out of your org-roam folder? If not, how do you handle them? Isn't org-mode slow to parse the TODOs from all of the files?
- Do you keep all of your notes in one org-roam folder? Or do you imagine having multiple org-roams? 

Many thanks!

**Comment by jethrokuan** [comment]
Thank you!

1. Yes, they are in a separate directory, but they could be in the same directory. I don't think to-dos will add much compute time on top of the note files, which are likely to be much larger. (It's roughly linear in LOC)
2. Yes I do. I won't have multiple org-roams.
