### ISSUE TITLE
Opening yesterday's org-roam file

### ISSUE THREAD

**Issue by jackbaty** [jethrokuan/org-roam#214]
### Brief Abstract
I often want to open the "daily notes" file for yesterday

### Proposed Implementation (if any)
Since we already have `org-roam-tomorrow` it's doesn't feel like a significant leap to have `org-roam-yesterday` as well. Could it be as simple as...?

```
(defun org-roam-yesterday ()
  "Create and find the file for yesterday."
  (interactive)
  (let ((path (org-roam--file-for-time (time-add -86400 (current-time)))))
    (org-roam--find-file path)))
```

This does lead to perhaps wanting more generic functions that move between days (e.g. `org-roam-previous-day`) but I'd be happy with just adding one for yesterday :).

**Comment by bdarcus** [comment]
While we're on this, would be nice if the docs included info on the purpose of these functions.

#209

**Comment by jethrokuan** [comment]
If you rely heavily on the daily note-taking functionality, may I suggest using org-journal together with org-roam? That's what I do, and they have `org-journal-previous-entry`. I'd prefer not to reinvent org-journal.

I don't really mind adding `org-roam-yesterday`. It seems non-trivial to do a `org-roam-previous-entry`.

**Comment by jackbaty** [comment]
That's fair, and yep, org-journal already does this. I do use org-journal but only as a personal journal, whereas I use org-roam as a more topic-based tool and "lab notebook" and log. Using Roam sort of trained me to work that way :). I get not wanting to reinvent org-journal!

**Comment by jethrokuan** [comment]
Although I've never tried it, setting the directory-local variable for `org-journal-dir` should work, if you wish to use org-journal functionality in multiple places, although the functions would only work if you're within the org-roam directory.

**Comment by jackbaty** [comment]
Thanks, I'll give the local variables a shot.
