### ISSUE TITLE
org-protocol and org roam

### ISSUE THREAD

**Issue by technovangelist** [jethrokuan/org-roam#217]
### Description

The link from the graph in Firefox was working but now I try it and it does not. I got rid of the platypus files and started over, but the instructions are confusing. https://org-roam.readthedocs.io/en/develop/roam_protocol/ links (poorly formatted) to a set of instructions https://github.com/jethrokuan/org-roam/issues/115 but the two sets of intructions don't agree with each other, so not sure which is accurate.  When I click on the link in the graph, I see this:
<img width="885" alt="CleanShot 2020-03-02 at 14 04 34@2x" src="https://user-images.githubusercontent.com/633681/75708421-c47f2600-5c8e-11ea-9de5-2c15be1b8da4.png">
but /Users/matt.williams/org-roam does in fact exist. 

Not sure where the problem is.

#### Steps to Reproduce
Open a graph in firefox from org-roam
click one of the links
boom

#### Expected Results
Opens the right org file

#### Actual Results
asks to create a directory

### Versions
- Emacs 26.3
- Doom v2.0.9
macos 10.14.6

**Comment by jethrokuan** [comment]
Do you have `(require 'org-roam-protocol)` somewhere in your config? You get that because the roam protocols are not registered.

Sorry about the docs, will clean that up before 1.0.

**Comment by technovangelist** [comment]
Yes, thats in my config.el file.

**Comment by technovangelist** [comment]
Also, a few people have share their configs for doom emacs and none of them have anything like this require statement. Does anyone else use the graph feature?

**Comment by jethrokuan** [comment]
> Also, a few people have share their configs for doom emacs and none of them have anything like this require statement. 

This is relatively new. 

What happens if you evaluate the require manually? 

`(require 'org-roam-protocol)`

And enter `emacsclient "org-protocol://roam-file?file=/tmp/test.org"` in your terminal

**Comment by technovangelist** [comment]
Oh. The graph was there when I first saw it so assumed it had been there from the beginning.

**Comment by naistran** [comment]
I'm also using Doom Emacs and had to make a few changes for graph links to work with `org-protocol` on MacOS.

1. Doom `config.el`:

```elisp
(use-package! org-roam
  :commands (org-roam-insert org-roam-find-file org-roam org-roam-show-graph)
  :init
  (setq org-roam-directory org-directory)
  (setq org-roam-graph-viewer "/usr/bin/open")
  (map! :leader 
      :prefix "n"
      :desc "Org-Roam-Insert" "i" #'org-roam-insert
      :desc "Org-Roam-Find"   "/" #'org-roam-find-file
      :desc "Org-Roam-Buffer" "r" #'org-roam
      :desc "Org-Roam-Show-Graph" "g" #'org-roam-show-graph)
  :config 
  (org-roam-mode +1)
  (require 'org-roam-protocol)) ;; require org-roam-protocol here
  ```

2. Update the executable `launch-emacs.sh` script (I had the same error as you @technovangelist — updating the script fixed it):

```sh
#!/usr/bin/env bash
/usr/local/bin/emacsclient --no-wait $1
```

3. Re-create the Platypus app:

```
| Setting                        | Value                     |
|--------------------------------+---------------------------|
| App Name                       | "OrgProtocol"             |
| Script Type                    | "env" · "/usr/bin/env"    |
| Script Path                    | "path/to/launch-emacs.sh" |
| Interface                      | None                      |
| Accept dropped items           | true                      |
| Remain running after execution | false                     |
```

Click on `Settings` then:

```
| Setting                        | Value          |
|--------------------------------+----------------|
| Accept dropped files           | true           |
| Register as URI scheme handler | true           |
| Protocol                       | "org-protocol" |
```

With `org-protocol` it doesn't switch the window focus to Emacs when clicking on links by default. My fix:

```elisp
(defun my-org-protocol-focus-advice (orig &rest args)
  (x-focus-frame nil)
  (apply orig args))

(advice-add 'org-roam-protocol-open-ref :around
            #'my-org-protocol-focus-advice)
(advice-add 'org-roam-protocol-open-file :around
            #'my-org-protocol-focus-advice)
```

@jethrokuan I notice we're already using `raise-frame`. But it doesn't seem to have an effect on MacOS. Should we switch to `x-focus-frame` if it works on Linux?

## Note for Emacs Mac Port

If you're using [Emacs Mac Port](https://github.com/railwaycat/homebrew-emacsmacport), it seems to support `org-protocol` out of the box but doesn't really work. It registered its `Emacs.app` as the default handler for the URL scheme `org-protocol`. We have to make our `OrgProtocol.app` the default handler instead (replace `org.yourusername.OrgProtocol` with your app identifier):

```
$ defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add \
'{"LSHandlerPreferredVersions" = { "LSHandlerRoleAll" = "-"; }; LSHandlerRoleAll = "org.yourusername.OrgProtocol"; LSHandlerURLScheme = "org-protocol";}'
```

Then restart your computer.

**Comment by technovangelist** [comment]
Genius!!! Thanks so much for solving this. 

@naistran do you use firefox to view the graph or something else?

**Comment by naistran** [comment]
@technovangelist I'm still using Chrome currently.

**Comment by technovangelist** [comment]
@naistran any chance you are using the capture templates as well? would love to see how that is configured.

**Comment by jethrokuan** [comment]
> @naistran any chance you are using the capture templates as well? would love to see how that is configured.

Here's mine:

```
(setq org-roam-capture-templates
        '(("d" "default" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "${slug}"
           :head "#+SETUPFILE:./hugo_setup.org
#+HUGO_SECTION: zettels
#+HUGO_SLUG: ${slug}
#+TITLE: ${title}\n"
           :unnarrowed t)
          ("p" "private" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "private-${slug}"
           :head "#+TITLE: ${title}\n"
           :unnarrowed t)))
```

**Comment by jethrokuan** [comment]
> Update the executable launch-emacs.sh script

I'm not familiar with Platypus, but maybe the launch script can be moved into the Platypus app itself

**Comment by naistran** [comment]
With Platypus, the launch script does get copied into the app and you can edit it directly inside the `OrgProtocol.app` folder. However, when you're creating the app for the first time, you need to set the Script Path to an existing script file for Platypus to copy.

**Comment by technovangelist** [comment]
thank you so much

**Comment by technovangelist** [comment]
So the original question is solved, but I have a follow on so not sure if a new issue should be created. 

@naistran  The reason I asked about capture templates (which I should have mentioned) is that I am eager to get the bookmarklet working. I'd like to think of myself as a kinda bright guy, but I just can't get it. There is too much I should already know about emacs to get it. 

I tried your snippet above which is amazing because its one of the first examples that shows not only the template but how to include the template. I also tried replacing org-roam-capture-templates with org-roam-ref-capture-templates. Nothing seems to work. any pointers?

**Comment by jethrokuan** [comment]
Here's my unformatted bookmarklet:

```
javascript:location.href = 'org-protocol://roam-ref?ref='+encodeURIComponent(location.href) +'&title=' +         encodeURIComponent(document.title)
```

and my org-roam-ref-capture-template:

```
(setq org-roam-ref-capture-templates
        '(("r" "ref" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "websites/${slug}"
           :head "#+SETUPFILE:./hugo_setup.org
#+ROAM_KEY: ${ref}
#+HUGO_SLUG: ${slug}
#+TITLE: ${title}

- source :: ${ref}"
           :unnarrowed t)))
```

I think it's just one of the things that's hard to get working because it could've broke in many places:

1. capture template bad
2. bookmarklet bad
3. protocol not registered

**Comment by technovangelist** [comment]
That was super helpful. Whats the benefit to you of have the url in both roam_key AND source in the doc. Both are visible. Or is there a way to hide the #+ things?

**Comment by jethrokuan** [comment]
`ROAM_KEY` is metadata to the document, and doesn't get exported, while the description list does get exported to HTML. Not sure if there's an in-built way to toggle the visibility of the global attributes.

**Comment by technovangelist** [comment]
That makes a lot of sense. Thank you
