### ISSUE TITLE
Ability to place notes into subdirectories

### ISSUE THREAD

**Issue by travispavek** [jethrokuan/org-roam#218]
### Brief Abstract
I have a problem with just dumping everything in one directory. A way to specify where a new note should go would be great.

### Long Description
I realize this goes a bit against the model but I would like to separate notes by different categories. A few examples: people, journal (daily note), and meetings. I was using 'org-roam--new-file-named' as it allowed me to prefex the name with a directory but that seems to be gone now.  It looks like a solution should be pretty straight forward but I am not familiar enough with lisp to do it.

### Proposed Implementation (if any)
I am pretty open on how this is done, possible options:
 * Templates could have a subdir option. 
 * Something where we could create our own keyboard macros that would define it
 * I am also okay with even an example in the README on how one could create their own custom functions for paths.

 ## Please check the following:
- [x] No similar feature requests

**Comment by jethrokuan** [comment]
I'll include this in #216 , where the filename specified in the template will be the relative path to the org-roam-directory

**Comment by travispavek** [comment]
That will be great thanks!  Thanks for all the work you are doing!

**Comment by jethrokuan** [comment]
It actually already works that way, without modification, so if you're eager/brave enough you can give that branch a try.

**Comment by travispavek** [comment]
So I have been trying to use the default template you have document and getting the error message "Invalid org-roam-capture-context" when selecting the template in org-capture.  Any thoughts on what might be wrong?

**Comment by travispavek** [comment]
Templating works great for my needs.  Thanks!

**Comment by bdarcus** [comment]
> I'll include this in #216 , where the filename specified in the template will be the relative path to the org-roam-directory

I'm not sure if this should be a new issue, so I'll ask here.

So how is one supposed to create a new file within org-roam within a subdirectory?

When I specify the relative path, it does not work as a I expect. Am I missing something?

**Comment by Zaeph** [comment]
> When I specify the relative path, it does not work as a I expect. Am I missing something?

It's working on my end.  Here's the template I've used:
```el
("t" "test" plain
           (function org-roam-capture--get-point)
           "%?"
           :file-name "foo/%<%Y%m%d%H%M%S>-${slug}" ; <---
           :head "#+TITLE: ${title}\n"
           :unnarrowed t)
````

However, it seems that `foo/` cannot be created by the `org-roam` capture template: it has to be created before hand.  Probably some bad interaction.

**Comment by danielkrajnik** [comment]
Could someone please explain why everything should be in one directory? I find it confusing as that's a completely new way of working for most newcomers, which doesn't seem to be documented anywhere?
