### ISSUE TITLE
org-roam-show-graph

### ISSUE THREAD

**Issue by anthrolisp** [jethrokuan/org-roam#22]
How to make the graph.svg file open in emacs and not one's default browser?

**Comment by anthrolisp** [comment]
I know see in your write-up that the image is opening in Firefox and clicking on it opens up the file in emacs. Is it possible to replicate this behavior without running EXWM as one's window manager?

**Comment by jethrokuan** [comment]
Here are the instructions for linux environments:

https://github.com/jethrokuan/org-roam/pull/12

**Comment by anthrolisp** [comment]
Does the following also go in the launch_emacs file?

`xdg-mime default roam.desktop x-scheme-handler/roam`

**Comment by jethrokuan** [comment]
You run that in the commandline
