### ISSUE TITLE
Backlinks in ox-hugo exports

### ISSUE THREAD

**Issue by jdiez17** [jethrokuan/org-roam#220]
### Brief Abstract

I use ox-hugo to export (some of) my org-roam notes to .md, and then to HTML. It would be pretty awesome to include backlinks to the end of this exported file, just like Roam does.

### Long Description

I don't know if this requires a feature to be added to org-roam, but I would still like to ask for advice here. Currently, whenever I save an org-roam file, ox-hugo exports this note as a .md file. The first step would be add some additional lines to a virtual "org text buffer" that is passed to ox-hugo, containing a list of notes that link to the note being exported. The second step, which may be significantly more challenging, would be to update (re-export) the referenced note whenever a forward link is inserted into an org-roam note.

Any ideas?

### Please check the following:
- [X] No similar feature requests

**Comment by jethrokuan** [comment]
A makeshift solution was available at https://github.com/jethrokuan/org-roam/issues/156#issuecomment-590030752, but the function to get the backlinks is now different, hopefully that helps in the meantime. It's not a thing I'll add into `org-roam`, but probably something that could go in the documentation.

**Comment by benide** [comment]
I've expanded on that a bit for some extra features, but I froze my version before the SQLite update. I plan to update sometime soon, and when I do I'll update that code as well. @jdiez17, if you haven't done something your self before then I'll put the code here.

**Comment by jdiez17** [comment]
@benide I have also held off on updating, so I would indeed be interested in your solution. Do you also have a way re-export the linked files whenever a link is added?

**Comment by benide** [comment]
Here's the extra stuff I have in there right now: https://gist.github.com/benide/982e9a88a9f52ccbbabd07e27049ed6b

Note that since org-roam has been changing fast, there might be some things that don't work for you depending on exactly where you are in the git history.

What this does is if your org file has `#+ide: backlinks` in it somewhere, it will automatically put them at the end. On line 34, the number `3` is indicating how deep into the backlinks to go, so I'm actually doing more than just one level of backlinks. Note that you can get repeats for anything larger than `1`, because this is kind of unrolling a directed graph into a tree.

Further, if `#+ide: autobib` is there, it will put `bibliography:...` at the end with whatever your `bibtex-completion-bibliography` has whenever you have any kind of `org-ref` citations in your file. The bibliography always comes after the backlinks.

This is just directly copied out of my personal config, but if you find it useful then great! :)

**Comment by benide** [comment]
Oh, and no, I don't have a way to re-export. That's a good point that I would have totally overlooked until it became obvious later on... It wouldn't be too hard to add advice to `org-roam-insert` to make that happen.

**Comment by jdiez17** [comment]
Thanks @benide. I have updated my org-roam setup, and with inspiration from your code, I have written a similar export hook that works with the new DB functions. Here it is, if someone is interested: https://gist.github.com/jdiez17/2a6d3e13d91db5b3faacb7966ce45845

**Comment by jethrokuan** [comment]
Nicely done @jdiez17 , that also works on my export setup. I've added an additional check for the file being an org-roam file, and remove the preview contents for my export:

```
(defun jdiez/org-roam--backlinks-list (file)
  (if (org-roam--org-roam-file-p file)
      (--reduce-from
       (concat acc (format "- [[file:%s][%s]]\n"
			                     (file-relative-name (car it) org-roam-directory)
			                     (org-roam--get-title-or-slug (car it))))
       "" (org-roam-sql [:select [file-from] :from file-links :where (= file-to $s1)] file))
    ""))

(defun jdiez/org-export-preprocessor (backend)
  (let ((links (jdiez/org-roam--backlinks-list (buffer-file-name))))
    (unless (string= links "")
      (save-excursion
      	(goto-char (point-max))
      	(insert (concat "\n* Backlinks\n") links)))))

(add-hook 'org-export-before-processing-hook 'jdiez/org-export-preprocessor)
```

**Comment by benide** [comment]
I've taken your update to the new database and re-included the ability to go deeper if anyone is interested in that.

```elisp
  (defun ide/org-roam--backlinks-list (file depth &optional indent-level)
    (if (and (org-roam--org-roam-file-p file) (not (eq depth 0)))
	(--reduce-from
	 (concat acc (if indent-level (make-string (* 2 indent-level) ? ) "")
		 (format " - [[file:%s][%s]]\n"
			 (file-relative-name (car it) org-roam-directory)
			 (org-roam--get-title-or-slug (car it)))
		 (ide/org-roam--backlinks-list
		  (car it) (- depth 1) (+ (if (not indent-level) 0 indent-level) 1)))
	 "" (org-roam-sql [:select [file-from] :from file-links :where (= file-to $s1)] file))
      ""))
```

I like a default of depth 3 generally, but some pages need only 1, so I handle that with the following:

```elisp
  (defun ide/org-property-values (prop)
    (if-let ((s (org-macro--find-keyword-value prop t)))
	(split-string s)))

  (defun ide/org-export-preprocessor (backend)
    (if-let ((values (ide/org-property-values "backlinks")))
	(let ((depth (string-to-number (car values))))
	    (let ((links (ide/org-roam--backlinks-list (buffer-file-name) depth)))
	      (unless (string= links "")
		(save-excursion
		  (goto-char (point-max))
		  (insert (concat "\n* Backlinks\n" links))))))))

  (add-to-list 'org-export-before-processing-hook #'ide/org-export-preprocessor))
```

So now, a page with `#+backlinks: 3` will go 3 layers deep, and `#+backlinks: 1` gives the same result that @jethrokuan should be getting.

Of course, in the actual code I'm using I still have my bibliography thing, but I stripped that here :)
