### ISSUE TITLE
Feature request: allow timestamps as file names

### ISSUE THREAD

**Issue by brabalan** [jethrokuan/org-roam#23]
I have a simple implementation of a zettelkasten using deft and org files, which seems to be the basis behing org-roam. I let deft use timestamps as file names as it makes for stable links, and I can easily edit the title of a note without breaking links. It seems that you use the title itself as file name. Could it be adapted?

**Comment by jethrokuan** [comment]
Yeah sure, I can add a function that creates time-stamped files. However, either you would need to know the relevant timestamp for `org-roam-insert`, or I would need to parse all the files to pull the title, and I think the latter is not likely to happen unless a cheap method of doing so presents itself. Would you be okay with that?

**Comment by brabalan** [comment]
The workflow I'm thinking of, which I haven't coded yet, is something like this:
- use deft, or a local directory search (using `rg` and `ivy` or `helm`) to do a full-text search when searching for a place to link
- instrument the results to insert an org link with description taken from the title

At the moment I'm doing it manually: I switch to deft, find the destination file, and link it. This works but I dislike moving away from the file I'm linking from.

**Comment by jethrokuan** [comment]
I wouldn't mind a PR the workflow you have in mind, i.e. use rg to get name of file, and then inserting the org link with title as the description.

**Comment by brabalan** [comment]
I'll try to implement it and will let you know.

**Comment by jethrokuan** [comment]
Here's something that works, if you have `counsel` and `rg`:

```
(defun org-roam-insert-action (x)
  (when (string-match "\\`\\(.*?\\):\\([0-9]+\\):\\(.*\\)\\'" x)
    (let* ((file-name (match-string-no-properties 1 x))
           (file (file-truename (expand-file-name
                                 file-name
                                 (ivy-state-directory ivy-last))))
           (id (org-roam--get-id file))
           (file-path (org-roam--get-file-path id)))
      (unless (file-exists-p file-path)
        (make-empty-file file-path))
      (insert (format "[[%s][%s]]"
                      (concat "file:" file-path)
                      (concat org-roam-zettel-indicator id)))
      (unless (eq ivy-exit 'done)
        (swiper--cleanup)
        (swiper--add-overlays (ivy--regex ivy-text))))))

(defun org-roam-rg ()
  (interactive)
  (let ((default-directory org-roam-directory)
        (counsel-ag-command "rg --with-filename --no-heading --line-number --color never %s"))
    (ivy-read (concat (car (split-string "rg")) ": ")
              #'counsel-ag-function
              :initial-input ""
              :dynamic-collection t
              :action #'org-roam-insert-action
              :require-match t
              :caller 'org-roam-rg)))
```

**Comment by jethrokuan** [comment]
I've added the functionality to use search and insert via title in #41 , as well as to create a new file using `org-roam-new-file`. You can use this functionality by setting `org-roam-link-representation` to `'title`.

The `rg` workflow is a bit more involved and I'm a bit hesitant to add it into the main package atm, but you're free to adapt the above in your own emacs config.

**Comment by brabalan** [comment]
Thanks a lot for all this. I'm trying to play with the `org-roam-insert-action`, but it seems to need to be adapted for the new code. I'm going to try to do it and post it here.

**Comment by jethrokuan** [comment]
@brabalan I fixed it for you:

```
(defun org-roam-insert-action (x)
  (when (string-match "\\`\\(.*?\\):\\([0-9]+\\):\\(.*\\)\\'" x)
    (let* ((file-name (match-string-no-properties 1 x))
           (file (file-truename (expand-file-name
                                 file-name
                                 (ivy-state-directory ivy-last))))
           (relative-file (file-relative-name file (file-truename org-roam-directory))))
      (unless (file-exists-p file)
        (make-empty-file file))
      (insert (format "[[%s][%s]]"
                      (concat "file:" relative-file)
                      (format org-roam-link-title-format (org-roam--get-title-or-id file))))
      (unless (eq ivy-exit 'done)
        (swiper--cleanup)
        (swiper--add-overlays (ivy--regex ivy-text))))))

(defun org-roam-rg ()
  (interactive)
  (let ((default-directory org-roam-directory)
        (counsel-ag-command "rg --with-filename --no-heading --line-number --color never %s"))
    (ivy-read (concat (car (split-string "rg")) ": ")
              #'counsel-ag-function
              :initial-input ""
              :dynamic-collection t
              :action #'org-roam-insert-action
              :require-match t
              :caller 'org-roam-rg)))
```

**Comment by brabalan** [comment]
Thanks, I was about to post this! I have a quick additional question: do you have a function that can set the title of the newly created file? Something similar to https://github.com/jrblevin/deft/blob/master/deft.el#L1426 that would set the title when creating the file.

**Comment by jethrokuan** [comment]
I've been using this from my own config: https://github.com/jethrokuan/.emacs.d/blob/600f2419b962be763f24be42167c5a6ca3f36be7/init.el#L1265 with a dir-local specification here: https://github.com/jethrokuan/braindump/blob/b05dcbae03db95d494f7f23a9dfc46da834905a2/org/.dir-locals.el#L4

But I do think that the title insertion could be moved into org-roam.

**Comment by jethrokuan** [comment]
@brabalan that functionality is now in master, let me know if it works for you.

**Comment by brabalan** [comment]
It works great. I've found a bug, though: at https://github.com/jethrokuan/org-roam/blob/master/org-roam.el#L261 the closing parenthesis of the `if` is too early, so the id is always requested. I changed it to:
```emacs-lisp
    (when (not id)
      (if org-roam-timestamped-files
          (setq id (org-roam--get-new-id))
        (read-string "Enter new file id: " (org-roam--title-to-id title))))
```

**Comment by jethrokuan** [comment]
Thanks for the catch. The code has been greatly simplified and improved in the `develop` branch, I think this bug in particular has also disappeared.

**Comment by brabalan** [comment]
Great, I'll switch the the `develop` branch then.

**Comment by tpeacock19** [comment]
with this change, may be useful to remove the `(deft-use-filename-as-title t)` option from the Deft portion of the Org Roam Documentation. By default, deft gets its title from the `#+TITLE:` string in org files.

**Comment by jethrokuan** [comment]
> By default, deft gets its title from the #+TITLE: string in org files.

Actually by default, `the title is taken to be the first non-empty line of the FILE.`, which happens to be `#+TITLE` for the most part. This function patches it:

```
(defun deft-parse-title (file contents)
    (with-temp-buffer
      (insert contents)
      (org-roam--get-title-or-slug (file-truename file))))
```

**Comment by tpeacock19** [comment]
I moreso meant, for example, in this GIF in the documentation. 

[https://org-roam.readthedocs.io/en/latest/images/org-roam-find-file.gif](url)

You can see the titles of the notes in the Deft window showing '20200215...'. However, if you set `(deft-use-filename-as-title nil)` it will show the parsed title in the Deft view per this function in deft.el:

```
(defcustom deft-strip-title-regexp
  (concat "\\(?:"
          "^%+" ; line beg with %
          "\\|^#\\+TITLE: *" ; org-mode title
          "\\|^[#* ]+" ; line beg with #, * and/or space
          "\\|-\\*-[[:alpha:]]+-\\*-" ; -*- .. -*- lines
          "\\|^Title:[\t ]*" ; MultiMarkdown metadata
          "\\|#+" ; line with just # chars
          "$\\)")
  "Regular expression to remove from file titles.
Presently, it removes leading LaTeX comment delimiters, leading
and trailing hash marks from Markdown ATX headings, leading
astersisks from Org Mode headings, and Emacs mode lines of the
form -*-mode-*-."
  :type 'regexp
  :safe 'stringp
  :group 'deft)
```

Its just a cosmetic thing but I thought necessary for myself. Awesome project btw, I wish I could help but am just early on in my elisp/programming journey.

**Comment by jethrokuan** [comment]
Looking at the docstring of `deft-parse-title`, I see:

```
  "Parse the given FILE and CONTENTS and determine the title.
If `deft-use-filename-as-title' is nil, the title is taken to
be the first non-empty line of the FILE.  Else the base name of the FILE is
used as title."
```

I set `(setq deft-use-filename-as-title nil)`, and see this, because my first non-empty line is not the `#+TITLE:` attribute:

![image](https://user-images.githubusercontent.com/1667473/74593044-86fd8480-5062-11ea-8ecb-d2b65639d8f6.png)

but after patching as above, it's correct:
 
![image](https://user-images.githubusercontent.com/1667473/74593130-11de7f00-5063-11ea-977d-444c409ca401.png)

**Comment by tpeacock19** [comment]
Ahh I understand what you meant now. thanks for your patience.

**Comment by jethrokuan** [comment]
Thanks for pointing it out, I'll edit the documentation accordingly sometime tomorrow!
