### ISSUE TITLE
Can't necessarily follow relative non-backlinks from the *org-roam* buffer

### ISSUE THREAD

**Issue by shader** [jethrokuan/org-roam#231]
### Description
If a backlink's context contains other links to roam files (which are usually relative), but the org-roam buffer was initially opened from _outside_ `org-roam-dir`, the links open new files.

The default-directory should either be `org-roam-dir`, or for absolute correctness each link should be opened relative to the file it came from, to support multiple directories.

#### Steps to Reproduce
1. Load Emacs
2. Run `org-roam` (C-c n l) from outside `org-roam-dir` (e.g. `*scratch*`)
3. Open a roam file with backlinks such that the backlinks have more links in their context
4. Click on a link in the *org-roam* buffer that isn't itself one of the backlinks

#### Expected Results
Follows link

#### Actual Results
Opens new, empty buffer in `default-directory`

### Versions
- Emacs: v26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/b74cc143779bc67e82a9f6f2059ad4d4fdef02db

**Comment by jethrokuan** [comment]
I think #228 might have fixed this, could you pull down master and check?

**Comment by shader** [comment]
Yes, I think it seems to be fixed now.
