### ISSUE TITLE
Creating new today file in org-roam clears previous entry

### ISSUE THREAD

**Issue by aswinmohanme** [jethrokuan/org-roam#234]
### Description
I am using Spacemacs and have successfully integrated org-roam, (it's a fantastic package :), I can create a new today entry with `SPC a r t`. If it's the first time I'm running the command It shows the empty file with the date as title. If the command is run again then rather than showing the older file for editing a new fresh file is created.

#### Steps to Reproduce
1. Open Spacemacs
2. Create new today file with `SPC a r t`
3. Make changes and save
4. Open Spacemacs again and run the today command

#### Expected Results
- The today file should be opened for editing with the previous content intact

#### Actual Results
- A new today file is created

### Versions
- Running from the master branch as said on the docs for spacemacs

**Comment by jethrokuan** [comment]
Hopefully #235 fixes this for you!
