### ISSUE TITLE
Regression in user experience when inserting an org-roam link when org-roam-capture-templates is set.

### ISSUE THREAD

**Issue by jdiez17** [jethrokuan/org-roam#239]
#### Steps to Reproduce

1. Set `org-roam-capture-templates` to the following (for example): 

```      (org-roam-capture-templates
        '(("d" "default" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "${slug}"
           :head "#+SETUPFILE:./hugo_setup.org
#+HUGO_SECTION: zettels
#+HUGO_SLUG: ${slug}
#+TITLE: ${title}\n"
           :unnarrowed t)
          ("p" "private" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "private-${slug}"
           :head "#+TITLE: ${title}\n")))
```
2. Open any existing org-roam note.
3. Insert a link to a **new** note, for example `M-x org-roam-insert "completely new page" RET`

#### Expected Results
1. The new org-roam note is created as a buffer in the background, and does not disrupt the note editing workflow.

#### Actual Results
1. After typing the name of the new page, org prompts the user for the template to use.
2. After the template is selected, an org-capture buffer is opened. The user can accept the capture and save with `C-c C-c`. 
3. After dismissing the capture dialog, the point is back to the file in which the link was being inserted.

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/b1e2209dfc0b06c6a4596c0e2c09744b55a0a272

### Commentary
I'm not sure what should be the correct behaviour here, since it is not obvious which capture template should be used for the new page.

**Comment by jethrokuan** [comment]
If you don't wish for your note-taking flow to be disrupted (i.e. you don't want to enter new stuff into the new note), you may add `:immediate-finish t` to the capture template.

**Comment by jtoloe** [comment]
Perhaps there should be an option for `org-roam-insert` to always use the default template?

**Comment by jethrokuan** [comment]
@jtoloe the default template is always used if it's the only template.
