### ISSUE TITLE
Help wanted; org-roam does not load

### ISSUE THREAD

**Issue by poulpoulsen** [jethrokuan/org-roam#243]
hello,
i have a problem with this package, because it wont load during startup.
if load with M-x load-library it works.
there is no error message, just nothing.
how can i check whats going on?
i use emacs 26.3 on linux kubuntu 18.04.

here is the code:
(add-to-list 'load-path "~/.emacs.d/lisp/org-roam-mode")
(require 'org-roam)
;;(define-key 'org-roam-mode-map (kbd "C-c n l") #'org-roam)
;;(define-key 'org-roam-mode-map (kbd "C-c n f") #'org-roam-find-file)
;;(define-key 'org-roam-mode-map (kbd "C-c n b") #'org-roam-switch-to-buffer)
;;(define-key 'org-roam-mode-map (kbd "C-c n g") #'org-roam-switch-to-buffer)
;;(define-key 'org-mode-map (kbd "C-c n i") #'org-roam-insert)
(setq org-roam-directory "~/org-rep/org-roam")
(setq org-roam-encrypt-files t)
(org-roam-mode +1)

Regards
Poul

**Comment by jethrokuan** [comment]
your load-path looks wrongly set, where did you clone it into?

**Comment by poulpoulsen** [comment]
i cloned it in ~/.emacs.d/lisp/org-roam-mode.

**Comment by jethrokuan** [comment]
you're supposed to point it to `~/.emacs.d/lisp`.

**Comment by poulpoulsen** [comment]
unfortunately no difference.
i think, that it not working, because as far as i read, emacs looks only in the directories, that are in load-path. no recursive load.
load-library doesnt work also, only if i add ~/.emacs.d/lisp/org-roam.
so there might be another problem?

**Comment by jethrokuan** [comment]
Maybe wait for the MELPA release #171 ? The setup is non-trivial, but MELPA will make it much easier.

**Comment by poulpoulsen** [comment]
ok, i will wait and after successfully install i come back again here.

**Comment by poulpoulsen** [comment]
i find out, that a missing letter some lines below my config produces the error. I dont know why, but now org-roam starts.
