### ISSUE TITLE
disable spell-checking on the roam buffer?

### ISSUE THREAD

**Issue by bdarcus** [jethrokuan/org-roam#249]
Since the buffer is intended to be a read-only view, could you turn off spell-checking on it?

**Comment by jethrokuan** [comment]
I'll add a hook variable that runs during the buffer refresh. You may add `(flyspell-mode -1)` there. I imagine some people may still want things spellchecked, so they can be corrected later.

**Comment by jethrokuan** [comment]
I just realised you can already do this:

(add-hook 'org-roam-backlinks-mode-hook (lambda () (flyspell-mode -1)))`

**Comment by bdarcus** [comment]
I think something changed that makes this solution no longer work.  If correct, how would I adapt?

**Comment by jethrokuan** [comment]
this should still work.
