### ISSUE TITLE
Option to allow spaces in file slug

### ISSUE THREAD

**Issue by gambhiro** [jethrokuan/org-roam#256]
### Brief Abstract

A boolean user variable to allow spaces in the file slugs.

### Long Description

I recognize that spaces in files can mess up shell operations, and I like my dashes and underscores too.

But looking at the file list is a kind of user interface too, and I can read the titles better with spaces.

### Proposed Implementation (if any)

In my init files I added a small change to `org-roam--title-to-slug`, after the sanitizing steps, adding a final replace from underscores back to spaces.

This could be controlled with a boolean config variable if other people wish to use it that way.

```
(pairs `(("[^[:alnum:][:digit:]]" . "_")  ;; convert anything not alphanumeric
                          ("__*" . "_")  ;; remove sequential underscores
                          ("^_" . "")  ;; remove starting underscore
                          ("_$" . "") ;; remove ending underscore
                          ("_" . " ") ;; underscores to spaces
                          ))
```

### Please check the following:
- [x ] No similar feature requests

**Comment by jethrokuan** [comment]
I'd much rather add an option to replace the whole `title-to-slug` function. A proliferation of small customizations like this would be bad for maintainability.

**Comment by gambhiro** [comment]
Fair enough, that's what I ended up doing as well, adding a `(defun org-roam--title-to-slug (title) ...)` in the `(use-package org-roam :config)` section.
