### ISSUE TITLE
Supplying a title to `org-roam-find-file`

### ISSUE THREAD

**Issue by jtoloe** [jethrokuan/org-roam#258]
### Brief Abstract
Modify `org-roam-find-file` to take an argument that will be used in `completing-read` to populate the list of completions.

### Long Description
I use org-roam together with org-noter and zotxt to take notes of papers that I read. I add a org-roam note with the title of a paper that I have stored in zotero. I can get the title of the currently selected item in zotero using zotxt but I found no way of having org-roam insert a note using this title. To do it I modified `org-roam-find-file` as shown below.

If this can already be accomplished in a different way please let me know.

### Proposed Implementation (if any)
A modification of `org-roam-find-file` to take the optional string argument `suggestion` that will populate the completion list with the string.

```
diff --git a/org-roam.el b/org-roam.el
index 19810f4..ddb6943 100644
--- a/org-roam.el
+++ b/org-roam.el
@@ -783,11 +783,11 @@ point moves some characters forward. This is added as a hook to
                       file-path) res))))
     res))
 
-(defun org-roam-find-file ()
+(defun org-roam-find-file (&optional suggestion)
   "Find and open an org-roam file."
   (interactive)
   (let* ((completions (org-roam--get-title-path-completions))
-         (title (completing-read "File: " completions))
+         (title (completing-read "File: " completions nil nil (if suggestion suggestion nil)))
          (file-path (cdr (assoc title completions))))
     (if file-path
         (find-file file-path)
```

### Please check the following:
- [ ] No similar feature requests

**Comment by jethrokuan** [comment]
done!

**Comment by jtoloe** [comment]
Great, thanks!
