### ISSUE TITLE
Link within file

### ISSUE THREAD

**Issue by wannli** [jethrokuan/org-roam#260]
Great tool! Many thanks to @jethrokuan for porting some of the Roam functionality to Org!

The main use case presented here is a single link per file. Would it be possible to link to a heading within a file and treat what’s under that heading as a stand-alone “note” on par with all other notes?

**Comment by jethrokuan** [comment]
> Would it be possible to link to a heading within a file and treat what’s under that heading as a stand-alone “note” on par with all other notes?

No, this is a workflow that's difficult to support.

**Comment by wannli** [comment]
Many thanks!
