### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by elliottw** [jethrokuan/org-roam#271]
### Description
attempt to write a readonly database error when inserting new file (completely new, not referring to pre-existing), and C-c C-c the newly populated capture buffer
#### Steps to Reproduce

Saving bookmarks to file /Users/elliott/.emacs.d/.cache/bookmarks...
Wrote /Users/elliott/.emacs.d/.cache/bookmarks
Saving bookmarks to file /Users/elliott/.emacs.d/.cache/bookmarks...done
Saving file /Users/elliott/Dropbox/slipbox/20200222180100_imsi_hacking.org...
Wrote /Users/elliott/Dropbox/slipbox/20200222180100_imsi_hacking.org
Database access error: "attempt to write a readonly database"

did this with org-roam-insert
capture buffer pops up
C-c C-c

#### Expected Results
new file is saved, capture buffer closes, return focus to original org file
#### Actual Results
capture buffer does not close, i hit :w instead, everything works as should

### Versions
- Emacs (`C-h v emacs-version`): v 26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
This happens to me when the db is not synced over over Dropbox nicely.

I run EXWM, so when I poweroff my desktop, emacs quits, unlocking the DB and making it writable. But Dropbox hasn't had the chance to sync the unlocked db, so when I access it on laptop I'm on the locked (read-only) DB.

I'm not sure if there's a good way to fix this, other than being careful about the syncing. You can close all connections `(org-roam--db-close-all)`, delete the database and rebuild it from scratch.

**Comment by jethrokuan** [comment]
#335 makes it a lot easier to work around this issue.

Delete the org-roam db, and run `M-x org-roam-build-cache`.
