### ISSUE TITLE
creating new files on mac uses a dash between date and name, on linux, uses underscore

### ISSUE THREAD

**Issue by elliottw** [jethrokuan/org-roam#272]
### Description
creating new files on mac uses a dash between date and name, on linux, uses underscore
#### Steps to Reproduce
on macs:
org-roam-insert
foo bar
produces something like 202003121212-foo_bar

on linux:
produces something like 202003121212_foo_bar

### Versions
- Emacs (`C-h v emacs-version`): v26.3 on macos and linux
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment]
No reason for this, could be different versions of org-roam loaded in your machines.
