### ISSUE TITLE
Descriptive Dates in Title like Org Journal

### ISSUE THREAD

**Issue by aswinmohanme** [jethrokuan/org-roam#277]
### Brief Abstract
When creating new date entry with `org-roam-today` the title is populated as `#+TITLE: 2020-03-11
`. 

Creating a new entry with `org-journal` the title is `#+TITLE: Wednesday, 11 March 2020` . Is there any way to enable title to be in long form as it would make searching easier.

**Comment by jethrokuan** [comment]
I personally don't use `org-roam-today`, and choose to use `org-journal`. Those functions are there mainly for historic reasons, and for a simple implementation of that org-journal functionality.

**Comment by aswinmohanme** [comment]
I have tried with org-journal and it seems kind of glitchy. I can't use org-roam-date for a dated entry too. It would be really nice to have this feature integrated with org-roam.

I know how much you get peddled with feature requests and how much effort you are putting into this.
