### ISSUE TITLE
Explicitly warn when org-mode is too old

### ISSUE THREAD

**Issue by alanz** [jethrokuan/org-roam#278]
### Description

This may not be a real problem once things are installed via MELPA, but when loading org-roam via a checkout of the project, it does not warn if running against a version of org-mode that is too old.

And if org-mode is 9.1, the links get rendered as plain text, instead of links in the org-roam buffers.  Oddly enough this only started happening in the last few days, no idea what commit it was.  But upgrading to current org-mode via the package manager sorted it out.

**Comment by jethrokuan** [comment]
It was this commit: https://github.com/jethrokuan/org-roam/commit/63e0558d969ff03a234dee71caad1ef0ad09053c

I removed the explicit check for org version 9.2 and above, and required 9.3 minimum. Hopefully the MELPA release goes through soon

**Comment by jethrokuan** [comment]
org-roam is now available on MELPA, so this should go away
