### ISSUE TITLE
file-missing "Cannot open load file" "No such file or directory" "org-roam"

### ISSUE THREAD

**Issue by Xunius** [jethrokuan/org-roam#279]
### Description
I'm having this error message when launching `emacs --debug-init`:

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "org-roam")
  require(org-roam)
  eval-buffer(#<buffer  *load*> nil "/home/guangzhi/.emacs.d/init.el" nil t)  ; Reading at buffer position 527
  load-with-code-conversion("/home/guangzhi/.emacs.d/init.el" "/home/guangzhi/.emacs.d/init.el" t t)
  load("/home/guangzhi/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1df6a1>)()
  command-line()
  normal-top-level()
```

#### Steps to Reproduce

My installation process:

1. `git clone https://github.com/jethrokuan/org-roam/ ~/.emacs.d/elisp/org-roam`
2. Put these to my `init.el`:

```
(add-to-list 'load-path "/home/guangzhi/.emacs.d/elisp")
(require 'org-roam)
(define-key 'org-roam-mode-map (kbd "C-c n l") #'org-roam)
(define-key 'org-roam-mode-map (kbd "C-c n f") #'org-roam-find-file)
(define-key 'org-roam-mode-map (kbd "C-c n b") #'org-roam-switch-to-buffer)
(define-key 'org-roam-mode-map (kbd "C-c n g") #'org-roam-switch-to-buffer)
(define-key 'org-mode-map (kbd "C-c n i") #'org-roam-insert)
(org-roam-mode +1)
```

3. Run `emacs --debug-init`

### Versions
- Emacs GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)
- Org-roam commit: Is this it?
```
commit 0cab668d9e68651af3c569cc24e31ce1a3d9be06 (HEAD -> master, origin/master, origin/HEAD)
Author: Jethro Kuan <jethrokuan95@gmail.com>
Date:   Wed Mar 11 15:41:18 2020 +0800

    (bugfix): propagate org-roam-directory to temp buffers (#275)
```

**Comment by jethrokuan** [comment]
can you try changing the load-path line to:

```
(add-to-list 'load-path "/home/guangzhi/.emacs.d/elisp/")
```

**Comment by Xunius** [comment]
@jethrokuan It doesn't help. I also tried `"/home/guangzhi/.emacs.d/elisp/org-roam"` and it shows this one instead: `File is missing: Cannot open load file, No such file or directory, emacsql`.

I then tried `emacs -Q` into scratch, and evaluate
```
(add-to-list 'load-path "/home/guangzhi/.emacs.d/elisp/")
```
Then `(require 'org-roam)`, it still gives me the same No such file or directory "org-roam" error.

**Comment by jethrokuan** [comment]
Ah okay, looks like the vanilla installation procedure is a bit flawed.

you'lll need to have:

```
(add-to-list 'load-path "/home/guangzhi/.emacs.d/elisp/org-roam")
```

and also `M-x package-install` the following packages: `f`, `s`, `emacsql`, `emacsql-sqlite`, `dash`, and also have an org-version >9.3.

This is all handled by MELPA during a package install. So I'm hoping the MELPA release comes through soon. #171

**Comment by Xunius** [comment]
@jethrokuan Thanks. Can't wait to see it in MELPA.
