### ISSUE TITLE
org-roam-build-cache: Invalid function: org-roam--with-temp-buffer

### ISSUE THREAD

**Issue by fkgruber** [jethrokuan/org-roam#281]
### Description
I'm getting error:
org-roam--db-ensure-built: [Org-roam] your cache isn’t built yet! Please run org-roam-build-cache
org-roam-build-cache: Invalid function: org-roam--with-temp-buffer

#### Steps to Reproduce
I install it with
      :hook 
      (after-init . org-roam-mode)
      :straight (:host github :repo "jethrokuan/org-roam" :branch "develop")
      :custom
      (org-roam-directory "/path/to/org-files/")
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n b" . org-roam-switch-to-buffer)
               ("C-c n g" . org-roam-show-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))))
I updated to latest orgmode

**Comment by jethrokuan** [comment]
Please switch to the master branch (i.e. remove :branch "develop").

**Comment by fkgruber** [comment]
thanks,
I tried that but I'm still getting
org-roam-build-cache: Invalid function: org-roam--with-temp-buffer

**Comment by jethrokuan** [comment]
That macro is defined in `org-roam.el`: https://github.com/jethrokuan/org-roam/blob/0cab668d9e68651af3c569cc24e31ce1a3d9be06/org-roam.el#L439

so you might need to re byte-compile everything, or delete some old stuff.

**Comment by fkgruber** [comment]
thanks! that worked
