### ISSUE TITLE
possible bug? capture template change hyphen in filename into underscore.

### ISSUE THREAD

**Issue by poulpoulsen** [jethrokuan/org-roam#287]
hello,
if i use the default template
("d" "default" plain (function org-roam--capture-get-point)
     "%?"
     :file-name "%<%Y%m%d%H%M%S>-${slug}"
     :head "#+TITLE: ${title}\n"
     :unnarrowed t)

the filename is changed, if it contains a hyphen.
Then it is changed into an underscore.
Why?
Is this intended? or is it forbidden to use hyphens?

Regards
Poul

**Comment by poulpoulsen** [comment]
I double check.
it seems, that the problem is inside $(slug). What does it mean?

Regards
Poul

**Comment by jethrokuan** [comment]
slug is a file-name suitable version of the title (see `org-roam--title-to-slug`). If you don't like the default, you may override the function.

**Comment by myshevchuk** [comment]
It's a feature!
