### ISSUE TITLE
Error in org-agenda when org-roam is enable : org-agenda-get-timestamps: Symbol’s value as variable is void: org-priority-highest

### ISSUE THREAD

**Issue by alvarmaciel** [jethrokuan/org-roam#288]
### Description
Hi, I'm trying to use org-roam but I have an issue whit org-agenda. When I have org-roam enabled and run org-agenda i have this message
org-agenda-get-timestamps: Symbol’s value as variable is void: org-priority-highest
and doesn't load the agenda view properly 

###  Org-roam setup
(use-package org-roam
      :hook 
      (after-init . org-roam-mode)
      :straight (:host github :repo "jethrokuan/org-roam" :branch "develop")
      :custom
      (org-roam-directory "~/Dropbox/org/pensadero/org/")
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n b" . org-roam-switch-to-buffer)
               ("C-c n g" . org-roam-show-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))))

Emacs version GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2019-07-11

Org mode version 9.3.6 (release_9.3.6-412-ge18415

**Comment by jethrokuan** [comment]
```
org-agenda-get-timestamps: Symbol’s value as variable is void: org-priority-highest
```

I don't have `org-priority-highest` anywhere in my Org-mode installation, nor is it used in Org-roam. Perhaps it's something in your personal org-agenda config?

**Comment by alvarmaciel** [comment]
Thanks! I'm checking, I don't have that in my setup, I find a bug that can be related to mixed installation of org.
Thanks!
