### ISSUE TITLE
Suggestions to `org-roam-capture-templates`

### ISSUE THREAD

**Issue by myshevchuk** [jethrokuan/org-roam#298]
#### Brief Abstract
Below are several suggestions related to `org-roam-capture-templates`.

#### Long Description
1. Hide `:target` in `org-roam-capture-templates` from the user 
Since `(function org-roam--capture-get-point)` is the only valid target for org-capture, it may be desirable to hard-code it and hide from the user.
2. Hide `:type` from the user
The above applies here.
3.  Ensure `"%?"` is present in the template string
There is a bug in the original org-capture, more specifically in`org-capture-place-plain-text`:
When `:unnarrowed` is set to `t` AND `"%?"` is missing from the template string, the capture process is interrupted and the following error is thrown:
    > condition-case: Capture template ‘%s’: Invalid search bound (wrong side of point)

    Since in org-roam both `:unnarrowed t` and the plain type are present by default, it may be         desirable to ensure the user doesn't catch the error if they accidentally or intentionally remove `"%?"` from the template string.

### Proposed Implementation (if any)
1. & 2. in `org-roam-capture`
```
  (let* ((type 'plain)
        (target '(function org-roam--capture-get-point))
        (org-capture-templates (--map (--> it
                                           (-insert-at 2 type it)
                                           (-insert-at 3 target it))
                                      org-roam-capture-templates))
        file-path)
```
3. in `org-roam--capture-get-point`
```
      (let* ((head (org-roam--fill-template (or (org-capture-get :head)
                                            org-roam--capture-header-default)
                                        org-roam--capture-info))
         (template (org-capture-get :template))
         (full-template (concat head template)))
    (org-capture-put :template
                     (if (s-contains-p "%?" full-template)
                         full-template
                       (concat "%?" full-template))))
```
### Please check the following:
- [ x] No similar feature requests

**Comment by jethrokuan** [comment]
1: I think it may be desirable to keep the structure of the original org capture template definitions. I know it's not great, but at least it's familiar. Things like DOCT tries to fix it.  

2: the type `plain` is only compulsory when the header template is injected. Other types like `entry` should be allowed.

3 is fine with me.

**Comment by myshevchuk** [comment]
Ok. 

Regarding the `plain` type, the header template is inserted anyway, either a user one or the default one, so the `plain` type is actually enforced currently, shall this be changed?
```
  (org-capture-put :template
                   (concat
                    (org-roam--fill-template (or (org-capture-get :head)
                                                 org-roam--capture-header-default)
                                             org-roam--capture-info)
                    (org-capture-get :template))
                   :type 'plain)
```

to something like

```
if :header 
      then 
              concat header template
              force :type 'plain
      else
             template
```
But what to do with org-roam--capture-header-default?

**Comment by jethrokuan** [comment]
The issue of requiring plain is not when `:header` is present, but when `:header` is prepended. It should only be prepended on a new file. #302 fixes the bug earlier, so that's fine now.

**Comment by teesloane** [comment]
Not sure if I'm piling on with an unrelated issue - I'm running into the error 
```
org-capture: Capture template ‘d’: Invalid search bound (wrong side of point)
```
When using a capture template such as this:
```elisp
  (setq org-roam-capture-templates
        '(("p" "project" entry (function org-roam--capture-get-point)
           ;; "r Entry item!"
           (file "~/.doom.d/templates/org-roam-project.org")
           :file-name "${slug}"
           :head "#+TITLE: ${title}\n#+STATUS: active \n#+FILE_UNDER: project \n"
           :unnarrowed t)
          ("r" "research" entry (function org-roam--capture-get-point)
           ;; "r Entry item!"
           (file "~/.doom.d/templates/org-roam-research.org")
           :file-name "${slug}"
           :head "#+TITLE: ${title}\n#+STATUS: active \n#+FILE_UNDER: research \n"
           :unnarrowed t)
          ("d" "default" plain (function org-roam--capture-get-point)
              "%?"
              :file-name "${slug}"
              :head "#+TITLE: ${title}\n"
              :unnarrowed t)))
```

Funny enough, when I try and create a `project` or `research` file using `Org-Roam-Insert`, it fails, but when going to create a new file as a `default` template with `Org-Roam-Find` , I see my first capture attempt waiting around in limbo. Not really a big deal, but wondering if the process for using capture has changed?


<img width="318" alt="Screen Shot 2020-03-20 at 10 09 34 AM" src="https://user-images.githubusercontent.com/12987958/77171997-a3db0c80-6a93-11ea-9fcc-712474fac2d9.png">

**Comment by jethrokuan** [comment]
An upstream bug in `org-capture` results in the error you see if `:unnarrowed t` is specified, and the template string does not contain a "%?".

However, from the error message, it seems that the `default` capture template with key `d` is the one failing. But you followed up with:

> Funny enough, when I try and create a project or research file using Org-Roam-Insert, it fails, but when going to create a new file as a default template with Org-Roam-Find , I see my first capture attempt waiting around in limbo. 

So I'm a bit confused as to which template is failing. Could you try adding `%?` to all your templates and see if you're still seeing this issue?

**Comment by myshevchuk** [comment]
Don't forget to pull the latest version of org-roam and restart emacs to get all function definitions updated as well as evaluating your `setq org-roam-capture-templates`. To me the issue seems to hide somewhere here.

**Comment by teesloane** [comment]
Ah, got it fixed. Turns out that my org template just needed to have the `%?` value in it. So after making it like so:

```
* Meta
:INFO:
:date_completed: ?
:date_started: ?
:file_under: ?
:intent: ?
:links: ?
:related: ?
:slug: ?
:state: ?
:END:
* Resources
* Tasks
* Notes

%?
```
I got it working. Thanks for weighing in.

**Comment by progfolio** [comment]
> An upstream bug in org-capture results in the error you see if :unnarrowed t is specified, and the template string does not contain a "%?".

Has this bug been reported upstream? A quick search for "unnarrowed" didn't turn up anything that looked relevant to this bug:
https://lists.gnu.org/archive/cgi-bin/namazu.cgi?query=unnarrowed&submit=Search%21&idxname=emacs-orgmode&max=20&result=normal&sort=date%3Alate

**Comment by progfolio** [comment]
I'm actually unable to reproduce this bug on my system with vanilla org-capture-templates:
```
(let ((org-capture-templates '(("b" "plain template bug?"
                                plain
                                (file "/tmp/capture-bug-test.org")
                                nil
                                :unnarrowed t))))
  (org-capture nil "b"))
```

**Comment by myshevchuk** [comment]
Empty string is not `nil`. Try it with (let ((org-capture-templates '(("b" "plain template bug?"
                                plain
                                (file "/tmp/capture-bug-test.org")
                               ""
                                :unnarrowed t))))
  (org-capture nil "b"))

**Comment by progfolio** [comment]
@myshevchuk : apologies, I should have added to that test that I did try it with both the empty string and nil. Both work fine for me.

**Comment by myshevchuk** [comment]
Yes, I cannot reproduce it either. This, however, produces the error:

``` elisp
(setq org-roam-capture-templates '(("b" "plain template bug?"
                                plain
                                (function org-roam-capture--get-point)
                               ""
                                :unnarrowed t)))
```
I remember to have traced the source of the error to line 1405 in `org-capture.el`
``` elisp
in function `org-capture-place-plain-text`:
...
	(when (or (search-backward "%?" beg t)
		  (search-forward "%?" end t))
	  (replace-match ""))
```
Putting `(message "message")` just before `when` would still output "message", but not inside `when` nor after it - those searches failed with an error. So I erroneously concluded it was a bug in `org-capture`.

**Comment by myshevchuk** [comment]
It must be a bug in `org-roam-capture--get-point`

**Comment by progfolio** [comment]
Perhaps not! I'm able to reproduce in vanilla org-capture now.
`nil` and the empty string do not error, but a string without an explicit `%?` does.

```emacs-lisp
;;throws the error in `org-place-plain-text` during (search-forward "%?" end t)
(let ((org-capture-templates '(("b" "bug test" plain (file "/tmp/buggy.org")
                               "FAIL" :unnarrowed t))))
  (org-capture nil "b"))

;;does not throw error
(let ((org-capture-templates '(("b" "bug test" plain (file "/tmp/buggy.org")
                               "PASS%?" :unnarrowed t))))
  (org-capture nil "b"))
```

**Comment by progfolio** [comment]
I'll report upstream and see what they have to say.

**Comment by myshevchuk** [comment]
Maybe it is a bug in Emacs itself? Because 
``` elisp
Signature
(search-forward STRING &optional BOUND NOERROR COUNT)
```
>Optional third argument, if t, means if fail just return nil (no error).
  If not nil and not t, move to limit of search and return nil.

So `(search-backward "%?" beg t)` should not produce an error...

**Comment by progfolio** [comment]
Yes, I noted that the `NOERROR` flag is non-nil in both of those calls. Not sure, to be honest. Org dev team will likely be able to kick this upstream if needed.

**Comment by myshevchuk** [comment]
These output the message string:
``` elisp
        (message "I'm here")
	(when (or (search-backward "%?" beg t)
		  (search-forward "%?" end t))
	  (replace-match ""))

	(when (or (and (message "I'm here") (search-backward "%?" beg t))
		  (search-forward "%?" end t))
	  (replace-match ""))

	(when (or (search-backward "%?" beg t)
		  (and (message "I'm here") (search-forward "%?" end t)))
	  (replace-match ""))

```

This does not:
``` elisp
	(when (or (search-backward "%?" beg t)
		       (search-forward "%?" end t))
		  (message "I'm here")
	  (replace-match ""))
```

It shouldn't output the message of course because both searches should result in `nil`, but it should not produce an error either, which is then caught back in `org-capture`, line 679:
``` elisp
	condition-case error
	    (org-capture-place-template
	     (eq (car (org-capture-get :target)) 'function))
```

**Comment by myshevchuk** [comment]
@progfolio Maybe this will help them to trace the error.

**Comment by progfolio** [comment]
Yes. It seems it's `search-forward` that throws. That's a native C function, so I haven't looked at it's source just yet.

This may be of relevance w re: to replacing text that exceeds the bounds of the search, but I'm still puzzled:
https://lists.gnu.org/archive/html/help-gnu-emacs/2009-07/msg00050.html

**Comment by myshevchuk** [comment]
Maybe it's `condition-case` that catches. My understanding of Emacs C functions equals to zero, but I can imagine that there is an error stack or whatever and `search-forward` pushes to that stack, does not fail and returns nil. `condition-case`, however, still reads from that stack and throws the error.

**Comment by progfolio** [comment]
Reported upstream: https://lists.gnu.org/archive/html/emacs-orgmode/2020-05/msg00095.html

**Comment by progfolio** [comment]
Fixed upstream as of https://code.orgmode.org/bzg/org-mode/commit/09086b7e75a4ccb27f141d2cd495c253f1b6b025

Just tested on my system and it seems to work fine.
