### ISSUE TITLE
Aborting a capture should not leave an empty file

### ISSUE THREAD

**Issue by khinsen** [jethrokuan/org-roam#310]
### Brief Abstract

Being a bad typist, I often end up creating new notes by mistake. I then type `C-c C-k` in the capture buffer to abort. However, this still creates an empty file for that note, and does a `find-file` for it. I think it should delete the file instead.

**Comment by myshevchuk** [comment]
This is the way org-capture works. As a temporary solution for your case you might want to consider setting `:no-save t` in `org-roam-capture-templates`, e.g.
```
(setq org-roam-capture-templates 
          '(("t" "test" entry (function org-roam--capture-get-point)
               "test entry%?"
                :file-name "test/%<%Y-%m-%d-%H%M%S>-${slug}"
                :head "#+TITLE: ${title}"
                :unnarrowed t
                :no-save t)))
```
You'll have to save the good buffers by hand then.

In order to fix current org-capture behaviour for org-roam I would suggest the following:
1. record the value of `:no-save` and store it in a separate variable
2. set `:no-save` to `t`
3. add a function to `org-capture-after-finilize-hook` that checks the value of `org-note-abort`
   - if it's true, fine - the buffer has not been saved
   - if it's nil
      - check the original value of `:no-save` recorded in step 1 and if it was `nil` (default), save the buffer
      -  if it was `t`, the user explicitly set it in the template, so do nothing

**Comment by jethrokuan** [comment]
> In order to fix current org-capture behaviour for org-roam I would suggest the following:
> 
>     1. record the value of `:no-save` and store it in a separate variable
> 
>     2. set `:no-save` to `t`
> 
>     3. add a function to `org-capture-after-finilize-hook` that checks the value of `org-note-abort`
>        
>        * if it's true, fine - the buffer has not been saved
>        * if it's nil
>          
>          * check the original value of `:no-save` recorded in step 1 and if it was `nil` (default), save the buffer
>          * if it was `t`, the user explicitly set it in the template, so do nothing

This sounds good. 1 and 2 can be done in `(org-capture--capture-new-file)`.

**Comment by jethrokuan** [comment]
this should be fixed now.

**Comment by khinsen** [comment]
Doesn't quite work, sorry.

1. If I terminate capture with `C-c C-c`, the file is not saved.
2. If I abort with `C-c C-k`, the buffer is not saved, but stays around and is marked as modified. When I quit Emacs, it asks me if I want to save it.

A quick look at the code shows that `org-roam--capture-save-file-maybe-h` is never added to `org-capture-after-finalize-hook`, so it is never called. I'd then say that if it doesn't save the buffer, it should do `(set-buffer-modified-p nil)` and `(kill-buffer)`.
