### ISSUE TITLE
adding roam flag to doom org module

### ISSUE THREAD

**Issue by bdarcus** [jethrokuan/org-roam#311]
I'm not sure if this FR should go here, and/or to Doom, but it would be great to add a `roam` flag on the `org` module, much like the existing `brain` flag for the similar `org-brain`.

https://github.com/hlissner/doom-emacs/tree/develop/modules/lang/org#module-flags

Would simplify installation even further.

**Comment by jethrokuan** [comment]
This should probably come after the MELPA release.

**Comment by bdarcus** [comment]
Yes, certainly. I was just assuming that was immanent, hence.

**Comment by asymmetric** [comment]
Seems like this should be opened on the Doom issue tracker, rather than here.

**Comment by bdarcus** [comment]
I started here because I figured someone here might want to simply submit a
PR to Doom, once org-roam is on MELPA.

And I saw Jethro's post that he moved to Doom himself ;-)

Also, since it's not yet on MELPA, seemed premature.

**Comment by bdarcus** [comment]
With MELPA release, FR added to Doom:

https://github.com/hlissner/doom-emacs/issues/2759

**Comment by bdarcus** [comment]
Doom now has the `+roam` flag, but when I add it, and remove all the previous org-roam config, I'm getting an error that seems related to the #367. 

It's the same error where can't find the org-roam-macs file. When I look in the straight directory, there's a disconnect between the build and repo directories. The first only has symlinks for two of the files.

**Comment by bdarcus** [comment]
The problem, and solution, is here:

https://github.com/hlissner/doom-emacs/commit/f28a304abd1b9e13c4e1217211bef305c5f3badc#r38132446
