### ISSUE TITLE
Grep-based Search View

### ISSUE THREAD

**Issue by l3kn** [jethrokuan/org-roam#318]
### Brief Abstract

Add a mode for listing all files containing a term by searching `org-roam-directory` with grep
and collecting the results in a tabulated list.

### Long Description

This could be used as a basis for implementing #31 by adding a command to turn matches into links.

If you think this would be a good addition to org-roam, I'll clean up my code and create a pull request.

### Proposed Implementation (if any)

1. Use `grep` to search files in `org-roam-directory` for a term
2. Show results (title + match string) in a tabulated list

### Preview

Prototype implementation, searching for files containing "grep"

![2020-03-17_search_view](https://user-images.githubusercontent.com/2060269/76860181-dea63000-685a-11ea-930f-b9ff4ca81b9a.png)

### Please check the following:
- [X] No similar feature requests

**Comment by dbjg** [comment]
I think it would be better to use existing emacs features for this. There are plenty of fuzzy file finder packages for emacs that do this. You can even use the basic `M-x find-grep` to do this.

**Comment by jethrokuan** [comment]
Eventually I'm going to need build a search view, I'm just really tied down with other things atm. Search is hopefully going to look like maybe GitHub's advanced code search.

When that comes, I'll look at what you've done in your repo @l3kn . In 2 months or so, when I'm free :D

**Comment by l3kn** [comment]
@dbjg That's a good point. I like being shown file titles instead of their paths but until there is some more advanced search functionality, that doesn't justify adding new functions / commands to org-roam.

@jethrokuan An advanced search view is a good idea, searching for terms in files could be a sub-functionality of that.
