### ISSUE TITLE
Note creation via capture broken by #315

### ISSUE THREAD

**Issue by khinsen** [jethrokuan/org-roam#319]
### Description
1.  If I terminate capture with `C-c C-c`, the file is not saved.
2.  If I abort with `C-c C-k`, the buffer is not saved, but stays around and is marked as modified. When I quit Emacs, it asks me if I want to save it.

A quick look at the code shows that org-roam--capture-save-file-maybe-h is never added to org-capture-after-finalize-hook, so it is never called. I'd then say that if it doesn't save the buffer, it should do (set-buffer-modified-p nil) and (kill-buffer).

**Comment by brabalan** [comment]
I am having the same issue.
