### ISSUE TITLE
howto : timestamp on save

### ISSUE THREAD

**Issue by alanz** [jethrokuan/org-roam#322]
I find it useful to keep a timestamp of the last changed date for a file, and have modified my setup to do this.  I am sharing it here in case it is useful to anyone else.

In `~/.emacs`

```elisp
(require 'time-stamp)
(add-hook 'write-file-functions 'time-stamp) ; update when saving
```

Then the `:head` entry for the template changes to

```elisp
         :head "#+TITLE: ${title}\nTime-stamp: <>\n"
```

So long as  `Time-stamp: <>` appears in the first 8 lines of the entry, it will be updated on save.

**Comment by jethrokuan** [comment]
I've moved this into the wiki. I'll let the wiki grow as a place for users to contribute small snippets.

**Comment by alanz** [comment]
Thanks. I was hoping it would end up somewhere useful for others.

**Comment by alexvorobiev** [comment]
I have tried to make `time-stamp` it use the standard Org-mode #+date keyword but haven't succeeded :(

```
 (add-hook 'org-mode-hook
                (lambda ()
                  (set (make-local-variable 'time-stamp-pattern)
                       "8/#+date:[ \t]+%:y-%02m-%02d %02H:%02M:%02S")))
```
