### ISSUE TITLE
org-roam forces the *scratch* buffer into Fundamental mode

### ISSUE THREAD

**Issue by jmburgos** [jethrokuan/org-roam#325]
A minor annoyance.  I like to have the *scratch* buffer in lisp-interaction-mode.  Butt when using org-roam, after starting Emacs the *scratch* buffer is in Fundamental mode even if I have
 
`(setq initial-major-mode 'lisp-interaction-mode) 
`
in my .init file.  

Thanks,

Julian

**Comment by khinsen** [comment]
Weird. My scratch buffer is in lisp-interaction-mode by default, without anything in my .init, and it stays in that mode with `org-roam` as well. Also, there is nothing in the `org-roam` code that touches `*scratch*`, nor any reference to `fundamental-mode`. Are you sure that what you observe is not a side-effect of other parts of your Emacs configuration?

**Comment by jmburgos** [comment]
Thanks.  It seems I need to do a bit of research then. :)

**Comment by jethrokuan** [comment]
Can't reproduce this too. Feel free to reopen if this persists.
