### ISSUE TITLE
Recreate a deleted cache.db file

### ISSUE THREAD

**Issue by myshevchuk** [jethrokuan/org-roam#331]
### Description
After deleting `cache.db`, `org-roam-build-cache` does not re-create the file.

#### Steps to Reproduce
When emacs is running and org-roam is loaded:

1. Delete `cache.db`
2. Run `org-roam-build-cache`
3. Follow a link to an org file within `org-roam-direcory`

#### Expected Results
The `cache.db` file is created, the linked file is opened, the org-roam buffer is updated with the information about the visited file.

#### Actual Results
After the first attempt to open the link (C-c C-o) a message appears:
> [Org-roam] your cache isn’t built yet! Please run org-roam-build-cache

The linked file is not opened.

After the second C-c C-o the linked file is opened but the org-roam buffer is not updated, it shows the information about the file from where the link was followed, and the following error is thrown:
> Error in post-command-hook (org-roam--maybe-update-buffer): (error "[Org-roam] your cache isn’t built yet! Please run org-roam-build-cache")

Running `org-roam-build-cache` does not fix the error. The `cache.db` file is only created after turning  `org-roam-mode` off and on or after emacs restart.

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/63b2eaa

**Comment by myshevchuk** [comment]
Sorry, `org-roam.db`.

**Comment by jethrokuan** [comment]
org-roam stores the db connection, which isn't closed when the org-roam cache file is deleted. You can execute `(org-roam--db-close-all)` and run `org-roam-build-cache`, and that should work.

**Comment by myshevchuk** [comment]
Yes, but since `org-roam-build-cache` is an interactive function and the error message explicitly asks to call it to fix the error, shouldn't it do the job?
