### ISSUE TITLE
nested org-roam capture processes not supported?

### ISSUE THREAD

**Issue by bdarcus** [jethrokuan/org-roam#344]
### Description

I added a new note to an existing note as a tag, and then tried to do the same thing in the new note, but got a `nested org-roam capture processes not supported` error.

Am I missing something?

#### Steps to Reproduce

1. insert new note as tag on note A to create note B
2. insert new note as tag on note B

### Versions
- Emacs: v26.3
- Org-roam: v1.0

**Comment by jethrokuan** [comment]
It's precisely what it states. You're still in a capture process for note B, so org-roam-insert cannot spawn a new capture process a new note. I know that this is going to be common, but it's really difficult to support properly. See #327

**Comment by bdarcus** [comment]
I gathered that, but how do I as a user workaround that limitation?

Close the new notes buffer and reopen it with roam find?

**Comment by bdarcus** [comment]
Actually, that doesn't work.

**Comment by jethrokuan** [comment]
Complete the capture, then visit the that new file. Then call org-roam-insert again. Just closing the buffer won't do.

**Comment by bdarcus** [comment]
"Compete" how? The new files are saved.

**Comment by jethrokuan** [comment]
Usually `C-c C-c` to complete the org-capture.

**Comment by bdarcus** [comment]
I ended up simply restarting, because I couldn't find a place to complete the capture.

Now it seems straightforward; I just missed what was going on when I was creating a new note this way. I thought I was seeing simply a new note in roam.

Might be good to add something on this to the documentation.

Perhaps this ...

```
org-roam-insert insert links to existing (or new) notes. Entering a non-existent title will also create a new note with that title.
````

... could be changed to something like this?

```
org-roam-insert insert links to existing (or new) notes. Entering a non-existent title will also create a new note with that title using org-capture. When doing so, make sure to use `C-c C-c` to complete the capture.
```

**Comment by jethrokuan** [comment]
There is a header line there though... which mentions how to finish the capture, or abort it. I don't see the need to be so specific in the docstrings.

**Comment by bdarcus** [comment]
I think mentioning that org-capture is the intermediary is likely
significant, particularly for people without much experience with org-mode.

**Comment by evertedsphere** [comment]
Agreed, I got stuck in "Org-roam capture in process" and couldn't figure it out until I read @bdarcus's last comment.

**Comment by hungpham2511** [comment]
org-roam basically freezes and hangs the emacs process whenever I try to insert a new note now. Quite annoying because the only thing I can do when this happens is to kill the process and start emacs again.
