### ISSUE TITLE
Installation instructions still link to develop branch

### ISSUE THREAD

**Issue by dalanicolai** [jethrokuan/org-roam#345]
### Description
When trying to install your package using the instructions from [the documentation](https://org-roam.readthedocs.io/en/develop/installation/) an error pops up that develop branch does not exist

#### Steps to Reproduce
Just an alert... There is no develop branch in your github repository, but [the instructions](https://org-roam.readthedocs.io/en/develop/installation/#spacemacs) (still) use the develop branch...

**Comment by jethrokuan** [comment]
Where did you find the link to the develop branch documentation? I can't seem to locate it anywhere.

**Comment by bdarcus** [comment]
This line:

``` elisp
(recipe :fetcher github :repo "jethrokuan/org-roam" :branch "develop"))))
```

**Comment by jethrokuan** [comment]
I don't see that in the master branch of the documentation.

**Comment by bdarcus** [comment]
Maybe it's not published yet then? I see that on the documentation link on the main repo page.

https://org-roam.readthedocs.io/en/latest/installation/

**Comment by jethrokuan** [comment]
I think it might've been cached for you, that has been long gone.

**Comment by bdarcus** [comment]
> I think it might've been cached for you, that has been long gone.

That appears to have been the case.

**Comment by dalanicolai** [comment]
Well I never visited your site before. I don't know exactly how I got there but I think I did not follow any unusual path. (I guess I just got there via your home page or via google). Anyway, I will close this issue then...

**Comment by dalanicolai** [comment]
Actually I googled for "org-rome spacemacs" now and that links is the first result...

**Comment by togakangaroo** [comment]
It is definitely still showing for me. Just visited the site

![image](https://user-images.githubusercontent.com/66150/79626380-68b11500-80f5-11ea-95d1-dff0b27fca7b.png)

at this link: https://org-roam.readthedocs.io/en/develop/installation/

It comes up from google

**Comment by jethrokuan** [comment]
That's the develop branch docs link, not the latest/master.
