### ISSUE TITLE
Running ivy-immediate-done after org-roam-insert does not work

### ISSUE THREAD

**Issue by Cumol** [jethrokuan/org-roam#352]
### Description
Using ivy/counsel as my completion backend. Running `org-roam-insert` to create a note with the name `bar `while there is a note called `barricade` leads to selecting the note barricade.

`counsel-find-file` has the option to run `ivy-immediate-done `to resolve this issue. It is also normally bound to `C-M-j `when inside the minibuffer from counsel. Doing this outputs the following:

`Nested Org-roam capture processes not supported`

#### Steps to Reproduce
1. Load Emacs
2. Create note with title `barricade`
3. Run `org-roam-insert`
4. type `bar` to create a note with the title `bar`

#### Expected Results
Capture buffer for note with title `bar`
#### Actual Results
Note with title `barricade` is opened

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam MELPA version: 20200323.734

**Comment by jethrokuan** [comment]
Probably the same issue as #327 . You need to complete the capture before you make another one
