### ISSUE TITLE
org-roam-find-file and org-roam-insert don't allow spaces

### ISSUE THREAD

**Issue by Spass1966** [jethrokuan/org-roam#353]
The file: prompt appears to only accept already existing completion candidates when using spaces to separate words so if an attempted space is added and the file doesn't already exist, org-roam will complain of [no match] and will disallow the space.

**Comment by jethrokuan** [comment]
Use a completion system that allows for non-matches, like ivy or helm.

**Comment by Spass1966** [comment]
I do! I use ivy.

**Comment by jethrokuan** [comment]
Could you share your ivy configuration? In any case, `org-roam` just calls completing-read, the settings that disallow "space" on no match is somewhere in your config.

**Comment by Spass1966** [comment]
> Could you share your ivy configuration? In any case, `org-roam` just calls completing-read, the settings that disallow "space" on no match is somewhere in your config.

I included any package referencing ivy at my gist https://gist.github.com/Spass1966/af5fce5c1fa58b33fc44dedb605d4de5

**Comment by tsproisl** [comment]
Using ido I observe the same behavior. However, it's still possible (albeit a bit cumbersome) to insert a space via C-q SPC.

**Comment by jethrokuan** [comment]
@Spass1966 Nothing looks off. Fwiw I'm using the ivy config in Doom Emacs, but the Ivy config in my original config doesn't have many tweaks and it worked back then.

Nothing I can do about the ido situation, I think that's just how ido was designed to behave
