### ISSUE TITLE
Message during startup

### ISSUE THREAD

**Issue by aaronjensen** [jethrokuan/org-roam#356]
### Description

`org-roam-build-cache` now emits:

```
files: 0, links: 0, titles: 0, refs: 0, deleted: 0
```

There was previously `org-roam-mute-cache-build` which was added in #159. That appears to be gone now.

#### Steps to Reproduce

`M-x org-roam-mode`

#### Expected Results
Silence

#### Actual Results
Message

### Versions
- Emacs (`C-h v emacs-version`): v27
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/3e0a49de037eb49c1ee07643aaa3df2b0e0714c5

**Comment by jethrokuan** [comment]
I can add it back. Would you also prefer it to be muted when it's called manually?

**Comment by aaronjensen** [comment]
That'd be fine with me.

**Comment by aaronjensen** [comment]
Thank you!
