### ISSUE TITLE
Rename file - update corresponding links.

### ISSUE THREAD

**Issue by akoen** [jethrokuan/org-roam#36]
Hi, thanks for a great project. Is it possible to have backlinks automatically update if you rename an org-roam file? I believe that this would lead to more long-term stability.

**Comment by jethrokuan** [comment]
It is, but I think this will come later. I'd like for everything else to be stable first.

**Comment by akoen** [comment]
Yes of course.

**Comment by daniel-koudouna** [comment]
I can pick this up if you want. What would be the expected behaviour on the name of the link? An idea could be:

- unchanged link names would be changed to the new name, i.e
[[file:cool_stuff.org][$cool_stuff]] --> [[file:cool_things.org][cool_things]]

- custom/changed link names would be the same, i.e
[[file:cool_stuff.org][my_stuff]] --> [[file:cool_things.org][my_stuff]]

**Comment by jethrokuan** [comment]
@daniel-koudouna are you on the develop branch? Ideally:

- unchanged link names should be the title of the Org file if it exists, or the file name if not
- custom/changed link names should be the same

I'd expect this to be an advice on `rename-file`.

**Comment by jethrokuan** [comment]
(tbh I'd really like to push for not renaming files to not be part of a workflow, but this seems like a common request)

**Comment by grimsleydl** [comment]
Is using `ord-id` to keep track of things out of the question this far along/to keep dependencies down?

**Comment by jethrokuan** [comment]
> [[id:735f13ef-60e5-43fc3-92c9-6adfhwey][cool_stuff]]

The links are to files, so `org-id` wouldn't help.

**Comment by jdiez17** [comment]
Is the goal of this issue/PR #124 to be able to change the title of an org-roam file, and update the link text of anything that references it, to be the new title? In my opinion this would be a more common use case than renaming the actual underlying file, but let me know what you think.

**Comment by jethrokuan** [comment]
I'd say neither use-cases should be common. But #124 at least makes sure that the cache remains a consistent view of the current state of the files.

**Comment by jethrokuan** [comment]
I believe this should be resolved by #124 .
