### ISSUE TITLE
Symbol’s function definition is void: org-link-make-string

### ISSUE THREAD

**Issue by tmalsburg** [jethrokuan/org-roam#360]
### Description

When I use `org-roam-insert` to link to an existing file, I get an error message: `Symbol’s function definition is void: org-link-make-string`.

#### Steps to Reproduce

My config:

``` elisp
(require 'org-roam)
(setq org-roam-directory "/home/username/documents/")
(org-roam-mode +1)
```

1. Open an org file in `org-roam-directory`.
2. `M-x org-roam-insert`

My org mode doesn't have a function `org-link-make-string` and org roam doesn't have such a definition either.

#### Expected Results
Link.

#### Actual Results
Error message: `Symbol’s function definition is void: org-link-make-string`

### Versions
- Emacs (`C-h v emacs-version`): v16.1.91
- Org-roam commit: Whatever commit I got when I installed org-roam via package.el today.
- Org mode version 9.1.6 from Elpa.

### Hotfix
``` elisp
(defalias 'org-link-make-string 'org-make-link-string)
```

**Comment by jethrokuan** [comment]
org-mode needs to be at least 9.3. So it seems like requiring later versions of org in the `Package-Requires` header doesn't really work :thinking: 

https://github.com/jethrokuan/org-roam/blob/master/org-roam.el#L9

**Comment by tmalsburg** [comment]
Not sure what's going on, but some extra info that may or may not help making sense of this.

1. I was using the built-in version of org (Elpa version not installed). So it's indeed not clear why org-roam installed without complaining.

2. I now installed org from Elpa (v9.3.6) but my Emacs is still using the built-in version after a restart. Not sure why.

**Comment by tmalsburg** [comment]
Well, never mind. This seems to be a problem with my Emacs install and is likely not related to org-roam. I'm closing this issue.
