### ISSUE TITLE
Make inserting links to non-existing notes less disruptive

### ISSUE THREAD

**Issue by tmalsburg** [jethrokuan/org-roam#361]
### Brief Abstract
Currently when I insert a link to a non-existing note, this opens a capture buffer for that note.  This disrupts the writing process unnecessarily.  It'd be better if the new note was created silently, or not at all.
 
### Please check the following:
- [X] No similar feature requests

Thanks for org-roam. Looks really promising even in this early stage.

**Comment by bdarcus** [comment]
> ### Brief Abstract
> Currently when I insert a link to a non-existing note, this opens a capture buffer for that note. This disrupts the writing process unnecessarily. 

I agree with this diagnosis, which is related to #344.

But I'm not sure the best solution.

I also think whatever solution should work for two different cases: 

1. You want to remain in the flow of the current note, and go to the new note later.

2. You (as now) want to go to the new note immediately.

Silently creating the note is perfect for 1.

I guess for 2, it might also work; you'd just click that newly-created note link?

**Comment by jethrokuan** [comment]
You can make it silently complete, if you add `:immediate-finish t` to your capture template, it's your choice.

**Comment by bdarcus** [comment]
Is there something more one needs to do to the template configuration to get it work correctly than simply adding `immediate-finish`?

I have this, but get a "nested org processes not supported" error when trying to link to a new note.

```elisp
  (setq org-roam-capture-templates
        '(("d" "default" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "%<%Y%m%d%H%M%S>-${slug}"
           :head "#+TITLE: ${title}\n"
           :unnarrowed t
           :immediate-finish t)
```

**Comment by tmalsburg** [comment]
Setting `:immediate-finish t` works for me.  Would be good to point this out somewhere in the documentation.  My hunch is that most people would prefer this setting.

A small downside is that the capture buffer pops up for a split second which still causes a (minor) disruption.  But that's largely cosmetic.

**Comment by isolet** [comment]
Is it safe to set `org-roam-capture-templates`? I'm quite new to `org` and I'm not sure since it is declared by `defvar` rather than `defcustom`.

**Comment by jethrokuan** [comment]
> Is it safe to set `org-roam-capture-templates`? I'm quite new to `org` and I'm not sure since it is declared by `defvar` rather than `defcustom`.

It is. There just isn't a good customize interface for setting the value of org-roam-capture-templates. Org-capture-template is also defined with a defvar
