### ISSUE TITLE
Error when including org properties in capture template

### ISSUE THREAD

**Issue by ahristow** [jethrokuan/org-roam#362]
First off, thanks for taking the initiative to create org-roam. I tried Roam Research and within the first two days encountered exactly the problem that drove me from SaaS solutions to orgmode in the first place, namely a server problem that caused me to lose a day's worth of notes. I love the concept, though, so I'm thrilled to have a plain text solution that is fully under my control.

### Description
I transferred a capture template that works fine with org-capture to org-roam. In my original template, I capture entries to a property drawer, but this throws an error in org-roam.

#### Steps to Reproduce

1. Add the following template to `org-roam-capture-templates`:
```
("n" "Non-default" plain (function org-roam--capture-get-point)
    "* %?\n%^{MyProperty}p\n* Heading\n"
    :file-name "%<%Y-%m-%d-%H%M%S>"
    :head "#+TITLE: ${title}\n"
    :unnarrowed t)
```
2. Press `C-c n f` and enter a non-existent note title.

#### Expected Results

I am prompted for a note title and the value of the property `MyProperty`. A new file is created in the capture buffer that looks like this, with the insertion point placed after the first bullet:

```
#+TITLE: The title of my note
:PROPERTIES:
:MyProperty: The property value I assigned
:END:
*
* Heading
```
The template string `"* %?\n%^{MyProperty}p\n* Heading\n"` works as expected with org-capture when defined in `org-capture-templates`.

#### Actual Results

I am prompted for a title, then an error is thrown: `org-capture: Capture abort: Wrong type argument: number-or-marker-p, nil`. No capture buffer is opened.

In this case there is a fairly simple workaround using org-roam's own functionality. This is what I am using in the meantime to get my desired result:
```
("n" "Non-default" plain (function org-roam--capture-get-point)
    "* %?\n:PROPERTIES:\n:MyProperty: ${MyProperty}\n* Heading\n"
    :file-name "%<%Y-%m-%d-%H%M%S>"
    :head "#+TITLE: ${title}\n"
    :unnarrowed t)
```
It works, but based on my (quite possibly incorrect) interpretation of the org-roam code, the template string is supposed to be passed directly to org-capture, in which case it should work the same as it does with `org-capture-templates`.

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: 919d08732cd048de88069444989a3789bd984075

**Comment by jethrokuan** [comment]
Hi, I just tested your template and tit works for me:

![image](https://user-images.githubusercontent.com/1667473/77844485-e01c1480-71d9-11ea-9ac4-e0a69ca5ccb5.png)

**Comment by ahristow** [comment]
I confirm that it works for me now. No idea what the root cause was. I'm still having trouble with a similar, but different, template, but that appears related to org-capture directly and is probably user error rather than a bug.
