### ISSUE TITLE
Automatically updating links?

### ISSUE THREAD

**Issue by anthrolisp** [jethrokuan/org-roam#366]
Is there a way to have org-roam automatically update all links in the event that the filename changes? Many thanks in advance!

**Comment by anthrolisp** [comment]
Maybe, if done within org-roam, something like a renaming function?

**Comment by jethrokuan** [comment]
This is already the case, if you rename the file within emacs.

**Comment by anthrolisp** [comment]
Is there a preferred way to do this in emacs, such as using a particular function over others? Thanks again for all of your work on this!

**Comment by jethrokuan** [comment]
just using `rename-file` would work. Anything that calls it works as well.

**Comment by visika** [comment]
What would be the practice if lots of files happen to get renamed outside of emacs? Like recovering a backup that uses versioning in names or something else.

**Comment by visika** [comment]
OK, I think #222 already talks about that.

**Comment by jethrokuan** [comment]
`rename-file` already updates links for filename changes.

**Comment by Egthee210** [comment]
this is mine I  vent it  pull request eg owner
