### ISSUE TITLE
Modularization broke melpa release

### ISSUE THREAD

**Issue by lberk** [jethrokuan/org-roam#367]
### Description
The org-roam recipe only includes `org-roam.el` and `org-roam-protocol.el` files.

22b9d4b modularized org-roam, but the melpa recipe hasn't been updated to reflect the new files.

#### Steps to Reproduce
1. Load Emacs
2. M-x package-list-packages
3. Update org-roam to org-roam-20200328.1316
4. M-x org-roam

#### Expected Results
Org-Roam loads

#### Actual Results
```Cannot open load file: No such file or directory, org-roam-macs```

### Versions
- Emacs (`C-h v emacs-version`): 26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/22b9d4bd2231dcb0b945b53addac87467d5d2144

**Comment by jethrokuan** [comment]
This should be resolved now.

**Comment by chenyanming** [comment]
THe lastest version can not installed in doom-emacs with 

```
(package! org-roam)
(package! company-org-roam)
```
then
`./.emacs.d/bin/doom sync`

I have to use
```
(package! org-roam :recipe (:host github :repo "jethrokuan/org-roam"))
(package! company-org-roam :recipe (:host github :repo "jethrokuan/company-org-roam"))
```
May I know is it still a melpa issue?
