### ISSUE TITLE
Error: cannot make side window the only window

### ISSUE THREAD

**Issue by pmiddend** [jethrokuan/org-roam#369]
#### Steps to Reproduce

Example:

1. Load Emacs
2. Run `org-roam-find-file`

#### Actual Results
No capturing takes place. Message buffer contains:

```
org-capture: Capture template ‘d’: Cannot make side window the only window
```

Another `org-roam-find-file` leads to: `user-error: Org-roam capture in process`

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/649af5464021ab32660e7703661031334d1ba06d

**Comment by jethrokuan** [comment]
I'm not sure where your first error comes from, but the second error is something that should be fixed in #372 .

**Comment by LOBK** [comment]
I had a similar issue to OP. I managed to fix by undoing the hot fix that Jethro did. It was a weird fix and I'm just adding my 2 cents here so that it can be helpful for others in the future.

**Comment by jethrokuan** [comment]
Closing for now, feel free to reopen if its still an issue.
