### ISSUE TITLE
Org-Roam-Insert results in error "Not in an Org-Roam file"

### ISSUE THREAD

**Issue by LOBK** [jethrokuan/org-roam#377]
### Description

Org-Roam-Insert results in error "Not in an Org-Roam file". This is my first time writing a Github Issue so I apologise if it's too concise.

#### Steps to Reproduce

`M-x Org-Roam-Insert` or using the shortcut `C-c n I`

My `.emacs` file has the lines

```
(require 'org-roam)
(define-key org-roam-mode-map (kbd "C-c n l") #'org-roam)
(define-key org-roam-mode-map (kbd "C-c n f") #'org-roam-find-file)
(define-key org-roam-mode-map (kbd "C-c n b") #'org-roam-switch-to-buffer)
(define-key org-roam-mode-map (kbd "C-c n g") #'org-roam-show-graph)
(define-key org-mode-map (kbd "C-c n i") #'org-roam-insert)
(org-roam-mode +1)
(setq org-roam-directory ".org")
(setq org-roam-buffer-position 'left)
(setq org-roam-completion-system 'default)
(setq org-roam-link-title-format "R:%s")
(setq org-roam-buffer-width 0.4)
```

I suspect `(setq org-roam-completion-system 'default)` may be the issue, so I tried to install `helm` instead, but that threw further errors (related to helm). So I decided to raise this issue to eliminate all troubleshooting variables. 

#### Expected Results

I think it's supposed to show me a preview of my roam files to create a link? 

#### Actual Results

Error "Not in an Org-Roam file" and nothing happens.

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam: org-roam-20200329.952
- Org: 9.3.6

**Comment by jethrokuan** [comment]
You can only call that function in an org roam file (org file in the roam directory). From what buffer are you trying to call that function?

**Comment by LOBK** [comment]
I call the function in an org roam file. My workflow is to `C-c n f` a new org roam file, press `C-c C-c` to save the changes and I try to invoke `org-roam-insert`, but I get the error. I think the problem is that the org-roam db isn't being updated correctly, which confuses org-roam. I am going to try re-installing things and trying again

**Comment by LOBK** [comment]
I have fixed the issue. Using `use-package` instead of a vanilla install helped a lot. Thank you for making this, and continuing to develop it.
