### ISSUE TITLE
Support for navigating daily notes.

### ISSUE THREAD

**Issue by tmalsburg** [jethrokuan/org-roam#378]
### Brief Abstract
When I'm looking at the notes for a day, e.g. `org-roam-today`, I'd like to have function (bound to some key) that allows me to go back and forward a day at a time.

### Long Description
One question: If I'm at today and I go back one, but there is no note for yesterday, do we want to create a note for yesterday, or simply go to the note before today that is the closest in time? Personally, I'd prefer if the missing note was created on the fly.  It may stay empty but that's not a big deal.

### Proposed Implementation (if any)
If the title of the current note looks like a date, take that date, subtract (or add) one day, open note for that new date or create on the fly if non-existent.  If the title does not look like a date, show some message.

I can make a PR if you think this would be a useful addition.  If there is already a way to navigate daily notes, please let me know.

### Please check the following:
- [X] No similar feature requests

**Comment by jethrokuan** [comment]
Do you think it's a good idea to create an empty note with no content for the day while searching forward and backwards? Wouldn't this create noise in your directory?

fwiw if you're using the daily notes stuff heavily, please consider using org-journal instead. There's a lot of functionality there that works well with org-roam (like navigating between daily notes), and I don't think it's a good idea to reinvent the wheel here. The daily notes functionality is sort-of legacy, I'm using org-journal in place of it.

**Comment by tmalsburg** [comment]
> Do you think it's a good idea to create an empty note with no content for the day while searching forward and backwards? Wouldn't this create noise in your directory?

Yes, reasons: 1. I will have an entry for most days anyways. 2. Even if the note is empty, I may link to it from elsewhere, and it may be useful to open the empty note to see the backlinks. 3. I'm simply not worried about having many notes and think notes should be created liberally.  They are not getting in my way anyway (and if they do, that's a UI problem).

> fwiw if you're using the daily notes stuff heavily, please consider using org-journal instead. There's a lot of functionality there that works well with org-roam (like navigating between daily notes), and I don't think it's a good idea to reinvent the wheel here. The daily notes functionality is sort-of legacy, I'm using org-journal in place of it.

Didn't know about org-journal. In this case, I suggest removing the diary functions from org-roam.  IMO org-roam is too young to maintain legacy code, and I think other new users may walk down the same garden path as I did.

**Comment by jethrokuan** [comment]
Org-journal has a nice calendar interface that shows you which days have entries, and will get polluted when there are empty journal dates. 

![image](https://user-images.githubusercontent.com/1667473/78020568-447ad780-7384-11ea-9cc5-e5d07e71681f.png)

I'd think it's also extremely rare to link to a date that previously had no entry. 

> In this case, I suggest removing the diary functions from org-roam. IMO org-roam is too young to maintain legacy code, and I think other new users may walk down the same garden path as I did.

I'd considered removing the code in the past, but it seems like there are some who'd like to keep it (https://github.com/jethrokuan/org-roam/issues/277#issuecomment-597689605), for several reasons:

1. They're using org-journal for something else (personal diary, not inside the org-roam-directory)
2. They don't want to pull down an extra (heavy) package for this daily notes functionality

Which is why I'd intended to keep the daily notes functionality small, anyone who needs it should use migrate to org-journal.

**Comment by tmalsburg** [comment]
> I'd think it's also extremely rare to link to a date that previously had no entry.

Difficult to say without data. I can think of many use cases.  In one of the videos advocating for roam-style note taking the presenter actually recommends creating empty nodes as hubs for links.

> I'd considered removing the code in the past, but it seems like there are some who'd like to keep it (#277 (comment)), for several reasons:

Keeping it but in a semi-functional state seems like the least desirable solution IMO.   But never mind, I'm switching to org-journal. Seems to serve my needs well.
