### ISSUE TITLE
Allow to insert +#TITLE as link name instrad of org-roam-id

### ISSUE THREAD

**Issue by Mishkun** [jethrokuan/org-roam#38]
Currently org-roam-insert uses org-roam--get-id output as a link name. This is not so aesthetical with all of the dashes in the name. What about using file title by default or leting user to input it by themselves?

**Comment by jethrokuan** [comment]
With #41, you should be able to do this now, by setting `org-roam-link-representation`:

`(setq org-roam-link-representation 'title)`
