### ISSUE TITLE
add option to configure graph node attributes

### ISSUE THREAD

**Issue by bdarcus** [jethrokuan/org-roam#382]
I'm trying to add graph node configuration options (for font, color) to my config, but I can't get it work.

Am I doing something wrong, or is this is not currently supported?

```elisp
(setq org-roam-graphviz-extra-options '(("overlap" . "scale")
                                        ("color" . "skyblue")
                                        ("fontname" . "Fira Sans")))
```

**Comment by progfolio** [comment]
The documentation is out of date.
Try:
```emacs-lisp
(setq org-roam-graphviz-extra-options '(("overlap" . "scale")
                                        ("color" . "skyblue")
                                        ("fontname" . "Fira Sans")))
```

**Comment by bdarcus** [comment]
Changing the variable obviously fixes that. Thanks.

But color and fontname options don't have any effect. I'm thinking that's because I need to specify that they're node attributes, while the overlap option is for the graph as a whole.

**Comment by jethrokuan** [comment]
Yeah this isn't supported yet, but should be easy to add.
