### ISSUE TITLE
Cache is not updating on rename/delete. Backlink is also not working.

### ISSUE THREAD

**Issue by Sudraka** [jethrokuan/org-roam#389]
### To start with, thanks for this extraordinary project.

I had added org-roam as a layer in my spcemacs distribution and everything was working perfectly (backlinking & Inserting). But, now, after changing the org-roam directory (in packages.el file) to a new one, and renaming few files in the directory, I could see that the cache was not updating. I have tried to build the cache afresh after manually removing the old file. It is building an empty file and showing no file. Also now backlink buffer is presenting as an empty buffer.

- Emacs 26.3 under Spacemacs distribution
- org has default org-roam minor mode on.
- [Dotspacemacs](https://github.com/jethrokuan/org-roam/files/4413770/Dotspacemacs.txt) file here.

**Comment by jethrokuan** [comment]
What do you mean by changing the org-roam directory in packages.el? There should be a message when you delete the db file and rerun org-roam-db-build-cache, what does it say?

**Comment by Sudraka** [comment]
Initially I was using "~/org/org-roam/" as the default org-roam directory. Later I changed it to "~/org/".
When I rerun org-roam-db-build-cache, only this message is there: "helm-M-x-execute-command: End of file during parsing." and a new org-roam.db file is being generated in ~/org without any content.

**Comment by elliottw** [comment]
i might be experiencing the same issue?
First updated to the new melpa release of org-roam
deleted old db
ran org-roam-db-build-cache
new file created
no issues in messages, just:
files: 0, links: 0, titles: 0, refs: 0, deleted: 0

**Comment by zaeph** [comment]
> i might be experiencing the same issue?

Have you tried restarting?  If that doesn't make it, please eval `(org-roam-build cache t)`.

**Comment by elliottw** [comment]
restart did nothing, assuming you mean `(org-roam-build-cache t)`?
After that, still no links in the sidebar but I do see 'files: 2697, links: 389, titles: 2697, refs: 0, deleted: 0' in messages buffer.

**Comment by zaeph** [comment]
You need to focus an Org-roam file for the `org-roam-buffer` to show you backlinks.

Judging by the output you see in `*Messages*`, it seems like the cache properly rebuilt itself, so if there is still a problem, it must be coming from somewhere elsee.

**Comment by elliottw** [comment]
restarted, org-roam-find-file, select file, seems to be working now, thanks!

**Comment by zaeph** [comment]
I'm closing this.

@Sudraka: If the problem crops up again for you, feel free to re-open the issue.
