### ISSUE TITLE
Require org-roam fails with cannot find 'f file

### ISSUE THREAD

**Issue by renukr** [jethrokuan/org-roam#39]
When I try to load org-roam I get the following error

Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "f")
  require(f)
  eval-buffer(#<buffer  *load*> nil "/home/ANT.AMAZON.COM/renukr/.emacs.d/lisp/org-roam/org-roam.el" nil t)  ; Reading at buffer position 229
  load-with-code-conversion("/home/ANT.AMAZON.COM/renukr/.emacs.d/lisp/org-roam/org-roam.el" "/home/ANT.AMAZON.COM/renukr/.emacs.d/lisp/org-roam/org-roam.el" nil t)
  require(org-roam)
  eval((require (quote org-roam)) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

https://github.com/jethrokuan/org-roam/blob/32865d3d0cc5c647904211fb59f121580fc6e68a/org-roam.el#L12

**Comment by jethrokuan** [comment]
f is from https://github.com/rejeep/f.el and published on MELPA, installing it should fix things: (use-package f)

Things will be like that until the project goes on MELPA unfortunately.

**Comment by jethrokuan** [comment]
This should be resolved, since I've added the relevant `Package Requires` into the elisp files.
