### ISSUE TITLE
`org-roam-capture--in-process` remains `t` even when the capture buffer is closed

### ISSUE THREAD

**Issue by hungpham2511** [jethrokuan/org-roam#399]
#### Steps to Reproduce
1. Insert a new link;
2. Close the capture buffer manually;

#### Expected Results
1. org-roam-capture--in-process is nil, thus allows subsequent captures.

#### Actual Results
1. org-roam-capture--in-process is t, prevent subsequent captures.

### Versions
- Emacs (`C-h v emacs-version`): 28.0.50
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/4ca2606a28f8898299f2e0cc01c01b57cf848006

**Comment by hungpham2511** [comment]
A related issue, which actually is the reason why I happened to "close the capture buffer manually" is that org-roam-insert basically hang when inserting a new note. This behavior is quite random and I can't reproduce it.

**Comment by isolet** [comment]
I got `user-error: Org-roam capture in process` every time I'm trying to run `org-roam-find-file`.

**Comment by juergenhoetzel** [comment]
Fixed by #413
