### ISSUE TITLE
Invalid org-roam-capture-context

### ISSUE THREAD

**Issue by chris-aeviator** [jethrokuan/org-roam#400]
### Description
When setting up org-roam for spaceMacs as described, I'm getting an error. 

However, the mentioned default capture template has not been automatically setup, so I added it to my `.spacemacs` file manually as so:

```
(setq org-capture-templates
    '(("d" "default" plain (function org-roam--capture-get-point)
     	"%?"
     	:file-name "%<%Y%m%d%H%M%S>-${slug}"
     	:head "#+TITLE: ${title}\n"
     	:unnarrowed t)
     )
    )
```
#### Expected Results
orgmode should open the capture buffer for org-roam
#### Actual Results
An error message `invalid org-roam-caputure-context` is displayed in the bottom bar

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- https://github.com/jethrokuan/org-roam/commit/4ca2606a28f8898299f2e0cc01c01b57cf848006

**Comment by jethrokuan** [comment]
You need to use org-roam-capture (the insert and find-file functions) instead of changing org-capture

**Comment by chris-aeviator** [comment]
@jethrokuan thank you for the amazingly quick response. When using org-roam-capture i can see how a title is auto-generated from the filename I chose. The docs mention using the org-capture templates, how do I accomplish this? How do I create org-roam-capture templates, where do I write them into?

**Comment by jethrokuan** [comment]
It should be the other way around: the file name is generated from the title you input. To customize you set `org-roam-capture-templates` like you did above but a different variable name. There's docs on the template system, do have a look at that

**Comment by chris-aeviator** [comment]
awesome - I got it to work. The first screen is asking for "File" as the input

![image](https://user-images.githubusercontent.com/11522213/78467337-d9d7ec00-7735-11ea-93eb-9e72c512306f.png)

Which actually translate to title (in my view). When I create another template with `${tags}` inside the template I get asked `tags` after confirming File with a title. 

I will close this issue since it works but suggest to add the `(setq org-capture-templates` part to the docs, since the rest is pretty much step by step. For all lisp newcomers (I'm using org for long without going into lisp or emacs a lot) this would pretty much help. Awesome support, thanks a ton :beer:
