### ISSUE TITLE
org-roam buffer does not update when changing file via mark ring

### ISSUE THREAD

**Issue by schmeisers** [jethrokuan/org-roam#401]
### Description

After following a link, I often use the mark ring to go back to the file I was previously viewing.  When I do this, the org-roam buffer stays with the linked file.

For example...

From file `a` click a link to file `b`.  As expected, org-roam shows backlinks for `b`.  Then I go back to `a` using `org-mark-ring-goto` but org-roam says on file `b`.

**Comment by jethrokuan** [comment]
Can't seem to reproduce:

![output-2020-04-06-13:36:27](https://user-images.githubusercontent.com/1667473/78526159-bbdcbb00-780b-11ea-8d04-bf0e8e67e71b.gif)

Are both files a and b in the org-roam directory? the backlinks buffer only updates for files part of org-roam.

**Comment by schmeisers** [comment]
Yes, both `a` and `b` are in the org-roam directory.  However, I noticed that my backlinks are no longer working, so I think I may have some additional problems.  I'll mark this as closed.
