### ISSUE TITLE
database separate from other directories

### ISSUE THREAD

**Issue by Trevoke** [jethrokuan/org-roam#404]
### Brief Abstract

It should be possible to store the roam database in a different path than the roam files.

### Long Description

I use org-roam across multiple computers and sync with nextcloud. Today I connected one of the boxes and came across a sync conflict with the two roam databases. This made me sad.

### Proposed Implementation (if any)

N/A

### Please check the following:
- [X] No similar feature requests (or none that I saw anyway)

**Comment by brianmcgillion** [comment]
you can define `org-roam-db-location` to specify the location of the db

**Comment by Trevoke** [comment]
Oh interesting. Did not see that variable when I looked in the version I
have installed. Never mind then! Thanks :)

--

Aldric.

**Comment by jethrokuan** [comment]
yup, that's the variable to set.

**Comment by Trevoke** [comment]
Sorry to bother you again but in what version of org-roam is this variable available? It doesn't show when I search for variables, and there's no updated version of org-roam available on melpa or melpa stable - I seem to be using version 1.0.0-rc1 .

**Comment by progfolio** [comment]
Looks like the Melpa stable version is at 1433dbc and that variable was added shortly after in 3add2c5. Updating org-roam to the latest version should make that variable available to you.

**Comment by Trevoke** [comment]
I mean, I don't particularly want to shift to a non-versioned release if I
can avoid it.

When is the plan for another release?

--

Aldric.

**Comment by progfolio** [comment]
That's up to @jethrokuan . Do you use the built-in package.el for elisp package management or something else like straight or quelpa?

**Comment by Trevoke** [comment]
I think that's orthogonal to the conversation at hand, isn't it? I mean,
whether I use any one of those or a combination of them doesn't really
change my preferences, does it?

--

Aldric.

**Comment by progfolio** [comment]
Not your preference, but your ability to freeze at a version that gives you the functionality you're after. You could bump up to the commit which introduced the variable and freeze there, waiting for the next tagged release. I don't believe this is possible with package.el, but it is with straight and quelpa. You could, alternatively, clone the project and manually install it in your load-path at whichever commit you prefer.
