### ISSUE TITLE
Error when `org-agenda` includes a link to an `org-roam` file

### ISSUE THREAD

**Issue by Zaeph** [jethrokuan/org-roam#408]
Hello,

There seems to be a bad interaction between `org-agenda` and `org-roam` which seems to come from the custom face applied to `org-roam` links.  An error is raised upon building an agenda view which would include an item with a `file` link to an `org-roam` file (i.e. one in `org-roam-directory`).

Here's the traceback:
````
Debugger entered--Lisp error: (args-out-of-range 0 2)
  add-text-properties(0 2 (face org-link))
````

Bear in mind that I use a heavily-customised `org-agenda` setup, and I haven't had the time to run tests in a proper, minimal testing environment.  I thought it'd quicker for any of you to try it out on your end in the meantime.

I've investigated, and I've tracked it down to `org-roam--find-file-hook-function`:
https://github.com/jethrokuan/org-roam/blob/72faa591fb5c86c13786e95e7f8a61663c197b77/org-roam.el#L804-L811

Commenting out the line with `org-link-set-parameters` disable the custom fontification and circumvents the problem.  Also, the reason why I suspect `org-roam` of being the culprit—rather than, say, the function that handles the cosmetic customisation of links—is that `org-ref`'s citation links (which also have a different face) can be included in an `org-agenda` without raising an error.

Thank you for your work on `org-roam`.  I've discovered it yesterday, and I look forward to helping.

HTH,

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: MELPA 20200406.848 (I will move to `master` for testing and helping)

**Comment by juergenhoetzel** [comment]
I also hit this issue. I suppose you also use `~` in your `org-roam-directory`?:
Workaround: https://github.com/jethrokuan/org-roam/pull/470

**Comment by Zaeph** [comment]
> I also hit this issue. I suppose you also use `~` in your `org-roam-directory`?:
> Workaround: #470

You're absolutely right: that was it! 🎉

Good work on tracking it down.  All I did was el-patch `org-roam--find-file-hook-function` and completely forgot about it.
