### ISSUE TITLE
Force New File Creation during Org-roam-find-file

### ISSUE THREAD

**Issue by plwg** [jethrokuan/org-roam#410]
### Brief Abstract

Currently, during `org-roam-find-file`, if there is a matched note with the search string, I can't create a new file with the search string.

### Long Description

For example, I can't create a note with the the title `education` during `org-roam-find-file` if a note called `higher education` already exists, since hitting enter will switch to `higher education`. In `deft`, this was solved by having the option to create new file with the search string with `C-c C-n`. Is there a way to do this in `org-roam`?

### Please check the following:
- [X] No similar feature requests

**Comment by brianmcgillion** [comment]
do you not get a [?] item at the top of the list in `Find File` that allows you to create a new title and not just match an existing one from the list of returned files?

**Comment by jethrokuan** [comment]
The `[?]` item appears only for helm users.

For ivy users, you can call `ivy-immediate-done`, or set `ivy-use-selectable-prompt` to `t`. The default completion mechanism doesn't seem to allow for this, and there's a clause in the documentation stating so.

**Comment by plwg** [comment]
> The `[?]` item appears only for helm users.
> 
> 
> 
> For ivy users, you can call `ivy-immediate-done`, or set `ivy-use-selectable-prompt` to `t`. The default completion mechanism doesn't seem to allow for this, and there's a clause in the documentation stating so.

Thank you! It works!
