### ISSUE TITLE
Permit UTC timestamps in file names

### ISSUE THREAD

**Issue by grzm** [jethrokuan/org-roam#416]
### Brief Abstract

While `org-mode` timestamps sadly don't include time zone, it would be great to be able to use UTC timestamps in `org-roam` file names.

### Long Description

Currently, `org-roam` relies on `org-capture` to encode timestamps in filenames. Natively `org-mode` doesn't include time zone, and currently `org-roam` encodes file names with the local time stamp. While `org-mode` timestamps are local timestamps (with the time zone assumed), it would be nice to be able to encode the UTC timestamp in the filename to preserve the absolute instant when the note was created.

`format-time-string` (and its alias `org-format-time-string`) takes a time zone argument, which would be sufficient to allow a user to supply a time zone along with the format string, perhaps as an optional second argument if a specific time zone were desired.

### Please check the following:
- [X] No similar feature requests

**Comment by jethrokuan** [comment]
You can actually make use of org-capture's ability to evaluate arbitrary emacs-lisp for this:

```
(setq org-roam-capture-templates
        '(("d" "default" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "%(format-time-string \"%Y-%m-%d %H:%M:%S %z\" (current-time))"
           :head "#+TITLE: ${title}\n"
           :unnarrowed t)))
```

Gives me a filename with a timestamp with time-zone. This does feel like an ask for Org, rather than for org-roam.

**Comment by grzm** [comment]
Thank you for the succinct solution. I was thinking there was likely a way to do this, but wasn't aware of being able to use "%(...)" for `:file-name`. I ended up using `"%(format-time-string \"%Y-%m-%d--%H-%M-%SZ--${slug}\" (current-time) t)"` to incorporate the slug as well. Works a treat! This, along with the suggestion in https://github.com/jethrokuan/org-roam/issues/287 to override `org-roam--title-to-slug` have given me the flexibility to create the file names just like I like them. Thanks!

Would you be open to a PR to include these hints in the templating section of the docs?

And I completely agree that the lack of time zone support is a shortcoming of org itself rather than org-roam. Given the ecosystem that's around org and timestamp handling, I think that's a bigger (but very worthwhile, IMO) lift. That you've been support these customizations speaks to the deftness with which you've incorporated org-roam into org. Cheers!

**Comment by jethrokuan** [comment]
> Would you be open to a PR to include these hints in the templating section of the docs?

Sure!

**Comment by jethrokuan** [comment]
@grzm working on #473 , I found that org-capture already has in-built support for `format-time-string` timestamps, so something like:

```
(setq org-roam-capture-templates
        '(("d" "default" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "%<%Y-%m-%d %H:%M:%S %z>-${slug}"
           :head "#+TITLE: ${title}\n"
           :unnarrowed t)))
```

should also work.

**Comment by grzm** [comment]
Here's a PR relating to docs: https://github.com/jethrokuan/org-roam/pull/478

**Comment by grzm** [comment]
The format string in `"%<%Y-%m-%d %H:%M:%S %z>"` will effectively run
```
(format-time-string "%Y-%m-%d %H:%M:%S %z" (current-time))
```
which will use the local time zone.

Passing the third argument, 
``` emacs-lisp
"%(format-time-string \"%Y-%m-%d %H:%M:%S %z\" (current-time) t)"`
```
 will use the specified time zone (with `t` being a synonym for UTC).

For example:

``` emacs-lisp
(setq now (current-time)) 
now ;; => (24216 65280 196524 0)
(format-time-string "%Y-%m-%d %H:%M:%S %z")   ;; => "2020-04-16 19:57:36 -0500"
(format-time-string "%Y-%m-%d %H:%M:%S %z" t) ;; => "2020-04-17 00:57:36 +0000"
```
Both formats represent the same instant. The time zone is included in the output because of `%z`, but the time zone that's used is in formatting is different.
