### ISSUE TITLE
Make file opening search case insensitive

### ISSUE THREAD

**Issue by stefanv** [jethrokuan/org-roam#419]
### Abstract

When opening a note, you have to accurately remember the title capitalization, otherwise the note is not shown in the list of completions.

### Proposed Implementation (if any)

Complete all files that match, regardless of case.

### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
The completing-read behaviour you're seeing is not actually governed by `org-roam`.

For example, how ivy does it is that the filter is case-insensitive by default, but once you type a capital letter, ivy assumes you want to have a case-sensitive search. You'll have to look at the completion mechanism you're using to get the behaviour you want.

**Comment by stefanv** [comment]
Thank you kindly for that explanation, and apologies: I should have done my homework better!

**Comment by jethrokuan** [comment]
No worries, let me know if you still can't figure it out :smile:

**Comment by stefanv** [comment]
The bug fix only required updating the muscle memory algorithm in my brain, so it was a pretty painless firmware upgrade; thanks again!

**Comment by Xunius** [comment]
Hi all. 
I'm also puzzled by the case sensitivity issue. I assume my current settings should work in an insensitive manner, but for some reason I still need to type `Goog` - `Tab` for the note `GoogleNet` to show in my `org-roam-node-find` results. Typing `goog` - `Tab` gives nothing.

I have:

```
(setq org-roam-completion-system 'ivy)
```
for `org-roam`. And `case-fold-search` is `t` for `ivy`. What am I missing?

Versions:
+ org-roam: 20220102.603
+ org: 9.4
+ Emacs: 27.1

Thanks!

**Comment by asymmetric** [comment]
For vertico, I had to set `completion-ignore-case t`.

**Comment by stefanv** [comment]
I think `org-roam-completion-system` was a v1 feature. Try `(setq org-roam-completion-everywhere t)` perhaps? Ivy's default is `auto` for `ivy-case-fold-search-default`, which has the behavior described above (typing only lower case searcher both upper and lowercase).

**Comment by Xunius** [comment]
@stefanv I did have `(setq org-roam-completion-everywhere t)`, and I have verified that `ivy-case-fold-search-default` and `ivy-case-fold-search` are both `auto` in my emacs. But I'm still not getting insensitive completions. So is my ivy not working properly? I have got ivy=20230714.751.

These are my org-roam configs, in case you could spot anything wrong:

```
(use-package org-roam
    :ensure t
    :hook
    (after-init . org-roam-db-autosync-mode)
    :custom
    (org-roam-directory "~/Notebooks/org")
    :config
    (setq org-roam-completion-everywhere t)
    (setq org-roam-completion-system 'ivy)
    (define-key org-roam-mode-map [mouse-1] #'org-roam-buffer-visit-thing)
    (define-key org-roam-mode-map (kbd "RET") #'org-roam-buffer-visit-thing)
    (org-roam-setup)
    :bind (("C-c n l" . org-roam-buffer-toggle)
            ("C-c n f" . org-roam-node-find)
            ;("C-c n b" . org-roam-switch-to-buffer)
            ("C-c n g" . org-roam-graph)
            ("C-c n i" . org-roam-node-insert)
            ("C-c n a" . org-roam-alias-add)
            ("C-c n r" . org-roam-ref-add)
            ;("C-c n I" . org-roam-insert-immediate)
            :map org-mode-map
            ("C-c i" . completion-at-point)
)
)
```
