### ISSUE TITLE
Bug: `org-id-get-create` hook causes an error that prevent completing capture process

### ISSUE THREAD

**Issue by iSeeU816** [jethrokuan/org-roam#420]
Hello,

Firstly, I want to thank you for developing this package. It's a good thing to
see alternatives in Emacs to many other tools.

### Description

Secondly, I recently started testing org-roam package, while doing that I fall
into a bug. The bug prevent capture buffer from completing the capture process
with `C-c C-c`, or canceling it with `C-c C-k`.

I figured out what the cause of that, when disabling the cause, org-roam
function very well.

#### Steps to Reproduce

I will write a simple one now, and if you still can't reproduce it; then I will
write a detailed one.

1. Start a fresh Emacs, nothing in `.emacs.d` directory.
2. Setup Melpa to install `use-pacakge` and `org-roam`.
   - use-package 2.4 (20200322.2110).
   - org-roam 1.0.0-rc1 (20200409.426).
     - This will install Org. Its version as of now is 9.3.6.
3. Setup `org-roam` like in README file example.
4. Run `org-roam-mode`.
5. Success process:
   1. Run `org-roam-find-file`.
   2. Type `foo`, and a capture buffer will be created.
   3. Hit `C-c C-c` to complete capturing.
6. Fail process:
   1. Evaluate this:

      ``` elisp
      (use-package org
        :hook (org-capture-prepare-finalize . org-id-get-create))

      ;; Or even this:
      (add-hook 'org-capture-prepare-finalize-hook #'org-id-get-create)
      ```

   2. Run `org-roam-find-file` and type `bar` as the filename.
   3. Once hitting `C-c C-c`, an error will appear:
      - `Before first headline at position 14 in buffer CAPTURE-<timestamp>-bar.org`.
   4. In addition, when attempt to create a new file `C-c n f`, this error appear:
      - `Org-roam capture in process`.

I noticed that when creating a heading in `bar` file, no error was occurred. So,
the error was because of the messing heading(s) in the file. I think `org-roam`
doesn't require any headings in the file; as the user can create a new file as a
tag, and have it empty to write info in it later.

#### Expected Results

Like described in *success process* above, the file should be created when
complete the capture process.

#### Actual Results

An error prevents the capture buffer from complete. Beside that, calling
`org-roam-find-file` to create another file will fail. The latter can be
workaround by restarting Emacs.

### Versions

- Emacs (`C-h v emacs-version`): v26.3 (7.8; Emacs Mac port).
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/6e9700396733ec1273d3331713d651e4d5195121

Thank you, again!

**Comment by progfolio** [comment]
That hook function would fail for captured entries that aren't Org headings.
You would want to guard against this so it doesn't fail for other capture template entry types (in org-roam or otherwise).

There may be some corner cases I haven't thought of, but a conditional guard in your hook function should do the trick:

```emacs-lisp
(defun my/org-capture-add-entry-id ()
  (unless (org-before-first-heading-p)
    (org-id-get-create)))
```

**Comment by iSeeU816** [comment]
Great! The function you provide works very well.

I tested it with all my Org capture templates and `org-roam-find-file` command,
all worked OK!

``` elisp
(defun my/org-capture-add-entry-id ()
  (unless (org-before-first-heading-p)
    (org-id-get-create)))

(use-package org
  :hook (org-capture-prepare-finalize . my/org-capture-add-entry-id))

;; Or:
(add-hook 'org-capture-prepare-finalize-hook #'my/org-capture-add-entry-id)
```

Thank you very much for your help! That's fixed it.
