### ISSUE TITLE
Autocompletion for links and tags

### ISSUE THREAD

**Issue by alex-rozenshteyn-leapyear** [jethrokuan/org-roam#421]
### Brief Abstract

Rather than using `org-roam-insert`, sometimes I want to be able to just press `TAB` or just have a list of suggestions pop up while I'm typing.

### Long Description

I would like company-mode style completion in three contexts:
- inside double square brackets (for a link); e.g. `[[comp|]]` (where the `|` is the cursor) might pop up completion.
- After a hash mark (for a tag); I know org-roam doesn't currently support tags, so this is for later
- After an at-sign (for a tag); this would be alternate syntax that would be useful for me

### Please check the following:
- [x] No similar feature requests

**Comment by brianmcgillion** [comment]
Have you enabled and tried, https://github.com/jethrokuan/company-org-roam

**Comment by jethrokuan** [comment]
Yup using `company-mode` and `company-org-roam` is the solution `org-roam` provides. I should probably add a link to it somewhere in the docs.

**Comment by alex-rozenshteyn-leapyear** [comment]
I'll try it out. I must have assumed it wasn't implemented because I didn't find documentation.
