### ISSUE TITLE
Documentation request: how do you configure your capture frame?

### ISSUE THREAD

**Issue by brabalan** [jethrokuan/org-roam#430]
I have setup the roam protocol (thank you for this great addition!), and I think it would be great if you could document how to set up the call to emacsclient to get the dedicated frame you show in https://org-roam.readthedocs.io/en/master/roam_protocol/.

Also, `org-roam-ref-capture-templates` should be renamed `org-roam-capture-ref-templates` in that page.

**Comment by jethrokuan** [comment]
The dedicated frame in that gif is just the default window configuration for org-capture. Configs like Doom changes it, I think it's something to do with `display-buffer-alist`.

**Comment by brabalan** [comment]
Thanks, I'll keep investigating then. I guess you call to emacsclient simply uses to `-c` argument?

**Comment by jethrokuan** [comment]
> Thanks, I'll keep investigating then. I guess you call to emacsclient simply uses to `-c` argument?

yes.

**Comment by brabalan** [comment]
Thank you for the information. It seems that `display-buffer-alist` is indeed the culprit.
