### ISSUE TITLE
Permission denied, /path when org-roam-db-build-cache

### ISSUE THREAD

**Issue by RCoeurjoly** [jethrokuan/org-roam#441]
### Description

I am following the [steps](https://org-roam.readthedocs.io/en/latest/configuration/#having-more-than-one-org-roam-directory) indicated to configure having more than one org roam directory.

To do so, I cloned the [braindump](https://github.com/jethrokuan/braindump/) repo
#### Steps to Reproduce

1. Clone [braindump](https://github.com/jethrokuan/braindump/) in my home directory
2. Create .dir-locals.el in the root of the cloned repo with `((nil . ((org-roam-directory . "~/braindump/"))))`
2.1 I tried both relative and absolute path, to no avail
3. Load Emacs
4. Open file ~/braindump/org/org-roam.org
5. Type y when prompted to add local variables
6. Run `org-roam-db-build-cache`

#### Expected Results
DB cache built successfully!

#### Actual Results
helm-M-x-execute-command: Creating directory: Permission denied, /path

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: I installed through spacemacs.
The org roam dir has this name inside elpa:
org-roam-20200411.1041

**Comment by jethrokuan** [comment]
I followed similar steps as you, and it works for me... the `/path` error is strange, is that the actual path `/path`?

**Comment by RCoeurjoly** [comment]
I think a clue to find the error is that when I describe the variable org-roam-directory from a org file I got "/path/to/org-files/".

The issue is that I cannot reproduce either, but I get another error.

**Comment by jethrokuan** [comment]
Any updates to this? `/path/to/org-files` appears in the docs, and README, but never in the code, so you must've added it somewhere.

**Comment by RCoeurjoly** [comment]
Yes, let's close it

**Comment by RCoeurjoly** [comment]
> Any updates to this? `/path/to/org-files` appears in the docs, and README, but never in the code, so you must've added it somewhere.

I does appear in the code. Line 10 of packages.el.
