### ISSUE TITLE
Allow selecting among multiple capture templates

### ISSUE THREAD

**Issue by alarsyo** [jethrokuan/org-roam#448]
### Brief Abstract

Correct me if I'm wrong, but currently, it seems only the first template of `org-roam-capture-templates` can actually be used; having multiple ones in there doesn't prompt for anything and just selects the first, "default" one.

### Please check the following:
- [x] No similar feature requests

**Comment by alarsyo** [comment]
My bad, it *does* prompt for which template to use, only after having asked for a title, hence my confusion (I'd written a template that handled titles in its own ways)

**Comment by jethrokuan** [comment]
Yup, that's also because it's not necessary to launch a capture if no new file is created.
