### ISSUE TITLE
Consolidate org-roam-graph commands

### ISSUE THREAD

**Issue by progfolio** [jethrokuan/org-roam#450]
Currently we have four commands that do similar things from a user perspective:

- `org-roam-graph-build`
- `org-roam-graph-show`
- `org-roam-graph-build-connected-component`
- `org-roam-graph-show-connected-component`
  
Instead of exposing four similar commands, we could make three of them private functions
and dispatch based on the prefix argument in `org-roam-show`.
The following prefix arguments could dispatch like so:

    | Prefix | Effect                           |
    |--------+----------------------------------|
    | nil    | show  graph                      |
    | N      | show connected with max N steps  |
    | C-u    | build graph                      |
    | C-u -  | build connected                  |
    | C-u -N | build connected with max N steps |

# implementation sketch

After making the other three commands private functions,
we dispatch based on the prefix-arg:

```emacs-lisp
(defun org-roam-show (&optional arg node-query)
  (interactive "P")
  (let ((dispatched
         (pcase arg
           ('nil "showing")
           ('(4) "only building")
           ('-   "only building (connected)")
           ((pred (> 0))  "only building (connected with steps)")
           ((pred (< 0))  "showing (connected with steps)"))))
    ;;etc
    ))
```

Thoughts?

**Comment by jethrokuan** [comment]
Maybe we can expose instead expose these functionality using `transient`, or `hydra`, which allows for a bit more discoverability.

**Comment by progfolio** [comment]
That's not a bad idea for users that prefer using something like hydra or transient. For those who don't, this would be a way to allow more flexible functionality from a single key-binding/command. Hydra/transient users could still bind to multiple keys by wrapping the command and passing the appropriate arg. e.g.

```emacs-lisp
(defun my/org-roam-build-graph ()
  "Wrapper for `org-roam-show-graph' which only builds the graph."
  (org-roam-show-graph '(4)))
```

**Comment by kljohann** [comment]
I would also humbly ask to not introduce too many _required_ dependencies (e.g. while I use transient in my configuration I'm trying to avoid pulling in hydra). :upside_down_face:

On the other hand having a single entry-point into the graph generation (like you suggest) sounds convenient. Though should the user maybe still have the possibility to conveniently/directly call into the underlying functions, if they want a more specific key binding? Also, separate commands might still be more discoverable. Maybe the dispatcher could be built on top of them?

**Comment by progfolio** [comment]
In terms of discoverability, all the uses of the prefixes would be in the docstring for `org-roam-show-graph`. Similar to how `org-capture` and `org-refile` and many other commands work.

Just to be clear, I'm not proposing we get rid of the the underlying functions, just that we don't expose them as commands. So a user could still wrap those functions (which I would not recommend as they would be 'private' and subject to name change without an alias) or, ideally, wrap `org-roam-show-graph` with the desired argument applied like the example in my last comment.

**Comment by jethrokuan** [comment]
> Having a single entry point would reduce duplication and ensure consistency between the commands as well.

Yeah this is important. An intermediary interface like Org's export would be both similar and familiar.

**Comment by progfolio** [comment]
> An intermediary interface like Org's export would be both similar and familiar.

I agree this would be good to have down the line and can imagine something that would allow users to save their own node queries. I've submitted a pull that consolidates the current functionality into a single command for now. That should make that transition easier if/when we need it and still gives us the benefits mentioned above in the mean time.
