### ISSUE TITLE
Predictable multi-user-incompatible file naming for dot graph tmp files

### ISSUE THREAD

**Issue by nrvale0** [jethrokuan/org-roam#453]
### Description
org-roam-graph-show generates static tmp file name of /tmp/graph.dot for all users. This means that after one user generates a graph subsequent users cannot generate graph as they will get a "Permission denied" error message on /tmp/graph.dot.

#### Steps to Reproduce
1. Load concurrent Emacs sessions as 2 or more users.
2. User 1 executes org-roam-graph-show and receives graph.
3. User 2 executes org-roam-graph-show and receives "Permission denied" error for /tmp/graph.dot.

#### Expected Results
org-roam uses randomly-generated + non-predictable tmp file names for graph output. Ideally in a tmp directory which is chmod 700 for each user as the current graph.dot files is chmod +r. 

#### Actual Results
static file name of /tmp/graph.dot with chmod +r.

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: 4af4d2e4d5f18422fe0f90d5d83fe4c10ef1a20f

**Comment by progfolio** [comment]
@nrvale0 : I think that should do the trick. On my system it creates the files with  permissions set to `600`. Is that sufficient as far as permissions are concerned or is there a need for the executable bit?

**Comment by nrvale0** [comment]
(defun my/tmp-file-in-dir (name_prefix)
      (let ((name_prefix (or name_prefix (user-login-name))))
        (with-file-modes ?\700
          (make-temp-file
           (format "%s/%s"
    	       (make-temp-file (format "%s/%s" temporary-file-directory name_prefix) t)
    	       "graph.dot.")))))
    
    (setq my_tmp_file_path (my/tmp-file-in-dir "blarg"))
    (setq my_tmp_file_modes (file-attribute-modes (file-attributes my_tmp_file_path "string")))
    
    (print (format "%s :: %s" my_tmp_file_path my_tmp_file_modes))

    
    "/tmp/blargOAjCrq/graph.dot.j95dyG :: -rw-------"

**Comment by progfolio** [comment]
I understand what you're requesting now, though I wonder if there's a better way to support this use-case.  Perhaps a variable `org-roam-directory`, which would allow the user to decide where the graph files are stored? This would also allow users to decide whether or not they want to keep their generated graphs longer than "/tmp" will store them.
Another potentially useful customization would be something like `org-roam-graph-file-name` which would allow users to customize the names of the files output by `org-roam-graph-build`.  These seem more flexible overall.

**Comment by nrvale0** [comment]
Those sound like they could be useful features as well. My  main concern was to remove the multi-user conflict and do so in a way that represented as close as I can get with my meager elisp skills to secure tmp file handling.

**Comment by jethrokuan** [comment]
This specific issue was resolved in #454 , so I'm closing it for now.
