### ISSUE TITLE
Huge latency at start of Org-roam

### ISSUE THREAD

**Issue by rougerbaptiste** [jethrokuan/org-roam#46]
I happen to see huge latency at every start of org-roam, or each buffer change to an org buffer.

Here are enclosed the profiler reports for Memory and CPU respectively :

**Memory :**
- timer-event-handler                                     279,189,753  93%
 - apply                                                  279,189,753  93%
  - org-roam--build-cache-async                           279,189,753  93%
   - setq                                                 279,007,713  93%
    - org-roam--find-all-files                            279,007,713  93%
     - org-roam--find-files                               279,007,713  93%
      - if                                                279,007,713  93%
       - let                                              279,007,673  93%
        - let                                             278,989,999  93%
         - while                                          278,989,999  93%
          - cond                                          278,989,999  93%
           - if                                           278,962,833  93%
            - progn                                       278,960,761  93%
             - setq                                       278,960,761  93%
              - append                                    278,960,761  93%
               - org-roam--find-files                     278,960,761  93%
                - if                                      278,960,761  93%
                 - let                                    278,954,981  93%
                  - let                                   278,870,845  93%
                   - while                                278,870,845  93%
                    - cond                                278,870,845  93%
                     - if                                 278,870,845  93%
                      - progn                             278,870,845  93%
                       - setq                             278,870,845  93%
                        - append                          278,870,845  93%
                         - org-roam--find-files           278,870,845  93%
                          - if                            277,773,573  93%
                           - let                          252,883,214  84%
                            - let                         190,833,546  64%
                             - while                      190,833,546  64%
                              - cond                      178,830,067  60%
                               - and                       86,725,554  29%
                                - string=                  36,549,233  12%
                                 - file-name-extension     33,409,421  11%
                                    file-name-sans-versions         6,246   0%
                                    file-name-nondirectory         6,246   0%
                                    vector                      4,164   0%
                                    make-byte-code              2,082   0%
                                    #<compiled 0x1b553f5>         2,082   0%
              not                                               2,072   0%
           + and                                               18,406   0%
   + async-start                                              182,040   0%
+ command-execute                                          18,483,416   6%
+ linum-update-current                                         27,880   0%
+ ...                                                           8,188   0%
+ redisplay_internal (C function)                               2,096   0%
+ polymode-post-command-select-buffer                           1,056   0%
  async-when-done                                                 912   0%
+ flycheck-display-error-at-point-soon                            160   0%

**and CPU :**
- ...                                                            4686  90%
 - while                                                         4176  80%
  - cond                                                         4176  80%
   - if                                                          4176  80%
    - progn                                                      4176  80%
     - setq                                                      4176  80%
      - append                                                   4176  80%
       - org-roam--find-files                                    4176  80%
        - if                                                     4176  80%
         - let                                                   4176  80%
          - let                                                  4176  80%
           - while                                               4176  80%
            - cond                                               4176  80%
             - if                                                4176  80%
              - progn                                            4176  80%
               - setq                                            4176  80%
                - append                                         4176  80%
                 - org-roam--find-files                          4172  80%
                  - if                                           4172  80%
                   - let                                         4024  77%
                    - let                                        2472  47%
                     - while                                     2472  47%
                      - cond                                     2436  47%
                       - and                                     1124  21%
                        - string=                                 404   7%
                         - file-name-extension                    380   7%
                            file-name-sans-versions                100   1%
                            #<compiled 0x1af2921>                   4   0%
                       + if                                        28   0%
                        setq                                       12   0%
   Automatic GC                                                   510   9%
+ command-execute                                                 459   8%
+ timer-event-handler                                              24   0%
+ linum-update-current                                              8   0%

Thanks !

**Comment by jethrokuan** [comment]
Just to confirm, you're on current master commit https://github.com/jethrokuan/org-roam/commit/6f1938e1ac6866456f8ca53384710b43d65f037e?

**Comment by jethrokuan** [comment]
A similar issue was recently fixed, see https://github.com/jethrokuan/org-roam/issues/33. Most of the time is spent in `(org-roam--find-files)`, which is no longer called during buffer changes. And the async build shouldn't be noticeable to the end user.

**Comment by l3kn** [comment]
@jethrokuan Seems like `(org-roam--find-files)` is called outside of the `async-start`
at https://github.com/jethrokuan/org-roam/blob/master/org-roam.el#L237.

**Comment by rougerbaptiste** [comment]
I wasn't on this commit for the profiler, though I just updated to the last commit. As you mentioned, I observe no more latency when changing buffer, even though there still is at the opening of the first org buffer.
I happen to be unable to make a new profiler (it returns me an error), but I guess the profiler would be the same as above since I didn't change buffer after the load of the first org file previously. I'll try to make you a more relevant report.

**Comment by jethrokuan** [comment]
> @jethrokuan Seems like `(org-roam--find-files)` is called outside of the `async-start`
> at https://github.com/jethrokuan/org-roam/blob/master/org-roam.el#L237.

yeah you're right, I think I can shift this in too.

**Comment by jethrokuan** [comment]
Merged a fix (I think), I don't have enough org files to make it slow :cry: . If this fixes your problem, do close the issue.

**Comment by jethrokuan** [comment]
Actually @rougerbaptiste how many files do you have, and how nested? `(org-roam--find-files)` is being called during `(org-roam-insert)` and `(org-roam-find-file)`. I'm thinking of caching the list of files, but then there's added complexity of keeping the cache up-to-date again.

**Comment by rougerbaptiste** [comment]
Actually I don't have much org files : just did a `find . -name "*.org"` in my home folder and located only 31 files, with files not nested under the 4th directory from my home folder.

**Comment by jethrokuan** [comment]
Hmm I see, hopefully you don't see anymore large lags... I have 250 org-files (0 nesting) and it's still instant.

**Comment by jethrokuan** [comment]
I'm going to close this for now, feel free to reopen if you're still seeing issues.
