### ISSUE TITLE
Customize file extension

### ISSUE THREAD

**Issue by samspo** [jethrokuan/org-roam#461]
### Brief Abstract
My files use the .txt extension instead of .org. It allows me to interact with the files on ios. Would it be possible to allow the customization of the file extension?

### Please check the following:
- [X] No similar feature requests

**Comment by TimQuelch** [comment]
.org files are simply text files anyway, you should probably be able to open them anyway.

If they were changed to .txt files, you would probably need to include a buffer local mode-line in all your notes so that emacs knows to open them in org-mode
e.g. 
` # -*- mode: org -*-`

**Comment by samspo** [comment]
Yes, .org files are text files and I use orgmode for my text files. 
But, files with a .txt extension are not included in org-roam. My understanding is that it is only designed for files with an .org extension. Am I wrong?

**Comment by jethrokuan** [comment]
I've added `org-roam-file-extensions`, and doing:

```
(setq org-roam-file-extensions '("org" "txt"))
```

should work for your usecase.

**Comment by samspo** [comment]
Thank you! It almost works. Except for "org-roam-insert". 
I want all my roam files with a .txt extension
`(setq` org-roam-file-extensions '("txt"))
But when I create a new file with "org-roam-insert" it creates an .org file.
I suspect the problem might be in "org-roam--file-path-from-id" ?

**Comment by paranoidsp** [comment]
This is exactly what I hoped to find, thanks! I have a problem though.

`org-roam-file-extensions` does not seem to support the empty string value. I have a bunch of files from org-journal that don't have a .org extension, is there a covenient way to support that?
Here's my configuration

```
(setq org-roam-file-extensions '("org" ""))
```

Please let me know if I'm doing something wrong.
