### ISSUE TITLE
Opening an IRC channel: #org-roam@freenode

### ISSUE THREAD

**Issue by Zaeph** [jethrokuan/org-roam#469]
When I'm working on a feature, I often find myself wanting to discuss some of its aspects with users and devs.  Communicating via GitHub is good for traceability and relating issues/PR together, but I wish we had a more informal setting to discuss.

I think it'd be interesting if we could open an IRC channel over @freenode.  As someone who spends a lot of time in #ranger@freenode, I can vouch for the efficacy of IRC for working on projects, and also just for shooting the breeze.
~~I'll be hanging out in ##org-roam@freenode if people are interested.  I could also [register a group with Freenode](https://freenode.net/groupreg) to have something a little more official and manage the channel.~~
It turns out you don't have to request anything, so I went ahead and register #org-roam@freenode! 🎉

### Please check the following:
- [x] No similar feature requests

**Comment by asymmetric** [comment]
I would be interested. There's already a [Slack](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg) channel but IRC is obviously a superior choice :)

**Comment by Zaeph** [comment]
> I would be interested. There's already a [Slack](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg) channel but IRC is obviously a superior choice :)

Oh yeah, you're write, I forgot to mention the fact that there was already a Slack channel.  I don't know anything about them, so I've just suggested IRC out of habit.

**Comment by jethrokuan** [comment]
I'd rather not have fragmentation, would be good if someone could set up bridges between the different platforms.

**Comment by Zaeph** [comment]
> I'd rather not have fragmentation, would be good if someone could set up bridges between the different platforms.

There seems to be options available online, but since I don't use Slack, I'd be hard-pressed to implement it.  I'm not sure how much fragmentation that'd introduce into the community, since I doubt there is all that much overlap between the people on Slack and the people on IRC.  IRC is pretty good for development work, but I'm only vouching for what I know.

Should I not use the name #org-roam@freenode if you don't want affiliation, then?

**Comment by Zaeph** [comment]
All right, I've found a way to join Slack via IRC, so it's good for me.  I'm a bit iffy about joining a proprietary platform, and I'd appreciate if we could keep the IRC channel open to provide support for those who would be reluctant on joining.

**Comment by dit7ya** [comment]
There exists mattermost which can act as a bridge, but it seems like this has to be hosted. Maybe there are free slack bots but I could not find any with a simple search. 

Relevant xkcd : https://xkcd.com/1782/

**Comment by Zaeph** [comment]
On my end, I've installed [wee-slack](https://github.com/wee-slack/wee-slack), a WeeChat plugin for Slack which seems quite good.

**Comment by jethrokuan** [comment]
@Zaeph you're free to have the IRC channel open, let's see where it goes for now. Not sure if many people these days still use it. I used to lurk on #nixos and #emacs, but it wasn't that useful.

**Comment by Zaeph** [comment]
> @Zaeph you're free to have the IRC channel open, let's see where it goes for now.

Thank you.

> Not sure if many people these days still use it. I used to lurk on #nixos and #emacs, but it wasn't that useful.

I'm not sure about the *many*, but I know that we do the bulk of the work for [ranger](https://github.com/ranger/ranger) on IRC.  It's pretty useful for working together on code, and it's a more informal setting to my eye.

I can't speak for #emacs and #org-mode because I've hardly spent any time in them.  However, I know that it helped to have an informal channel of communication with one of the maintainer when I was working on a patch.
