### ISSUE TITLE
Allow custom function to open back-links

### ISSUE THREAD

**Issue by ram535** [jethrokuan/org-roam#471]
I found a little inconvenience that everytime I open a back-link, it opens a new window.

I tried to make a function that open any link in an already open buffer that is not the `*org-roam*` buffer. 

But somehow `*org-roam*` buffer does `not` respect this function.

```
  (defun my/open-link (file)
    (if(get-buffer-window "*org-roam*" (selected-frame))
        (if(string= (buffer-name) "*org-roam*")
            (find-file-other-window file)
          (find-file file))
      (find-file file))))

  (org-link-frame-setup '((file . my/open-link)))

```

**Comment by ram535** [comment]
Yes, that works. But I am having a hard time trying to bind it to the mouse left click. I am using evil.

**Comment by jeffyql** [comment]
If you use general: https://github.com/noctuid/general.el
This may work:

(general-define-key
 :definer 'minor-mode
 :keymaps 'org-roam-mode
 :states 'normal
 "<down-mouse-1>" 'my/org-open-at-point
 )

**Comment by ram535** [comment]
It did not work for me. I guess it is  really tricky to bind it to a mouse key. Thanks for trying. It gave me a lot of clarifications.
