### ISSUE TITLE
Don't propose "bibliography ressources" when using org-roam-insert

### ISSUE THREAD

**Issue by tdehaeze** [jethrokuan/org-roam#474]
Let me first describe my workflow using `org-roam` which is I guess, quite usual:
- each paper/book I read has its own org file with `#+ROAM_KEY: cite:bibtex_entry` at the top

Then: 
- When I want to reference something in my bibliography from the note file, I generally use `helm-bibtex` that will insert `cite:bibtex_entry` to the file and everything work (back-links, ...)
- When I want to link to another "topic/tag" (and not a bibliography element), I use `org-roam-insert`.
  In such case, all the papers/books appear in the helm buffer and it is not very convenient to find the "topic/ag" I want to link.

Is there a way to do **not** show the files with a Roam key that look like `cite:something`?

That will be very useful.

Thanks a lot

**Comment by bdarcus** [comment]
Let me see if I understand this conceptually.

Let's assume two types of OR notes:

1. default/standard notes
2. bibliographic notes; these are ones with the `#+ROAM_KEY: cite:`, which is what designates them as such in the system

So each bib entry only has 1 bibliographic note associated with it, and OR linking only happens to standard notes (1 above).

Therefore, you're saying that logically, 2 should not be completion candidates when inserting links.

Is that all correct?

If yes, I think I agree with you! 

The UI needs to help users understand the logic of the system.

**Comment by tdehaeze** [comment]
You are exactly right.

**Comment by bdarcus** [comment]
> So each bib entry only has 1 bibliographic note associated with it, and OR linking only happens to standard notes (1 above).

I guess the key question is whether this is a correct assumption.

**Comment by tdehaeze** [comment]
If I understand correctly, Org Roam links are standard org links, so nothing is preventing us for linking to any file at all, right? 

So I don't know if we should _only_ be able to link to "standard notes" (1 above) using `org-roam-insert`.

One solution I can think of would be to make a function similar to `org-ref-insert` that _only_  autocomplete links to "standard notes" (e.g. that does not show of links to "bibliographic notes").


The thing is that I may have a **lot** of references with the "tag" (corresponding to the standard note) I want to link to in their title. 
All these papers titles are polluting the autocomplete function, and it is more difficult to find the standard note I want to link to. If I want to link to a reference I would like to use a separate function (`helm-bibtex` for instance).

I think I kind of repeat myself but I hope it is more clear now.

**Comment by Zaeph** [comment]
I can see the value behind excluding ref-notes from some uses of `org-roam-insert`, but I don't think we should make it the default.

I think there is value in allowing user to filter the inputs to `org-roam-find-file` and `org-roam-insert`.  All we'd need needing is an extra argument to pass a function to those commands, and to modify this (in the two):
https://github.com/jethrokuan/org-roam/blob/e1873a6a1660b5c4f850df2da578d1a1b851f8ac/org-roam.el#L376

Then, the user could write functions like `org-roam-insert-non-refs` which would exclude all refs from the candidates.

**Comment by tdehaeze** [comment]
That seems perfect to me

**Comment by Zaeph** [comment]
> That seems perfect to me

I'll start working on a prototype, then.

**Comment by Zaeph** [comment]
Proposition in #481.
