### ISSUE TITLE
Exclude certain note classes from backlinks in exports

### ISSUE THREAD

**Issue by visika** [jethrokuan/org-roam#484]
### Brief Abstract
I'd like to keep private notes from appearing in the backlinks of an exported note.
### Long Description
These can be useful for the writer to make connections, but may be confidential or useless for an audience to see when published.
This is somewhat a mix of #220 and #223.
### Proposed Implementation (if any)
We could get something functionally similar to `(setq org-roam-graph-exclude-matcher "private_")` to put in the config file.
### Please check the following:
- [x] No similar feature requests

**Comment by jethrokuan** [comment]
This is what I have in my personal config:

```
(after! (org org-roam)
    (defun my/org-roam--backlinks-list (file)
      (if (org-roam--org-roam-file-p file)
          (--reduce-from
           (concat acc (format "- [[file:%s][%s]]\n"
                               (file-relative-name (car it) org-roam-directory)
                               (org-roam--get-title-or-slug (car it))))
           "" (org-roam-db-query [:select [from]
                                  :from links
                                  :where (= to $s1)
                                  :and from :not :like $s2] file "%private%"))
        ""))
    (defun my/org-export-preprocessor (_backend)
      (let ((links (my/org-roam--backlinks-list (buffer-file-name))))
        (unless (string= links "")
          (save-excursion
            (goto-char (point-max))
            (insert (concat "\n* Backlinks\n" links))))))
    (add-hook 'org-export-before-processing-hook 'my/org-export-preprocessor))
```

It excludes anything with "private" in the filename.

**Comment by visika** [comment]
Thanks the help! Maybe I'll learn elisp one day to make these on my own :)
