### ISSUE TITLE
Capture note title as link description when using org-store-link

### ISSUE THREAD

**Issue by ricklupton** [jethrokuan/org-roam#487]
### Brief Abstract

`org-store-link` can be used to store a link to an org-roam file, but it does not store the title of the note. This means when you insert the stored link into an org file you get the path only with no description. It would be more useful if it stored the title of an org roam file as the link description, as well as the file name. 

### Long Description

As discussed in #477. 

@Zaeph wrote:

> At first, I was on the fence because I think that `org-roam-insert` should specifically work with `org-roam` files (i.e. inside `org-roam-directory`. After all, we can use `org-store-link` to get a link to the file. Problem is, if `org-before-first-heading-p` is `t`, we would only get the file-name, which might not be very informative.
>
> We could create a new link-handler for `org-roam` which would fill the visible part of a link with the `#+TITLE` of a note. We might also want to _avoid_ the usual behaviour which, when `org-before-first-heading-p` is `nil`, would link you to the nearest parent heading.

### Proposed Implementation (if any)

Create a new store link handler as described above. 

### Please check the following:
- [X] No similar feature requests

**Comment by juergenhoetzel** [comment]
> Create a new store link handler as described above.

Addressed in PR #491
