### ISSUE TITLE
Search within notes

### ISSUE THREAD

**Issue by Gahamelas** [jethrokuan/org-roam#493]
Is searching within notes implemented? This would be an important feature for me to install the package. Thanks!

**Comment by Zaeph** [comment]
> Is searching within notes implemented? This would be an important feature for me to install the package. Thanks!

Unless you're encrypting your files, you could use a tool like [`ripgrep`](https://github.com/BurntSushi/ripgrep) ([rg.el](https://github.com/dajva/rg.el) for Emacs integration) to search within the content of all your files.

**Comment by Gahamelas** [comment]
Thanks. That means that org-roam does not or does search within notes (not encrypted notes)? PS. Thanks for the tip on riprep. I'll have a look.

**Comment by Zaeph** [comment]
> That means that org-roam does not or does search within notes (not encrypted notes)?

We search the content of files (even the encrypted ones) to compute the backrefs and build the database, but we don't provide commands for users to search within their files.  Since we're using plain-text, there are already advanced tools to handle the searching, and `rg` is one of the most efficient.

**Comment by jethrokuan** [comment]
> That means that org-roam does not or does search within notes (not encrypted notes)?

Yes, that is not within the scope of org-roam.

**Comment by Gahamelas** [comment]
Thanks. I would like to know if org-roam would then create the links between notes or if I have to specifically add tags or similar to the notes. I have over thousand notes... that is why I ask.

**Comment by Zaeph** [comment]
> I would like to know if org-roam would then create the links between notes or if I have to specifically add tags or similar to the notes. I have over thousand notes... that is why I ask.

There is no way to link your notes for you.  The goal of the slip-box method is to have meaningful links between your notes, and only you can do this.  You're not supposed to plop all your notes into your `org-roam-directory` and call it a day: you have to adapt your notes following a certain number of principles.

See @jethrokuan's [blog post](https://blog.jethro.dev/posts/how_to_take_smart_notes_org/) for a primer on the topic.

To go further:
- <div class="csl-bib-body" style="line-height: 1.35; margin-left: 2em; text-indent:-2em;">
  <div class="csl-entry">Clear, David B. ‘Zettelkasten — How One German Scholar Was So Freakishly Productive’. Medium, 6 January 2020. <a href="https://writingcooperative.com/zettelkasten-how-one-german-scholar-was-so-freakishly-productive-997e4e0ca125">https://writingcooperative.com/zettelkasten-how-one-german-scholar-was-so-freakishly-productive-997e4e0ca125</a>.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&amp;rft.type=webpage&amp;rft.title=Zettelkasten%20%E2%80%94%20How%20One%20German%20Scholar%20Was%20So%20Freakishly%20Productive&amp;rft.description=Luhmann%20wrote%20over%2070%20books%20and%20more%20than%20400%20scholarly%20articles%20using%20the%20Zettelkasten%20notetaking%20method.&amp;rft.identifier=https%3A%2F%2Fwritingcooperative.com%2Fzettelkasten-how-one-german-scholar-was-so-freakishly-productive-997e4e0ca125&amp;rft.aufirst=David%20B.&amp;rft.aulast=Clear&amp;rft.au=David%20B.%20Clear&amp;rft.date=2020-01-06&amp;rft.language=en"></span>
</div>

- <div class="csl-bib-body" style="line-height: 1.35; margin-left: 2em; text-indent:-2em;">
  <div class="csl-entry">Ahrens, Sönke. <i>How to Take Smart Notes: One Simple Technique to Boost Writing, Learning and Thinking for Students, Academics and Nonfiction Book Writers</i>, 2017.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=urn%3Aisbn%3A978-1-5428-6650-7&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=How%20to%20Take%20Smart%20Notes%3A%20One%20Simple%20Technique%20to%20Boost%20Writing%2C%20Learning%20and%20Thinking%20for%20Students%2C%20Academics%20and%20Nonfiction%20Book%20Writers&amp;rft.aufirst=S%C3%B6nke&amp;rft.aulast=Ahrens&amp;rft.au=S%C3%B6nke%20Ahrens&amp;rft.date=2017&amp;rft.isbn=978-1-5428-6650-7&amp;rft.language=English"></span>
</div>

**Comment by Gahamelas** [comment]
Thanks. I asked because you mentioned earlier "We search the content of files (even the encrypted ones) to compute the backrefs and build the database". I did not really understand this unless it meant that it creates automatically "backrefs" (=links). Otherwise, why would it have access to the content of the files?

**Comment by Zaeph** [comment]
> I did not really understand this unless it meant that it creates automatically "backrefs" (=links).

When you have a link to a file, it's simple: you know the entry point (the current file), and you know the exit point (the file to which the link is pointing).  For computing backrefs, all we have is an exit point, and we need to check *all* the files in your `org-roam-directory` to know if any of them links to this exit point (i.e. the current file).

This is why I said that we search the content of your `org-roam` files.  The links *you* create are meaningful.  All we do behind the curtain is ensure that the link you created works both ways.

**Comment by Gahamelas** [comment]
All clear, thanks.
