### ISSUE TITLE
org-roam-graph--open is repeated 

### ISSUE THREAD

**Issue by zzp0** [jethrokuan/org-roam#496]
### Description
The PR #488 and #490 caused it.

**Comment by progfolio** [comment]
Sorry for the bug! Can you be more specific by what behavior you are seeing and how to reproduce it? Do you mean that the graph is opened twice when calling `org-roam-graph`, or something else?

**Comment by progfolio** [comment]
Apologies, I see what you mean now. Bad merge conflict resolution on my end.

**Comment by zzp0** [comment]
Sorry for the ambiguous bug report. (English is not my native language)

**Comment by progfolio** [comment]
Not a problem. I appreciate the report and understood clearly once I had the source code in front of me.
