### ISSUE TITLE
No cite backlinks

### ISSUE THREAD

**Issue by goktug97** [jethrokuan/org-roam#504]
I've been using the library before the MELPA. Today I saw amazing improvements and features so installed the library from the MELPA. I have a lot of cite:<name> references in my notes but none of them are shown in the org-roam buffer. Everything is set on the org-ref side. I can open and insert references using org-ref. Am I missing something?

```elisp
(use-package org-ref
  :config
  (setq org-ref-default-bibliography '("/home/goktug/bibliography/brain.bib")
        org-ref-pdf-directory "/home/goktug/bibliography/"
        bibtex-completion-bibliography "/home/goktug/bibliography/brain.bib"
        bibtex-completion-library-path "/home/goktug/bibliography"
        bibtex-completion-pdf-open-function 'org-open-file)
  :ensure t)

```

**Comment by zaeph** [comment]
Your bibliographic notes need to be somewhere inside your `org-roam-directory` for them to be detected by `org-roam`.  Note that you will also have to add a file-metadata tag `#+ROAM_KEY: cite:<citekey>` to have them detected by `org-roam`.

Look into [`org-roam-bibtex`](https://github.com/zaeph/org-roam-bibtex) for more info.  We're working on a migration script with @tmalsburg in zaeph/org-roam-bibtex#11 to allow users to migrate their existing library.

**Comment by goktug97** [comment]
It seems I missed the point. There should be a note for the cite.
I installed `org-roam-bibtex` but when I try to edit a note I get `Wrong type argument: stringp, nil` error. I assume org-roam only searches for the notes while org-roam-bibtex creates notes for the references?

**Comment by zaeph** [comment]
> I installed `org-roam-bibtex` but **when I try to edit a note** I get `Wrong type argument: stringp, nil` error. [emphasis added]

What do you mean by this?  Are you opening the note with `org-ref`?  `helm-bibtex`? From `org-roam-find-file`?  Without a backtrace of the error, we can't tell you what went wrong.  Please open an issue on `org-roam-bibtex` if you would like us to work on it.

> I assume org-roam only searches for the notes while org-roam-bibtex creates notes for the references?

It's a little more complex than that.  `org-roam-bibtex` is a connector between `org-ref` and `helm-bibtex`/`ivy-bibtex`, and we add a few things to `org-roam` to make it easier to manage your notes.  Check the read-me for more details.

**Comment by goktug97** [comment]
https://github.com/zaeph/org-roam-bibtex/issues/14

**Comment by tmalsburg** [comment]
Re migration script: Teaching period is starting here and things are a bit chaotic. May take a couple of days before I get to it.  But it's going to happen sooner or later because I need to migrate my own notes.

**Comment by zaeph** [comment]
> Re migration script: Teaching period is starting here and things are a bit chaotic. May take a couple of days before I get to it. But it's going to happen sooner or later because I need to migrate my own notes.

Sure thing, don't worry about it.  It's finals week for me, so I'll be short on time for the next two weeks.  Good luck to us both!
