### ISSUE TITLE
org-roam-backlink face never applies

### ISSUE THREAD

**Issue by Wetlize** [jethrokuan/org-roam#515]
### Description

When opening the backlink buffer `org-roam-backlink` will never apply its face to links that are backlinks. Grepping the codebase didn't show me anywhere where `org-roam-backlink` should actually apply, so I guess the code is missing somewhere?

#### Expected Results
`org-roam-backlink` should apply its face on backlinks in the backlink buffer.

#### Actual Results
The backlink buffer renders all backlinks with `org-roam-link` face.

### Versions
- Emacs (`C-h v emacs-version`): 26.1
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/d01f7b2dafcbcb4f7ca3e5f9ab4bec125070e1d4

**Comment by zaeph** [comment]
There seems to be a problem with that, yes.  I'm on it.

**Comment by zaeph** [comment]
So, I've investigated, and there seems to have been some problems with the code.

6eb7238daf8051e48dc559cb57b1ed14b824e742 introduced the `org-roam-backlink` face:
https://github.com/jethrokuan/org-roam/blob/6eb7238daf8051e48dc559cb57b1ed14b824e742/org-roam.el#L887

f27e5f2384529630e28e5643b56e9d78d2e018bf removed the fontification, but it's not referencing any issue in the tracker.

**Comment by Wetlize** [comment]
> Do you need to have a specific face for backlinks in your workflow, different than the one used for org-roam files?

Yes, though it's not critical. Sometimes I rename inserted links to a something different from the title, so it can help me to more quickly identify that the link in the backlink buffer points to the currently opened file, instead of other files in the `org-roam-directory`.

**Comment by zaeph** [comment]
> Yes, though it's not critical. Sometimes I rename inserted links to a something different from their corresponding title, so it can help me to more quickly identify that the link in the backlink buffer points to the currently opened file, instead of other files in the `org-roam-directory`.

The links would still be fontified with the face `org-roam-link` if their visible part differ from the title of the file to which they point.  The logic is based on whether the destination file is in `org-roam-directory`:
https://github.com/jethrokuan/org-roam/blob/d01f7b2dafcbcb4f7ca3e5f9ab4bec125070e1d4/org-roam.el#L462-L467

**Comment by Wetlize** [comment]
This should fix it:
```lisp
(defun org-roam--roam-link-face (path) 
  "Conditional face for org file links. 

Applies `org-roam-backlink' if PATH corresponds to currently
open Roam file in the backlink buffer, or `org-roam-link-face'
if PATH corresponds to any other Roam file."
  (cond ((string= (file-name-nondirectory path)
                  (buffer-name org-roam-buffer--current))
         'org-roam-backlink)
        ((org-roam--org-roam-file-p path)
         'org-roam-link)
        ('org-link)))
```

Though I wrote this very quickly and haven't test any edge cases yet.

**Comment by zaeph** [comment]
OK, now I understand, and I see the value in that.  Good work on finding that out!

Your implementation is good, but I can think of problems with sub-dirs since you're only checking for `file-name-nondirectory`.  I'm working on a solution right now.  Would you like to make a PR, or should I take care of it?

**Comment by Wetlize** [comment]
> Would you like to make a PR, or should I take care of it?

Thanks, I would be totally fine if you (or someone else) would do that, since I'm swamped right now and the more robust implementation would require me to dive deeper into the codebase.

**Comment by zaeph** [comment]
> > Would you like to make a PR, or should I take care of it?
> 
> Thanks, I would be totally fine if you (or someone else) would do that, since I'm swamped right now and the more robust implementation would require me to dive deeper into the codebase.

Sure, I'll take of it.  The problem I'm trying to solve right now:
- `sub1/file.org` and `sub2/file.org`
- `sub2/file.org` has a link to `sub1/file.org`
- Link is formatted as a back-link because we're only considering the filename.

I'm working on it, and it shouldn't be too complicated.

**Comment by rasendubi** [comment]
Just noticed this issue…

Originally, all reference *lines* (not links) were fontified as code in org-roam, which looked ugly in my setup. I introduced `org-roam-backlink` face to allow changing that.

Just wanted to highlight that this issue assigns quite a different meaning to `org-roam-backlink` face.
