### ISSUE TITLE
The backlink buffer doesn't correctly open links from the preview area using sub-directories

### ISSUE THREAD

**Issue by Wetlize** [jethrokuan/org-roam#517]
### Description
When you have your files spread across multiple sub-directories the links of which point to files across all other notes in sub-directories of `org-roam-directory`, opening them from the preview area of the backlink buffer will not properly resolve them (i.e. it will not open the correct file). Read further for more details.

This only happens when you use `org-roam-open-at-point` at the preview area with the point put on a link itself. If you use `org-roam-open-at-point` at a pure (non-linking) text, then it will properly resolve to the destination of the text, as expected.

#### Steps to Reproduce
In `org-roam-directory` create files copying the next structure:
- `org-roam-directory`
  - foobar1.org
  - foobar2.org
  - foo/
    - foo1.org
    - foo2.org
  - bar/
    - bar1.org
    - bar2.org

Put this in `foo1.org`:
```
[[file:../foobar1_org.org][Foobar]] from the main root, [[file:../foobar2.org][Foobar2]] from the main root, [[file:foo1.org][(foo) Foo1]] (self-loop) and [[file:foo2.org][(foo) Foo2]] from =foo= subdir, [[file:../bar/bar1.org][(bar) Bar1]] and [[file:../bar/bar2.org][(bar) Bar2]] from =bar= subdir.
```

Then try open all these links from the preview area of the backlink buffer. It doesn't matter which file you use select as your `org-roam-buffer--current` candidate, since all of them will behave the same.

#### Expected Results
Links that are part of the preview content should properly resolve their paths to correct destinations.

#### Actual Results
The links resolve instead the next way:
- links to `foobar1.org`, `foobar2.org`, `bar1.org`, `bar2.org` will always resolve to `foo1.org` file.
- link to `foo1.org` and `foo2.org` will always create new buffers in the main root of `org-roam-directory`.

### Versions
- Emacs (`C-h v emacs-version`): 26.1
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/963692f353090359b0513cc75abe92e7e7546bfc, #516 and #427 (tried all merged and separated).

**Comment by Wetlize** [comment]
As for now, I've wrote this hack for myself as a temporary solution:
```lisp
(defun my-org-roam-follow-preview-links-a (orig-fn &rest args)
  (cl-assert org-roam-backlinks-mode)
  (let* ((path (save-excursion
                 (org-backward-heading-same-level 1 t)
                 (forward-word)
                 (file-name-directory
                  (org-element-property :path (org-element-context)))))
         (default-directory path))
    (apply orig-fn args)))

(advice-add #'org-roam-open-at-point :override #'my-org-roam-follow-preview-links-a)
```

Anyone is welcome to open a PR for this issue, if you want a more elegant and robust solution.

**Comment by zaeph** [comment]
I can reproduce this.  I'd run into this issue in my testing yesterday, but couldn't figure out at the time if it was the code I was writing or `master`.

This is similar to the problem in #516, and I might be able to fix it with some of the functions I've written for it.  I'm on it.

**Comment by zaeph** [comment]
For the sake of illustration, here's what the MWE does:
- violet : Org-roam links
- maroon : Org-roam links to current file
- blue : normal `org-link` which shows that those Org-roam links are borked
![screenshot-7DWRw8ABxz](https://user-images.githubusercontent.com/12202828/80286191-3cffe180-872a-11ea-9b92-bffb21ebd716.png)

Compare `Foobar2` which is properly identified as an Org-roam link in the `org` buffer, but not in the side-window.

I think I might be able to replace every links in the side-window with an absolute path.  That would resolve the issue.

**Comment by Wetlize** [comment]
> I think I might be able to replace every links in the side-window with an absolute path. That would resolve the issue.

I thought myself rebuilding paths too (either, relatively from `org-roam-directory` or as absolute paths), but quickly glancing the rest of the codebase was not sure whether it would conflict with the whole design at the lowest level. So I've decided to dynamically switching `default-directory` instead, reading the correct path from the header.

However, just how you mentioned, it doesn't fix the issue that links that suppose to have `org-roam-link` render themselves as `org-link` instead. I thought creating a separated issue for that, but it looks like there's a single source that causes all that.

**Comment by zaeph** [comment]
> I thought myself rebuilding paths too (either, relatively from `org-roam-directory` or as absolute paths), **but quickly glancing the rest of the codebase was not sure whether it would conflict with the whole design at the lowest level**.

I don't think it would.  Without changing the way links are created in Org-roam files, I think the best way to handle this is to modify links to be absolute in the side-window.

This is the function I'm looking at right now:
https://github.com/jethrokuan/org-roam/blob/13f6b9e288d0568019bbbe6d05cdcd322ae1c72e/org-roam-buffer.el#L130-L153

I'm not sure if L150-151 are inserting text-properties, but I think this is something I could use.  I'll check that tonight.

**Comment by zaeph** [comment]
All right, some progress.  This might be the key:
https://github.com/jethrokuan/org-roam/blob/963692f353090359b0513cc75abe92e7e7546bfc/org-roam.el#L218
Seems like we should be able to do the rel-to-abs conversion here with no impact whatsoever on other code.  I'll try that out.
