### ISSUE TITLE
Installation with straight breaks current org installation

### ISSUE THREAD

**Issue by gcantieni** [jethrokuan/org-roam#529]
### Description
Org roam installation with straight causes me to clone org, which breaks my org installation. I think this might just be my own incompetence, maybe I should somehow specify with straight that I don't want to download deps? Maybe I should update my org installation separately because roam requires a newer installation? Still, I haven't been able to figure out how to make Org work again except by disabling org-roam and deleting the `org` file from my straight packages.

#### Steps to Reproduce
```
(straight-use-package-by-default t)
(use-package org-roam)
```

#### Expected Results
Uses the version of org that already comes with Emacs.

#### Actual Results
Clones the Org installation into the straight file and breaks my Org configuration (i.e. can't use org-agenda because all functions are unbound).

### Versions
- Emacs: v26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/41423005010f2f78c3e9301b97f1b0db83fd29b5

**Comment by gcantieni** [comment]
I think this can be solved by using the cloned straight version of org. Straight uses a hack to fix the straight version of org (since org expects its makefile to be run), but it seems the hack isn't applied to org if it's downloaded as a dependency. I fixed it by putting `(use-package org)` before the two lines mentioned in the initial issue comment. 

I'm still interested whether org-roam could be installed through straight without having to migrate to the straight version of org, though.

**Comment by jethrokuan** [comment]
The version of Org that ships with Emacs is too old, and org-roam depends on a version that's relatively new (>9.2) for some functionality. I suspect that earlier, you had loaded org before org-roam. which resulted in loading the pre-installed org instead of the new org that org-roam depends on and pulls down.
