### ISSUE TITLE
eval-buffer: Cannot open load file: No such file or directory, org-roam-compat

### ISSUE THREAD

**Issue by akoen** [jethrokuan/org-roam#530]
### Description
Using the master version of org-roam with straight.el, I get the error `eval-buffer: Cannot open load file: No such file or directory, org-roam-compat` when executing org-roam-mode. Furthermore, org-roam-mode is the only command from org-roam that is available in `M-x`. Finally, org-roam does not appear as a listing in `describe-package`. Everything works normally when using org-roam version 1.0.0.

#### Steps to Reproduce

1. Open emacs
2. Error message appears in messages.

#### Expected Results

Org-roam loads without error and appears as a package in `describe-package`.

#### Actual Results

- `eval-buffer: Cannot open load file: No such file or directory, org-roam-compat`.
- Package is missing in `describe-package`.

### Versions
- Emacs (`C-h v emacs-version`): 28.0.50
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/41423005010f2f78c3e9301b97f1b0db83fd29b5

**Comment by jethrokuan** [comment]
Can you navigate to the `build` and `repo` folders for `org-roam` in the `straight` folder, and post what you see?

**Comment by akoen** [comment]
![image](https://user-images.githubusercontent.com/43913902/80330182-52900c80-87f9-11ea-89b6-898cdfe8df57.png)

![image](https://user-images.githubusercontent.com/43913902/80330135-35f3d480-87f9-11ea-9f58-d9ad88460396.png)

Thanks for taking the time to help.

**Comment by jethrokuan** [comment]
You'll probably need to run `straight-rebuild-package` for org-roam, or delete both folders and rerun the straight pull again. It might be using the old MELPA recipe.

**Comment by akoen** [comment]
Before posting this, I had done that several times, to no avail. However, after deleting my entire straight directory and rebuilding everything, it was resolved.

Emacs is like this sometimes. Thanks for your help, you're the best.

**Comment by zaeph** [comment]
> Emacs is like this sometimes.

I think this is more a problem with the way `straight` handles the building of packages.  You're not the only who run into this issue in the past week.

At any rate, glad you got it working!
