### ISSUE TITLE
multi word font names prevent svg graph from displaying

### ISSUE THREAD

**Issue by technovangelist** [jethrokuan/org-roam#535]
### Description
I have added the following to customize the svg graph:
`
  (setq org-roam-graph-node-extra-config '(("style" . "filled")
                                           ("fontname" . "hasklig")
                                           ("fontsize" . "10")))
`
If i set the font to anything with two words, then the graph shows only an error: This XML file does not appear to have any style information associated with it. The document tree is shown below. 
#### Steps to Reproduce
Change the fontname to any font with a two or more word name

#### Expected Results
it displays a graph

#### Actual Results
It doesn't display a graph
### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by tecosaur** [comment]
@technovangelist I think I came across this issue too, and found escape quotes were required
https://github.com/tecosaur/emacs-config/commit/d7c26ad77754e15ef10041a1d58b0f4d06e922d4#diff-e8ccbb431f6e823868bda1b2365f5ef0R943-R948

**Comment by jethrokuan** [comment]
@tecosaur i'm pushing a fix for this now.

**Comment by tecosaur** [comment]
That timing :smile:
