### ISSUE TITLE
Better Docs for Roam Protocol

### ISSUE THREAD

**Issue by theianjones** [jethrokuan/org-roam#536]
### Brief Abstract
I am trying to set up a chrome bookmarklet to add an http resource to my org-roam. I've followed the guide in setting up platypus. Heres my configuration

![Image 2020-04-28 at 5 06 47 PM](https://user-images.githubusercontent.com/4407263/80537827-aa9e4e80-8972-11ea-9246-87631bdd0cda.png)

![Image 2020-04-28 at 5 07 07 PM](https://user-images.githubusercontent.com/4407263/80537839-b427b680-8972-11ea-9d24-00a2fefe786e.png)

Ive set up my capture templet in `.doom.d/config.el`:

```lisp
(use-package! org-roam
  :commands (org-roam-insert org-roam-find-file org-roam-switch-to-buffer org-roam)
  :init
  (setq org-roam-directory "~/Desktop/03-resources/org-roam")
  (setq org-roam-graph-viewer "/usr/bin/open")
  (map! :leader
        :prefix "n"
        :desc "org-roam" "l" #'org-roam
        :desc "org-roam-insert" "i" #'org-roam-insert
        :desc "org-roam-switch-to-buffer" "b" #'org-roam-switch-to-buffer
        :desc "org-roam-find-file" "f" #'org-roam-find-file
        :desc "org-roam-show-graph" "g" #'org-roam-show-graph
        :desc "org-roam-insert" "i" #'org-roam-insert
        :desc "org-roam-capture" "c" #'org-roam-capture)
  :config
  (require 'org-roam-protocol)
  (setq org-roam-capture-templates
        '(("d" "default" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "${slug}"
           :head "#+TITLE: ${title}\n"
           :unnarrowed t)
          ("p" "private" plain (function org-roam-capture--get-point)
           "%?"
           :file-name "private-${slug}"
           :head "#+TITLE: ${title}\n"
           :unnarrowed t)))
  (setq org-roam-ref-capture-templates
        '(("r" "ref" plain (function org-roam-capture--get-point)
           "%?"
           :file-name "websites/${slug}"
           :head "#+ROAM_KEY: ${ref}
#+TITLE: ${title}
- source :: ${ref}"
           :unnarrowed t)))
  (org-roam-mode +1))
```

The bookmarkley is just a book mark with:
Title: Add to Roam
url: 
```js
javascript:(function(){location.href = 'org-protocol://roam-ref?template=r&ref='+ encodeURIComponent(location.href)+ '&title='+ encodeURIComponent(document.title)})();
```

when I click the bookmarklet a buffer is opened inside of the platypus directory:

![Image 2020-04-28 at 5 10 09 PM](https://user-images.githubusercontent.com/4407263/80538105-24363c80-8973-11ea-92f0-018737db0d1d.png)

Do yall have any advice for debugging this issue?

**Comment by jethrokuan** [comment]
What's inside `launch_emacs_plat.sh`?

**Comment by theianjones** [comment]
<img width="524" alt="Image 2020-04-29 at 10 26 48 AM" src="https://user-images.githubusercontent.com/4407263/80607844-fbaa5300-8a03-11ea-8136-a5f167765b06.png">

<img width="632" alt="Image 2020-04-29 at 10 29 35 AM" src="https://user-images.githubusercontent.com/4407263/80608127-58a60900-8a04-11ea-82e7-7bd6b1a22b04.png">


[Here are the steps I took to install Doom Emacs.](https://www.ianjones.us/notes/org-roam).

Let me know if I can provide any more info

**Comment by jethrokuan** [comment]
Is your path to emacsclient correct? (is it symlinked to `/usr/local/bin/emacsclient`)? From the behaviour of clicking the link, I think that's fine. It seems to me that the `org-roam-protocol` library had not yet been required.

Could you evaluate `(require 'org-roam-protocol)` manually, and try the bookmarklet?

Are you running emacs as a server (read https://www.emacswiki.org/emacs/EmacsClient)? It could be that it's launching a new Emacs instance, which doesn't have the libraries loaded.

**Comment by theianjones** [comment]
I've made sure emacs is running as a server and that `(require 'org-roam-protocol)` in in my `config.el`. Here are my doom config files if that helps at all.. https://github.com/theianjones/dotfiles/tree/master/.doom.d

I did run this even though im not using emacs mac port just trying to see if that would help. Could this be the problem?

```
If you're using Emacs Mac Port, it registered its Emacs.app as the default handler for the URL scheme org-protocol. We have to make our OrgProtocol.app the default handler instead (replace org.yourusername.OrgProtocol with your app identifier):

$ defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add \
'{"LSHandlerPreferredVersions" = { "LSHandlerRoleAll" = "-"; }; LSHandlerRoleAll = "org.yourusername.OrgProtocol"; LSHandlerURLScheme = "org-protocol";}'
Then restart your computer.
```

**Comment by theianjones** [comment]
^ was it. I shouldn’t have added the protocol to my p-list. I think I didn’t have (require org-roam-protocol) in the right spot, I ran that command to add the protocol to my p list and then it was just broken from there.

Thanks for helping me out. I’m pretty new to Emacs and lisp so I appreciate the patience.

**Comment by jethrokuan** [comment]
Thanks for patiently debugging this issue. That wasn't something I could confirm.

I looked through your Doom config and noticed you removed ROAM_KEY from your ref template. That's fine, but that would mean for websites new notes are recreated when using the bookmarklet instead of accessing the old one. Is that the behaviour you want?

**Comment by theianjones** [comment]
Oh good catch, I was looking at your capture template and didn’t want the Hugo lines and accidentally deleted the roam key. 

Thanks! 

—
Ian Jones

--- original message ---
On May 2, 2020, 11:31 PM EDT notifications@github.com wrote:



Thanks for patiently debugging this issue. That wasn't something I could confirm.

I looked through your Doom config and noticed you removed ROAM_KEY from your ref template. That's fine, but that would mean for websites new notes are recreated when using the bookmarklet instead of accessing the old one. Is that the behaviour you want?

—

You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
