### ISSUE TITLE
Multiple org-ref citations are not recognised as multiple links

### ISSUE THREAD

**Issue by TimQuelch** [jethrokuan/org-roam#544]
### Description
org-ref multi-citations are handled by `cite:key1,key2`. In the org-roam databases this is stored as a single "cite" link to the (non-existing) key "key1,key2". This means that cite backlinks and cite graph behaviour does not work correctly for these links.

This looks like it is caused in
https://github.com/jethrokuan/org-roam/blob/08aa5c630de354440e8eed21b28507f4b9e6ac6a/org-roam.el#L229 ... https://github.com/jethrokuan/org-roam/blob/08aa5c630de354440e8eed21b28507f4b9e6ac6a/org-roam.el#L267-L272 
Here we're extracting the path of the link element. For the example below this is "key1,key2". 

Instead we should be splitting this somehow and generating two separate links. This could either be done as we generate it or we could do a pass through the mapping afterwards to split up keys containing commas.

#### Steps to Reproduce
Source note 1:
```
#+TITLE: Source note 1
#+ROAM_KEY: key1
```
Source note 2:
```
#+TITLE: Source note 2
#+ROAM_KEY: key2
```
Referencing note:
```
#+TITLE: Referencing note

cite:key1,key2
```

#### Expected Results
Two separate "cite" links in the links table of the database: One pointing to "key1" and one pointing to "key2"

#### Actual Results
A single "cite" link pointing to "key1,key2"

### Versions
- Emacs (`C-h v emacs-version`): v28.0.50
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/08aa5c630de354440e8eed21b28507f4b9e6ac6a

**Comment by TimQuelch** [comment]
My current manual workaround is to separate my `cite:key1,key2` into `cite:key1, cite:key2` which is slightly semantically different but is fine for my uses for now

**Comment by richarddavis** [comment]
I just upgraded to v2 and I'm having this same issue with Emacs version 27.2.
