### ISSUE TITLE
org-roam--format-link: Symbol’s function definition is void: org-link-make-string

### ISSUE THREAD

**Issue by f-lai** [jethrokuan/org-roam#552]
### Description
org-roam--format-link: Symbol’s function definition is void: org-link-make-string

Probably related: https://github.com/jethrokuan/org-roam/pull/337/commits
#### Steps to Reproduce
1. Run `org-roam-insert` on any org buffer

#### Expected Results
A link inserted.

#### Actual Results
No link is inserted, the call error'ed out with the message in the title.

### Versions
- Emacs (`C-h v emacs-version`): v26.3

Thanks.

**Comment by jethrokuan** [comment]
You're likely to be using the built-in version of Org from Emacs rather than the newer version Org-roam depends on and pulls in.

Please check with `M-x org-version` to ensure your org version is at least 9.1. for a fix, you may need to rearrange the load order in your init file.

**Comment by f-lai** [comment]
That's right, I'm using the built in version. `Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /Applications/Emacs.app/Contents/Resources/lisp/org/)`, does this look like the problem to you ? I just use the org version shipped with Emacs v26.3. 

Thanks!

**Comment by zaeph** [comment]
> That's right, I'm using the built in version. `Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /Applications/Emacs.app/Contents/Resources/lisp/org/)`, does this look like the problem to you ?

Yes, that's the problem, and you need a more recent version of Org-mode if you want to use Org-roam.  You should be able to install it with `M-x package-list-packages` by finding it on the list and installing it.

You might need to add this to your `init.el`:'
```el
;; org-elpa
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
```

This is to ensure that `package` can find a recent version from the Org-mode ELPA.

**Comment by jethrokuan** [comment]
Sorry, I meant version 9.2. Strange that 9.1.9 ships with Emacs 26.3 though, it should be much older.

**Comment by f-lai** [comment]
Works perfectly, thank you for all of your amazing work.
