### ISSUE TITLE
Allow org-capture to be able to add to org-roam-dailies-today's file

### ISSUE THREAD

**Issue by jmhammond** [jethrokuan/org-roam#556]
### Brief Abstract
I'd like the ability to have `org-capture` or an `org-capture`-like operation capture to the `org-roam-dailies-today` file. Basically allow all new content to go to that file without me having to manually navigate to it.

### Proposed Implementation (if any)
This isn't exactly the solution, but here was a quick-and-dirty solution (by quick, I mean I spent about three hours trying to figure it out...): 
Modified from [this post on StackOverflow](https://stackoverflow.com/questions/56274067/how-to-use-the-function-option-of-org-capture-correctly): 
```lisp
  (defun visit-the-daily-note()
    "Visit a new file named by the current timestamp"
    (interactive)
    (let* (
           (curr-date-stamp (format-time-string "%Y-%m-%d.org"))
           (file-name (expand-file-name curr-date-stamp "~/org/roam/")))
      (set-buffer (org-capture-target-buffer file-name))
      (goto-char (point-max))))

  (setq org-capture-templates '(("n" "Note" entry (function visit-the-daily-note)
                                 "* %?\n")))
```

In the code I'm just manually re-creating the format that `org-roam-dailies-today` creates for the filename. If for some reason that function changes, it will break this. If we can expose the 'create and find the file with the date' mechanism, that would enable us to implement a similar solution.

### Please check the following:
- [X] No similar feature requests

**Comment by jethrokuan** [comment]
So something like:

```
(defun org-roam-dailies-capture-today ()
  "Capture a note into the daily note for today."
  (interactive)
  (let ((org-roam-capture-templates org-roam-dailies-capture-templates)
        (org-roam-capture--info (list (cons 'time (current-time))))
        (org-roam-capture--context 'dailies))
    (org-roam--capture)))
```

should work, if your daily template doesn't have `:immediate-finish t`.

**Comment by jmhammond** [comment]
It didn't work as written, perhaps because I'm already in `org-capture` calling `org-roam--capture` doesn't work? 

I made the one change at the bottom during the "find where to insert the capture" stage of the capture function, telling it to insert at the end of file: 

```lisp
  (defun org-roam-dailies-capture-today ()
    "Capture a note into the daily note for today."
    (interactive)
    (let ((org-roam-capture-templates org-roam-dailies-capture-templates)
          (org-roam-capture--info (list (cons 'time (current-time))))
          (org-roam-capture--context 'dailies))
      (goto-char (point-max))))
```
This worked perfectly. My previous script in my original post would create the file, but didn't insert the org-roam headings that were default had I called `org-roam-dailies-today` (I discovered this this morning). However, your script with my change properly created the file and now inserted the capture at the end. 

Thanks!

I think I could mark this closed, except perhaps we can turn this into a documentation request? If the code I provided is satisfactory, I can make update the docs/configuration.md and make a PR for it.

**Comment by jethrokuan** [comment]
> It didn't work as written, perhaps because I'm already in org-capture calling org-roam--capture doesn't work?

Yes, nested org-roam captures are not yet supported (see #527 ). What about the above didn't work? It works for me if I change the daily template, removing the `:immediate-finish t`.

**Comment by jmhammond** [comment]
I'm sure I'm doing something wrong. I'm in doom emacs, and in my private config.el file, I've pasted your suggested function and call it with an `org-capture-template`
```emacs-lisp
  (defun org-roam-dailies-capture-today ()
    "Capture a note into the daily note for today."
    (interactive)
    (let ((org-roam-capture-templates org-roam-dailies-capture-templates)
          (org-roam-capture--info (list (cons 'time (current-time))))
          (org-roam-capture--context 'dailies))
      (org-roam--capture)))

  (setq org-capture-templates '(("n" "Note" entry (function org-roam-dailies-capture-today)
                                 "* %?\n")))
```

When I run the capture via `org-capture` and select the note template, if my cursor is inside a line, it just creates a newline. If my cursor isn't inside text, it does nothing. Either way, I get no capture buffer. Here's a GIF:
![CaptureGif](https://user-images.githubusercontent.com/84139/81027183-5ac3f980-8e42-11ea-8ad4-aacf8f380a2b.gif)

**Comment by jethrokuan** [comment]
@jmhammond you just need to call `M-x org-roam-dailies-capture-today` to launch a capture. Org-roam adds some additional hooks and functions to org-capture, so it can't just simply be added to `org-capture`. So the above snippet for the function, and:

```
(defun org-roam-dailies-capture-today ()
  "Capture a note into the daily note for today."
  (interactive)
  (let ((org-roam-capture-templates org-roam-dailies-capture-templates)
        (org-roam-capture--info (list (cons 'time (current-time))))
        (org-roam-capture--context 'dailies))
    (org-roam--capture)))

(setq org-roam-dailies-capture-templates
      '(("d" "daily" plain (function org-roam-capture--get-point)
         ""
         :file-name "%<%Y-%m-%d>"
         :head "#+TITLE: %<%Y-%m-%d>")))
```

and calling `M-x org-roam-dailies-capture-today` gets you the behaviour you want.

**Comment by jmhammond** [comment]
Okay, I've got it now, thanks! This has been really helpful, and it works well.
