### ISSUE TITLE
Garbled text in Org-Roam-Find from gpg file

### ISSUE THREAD

**Issue by teesloane** [jethrokuan/org-roam#558]
#### Steps to Reproduce

1. I have a gpg.org file in my org-roam dir.
2. Open org-roam-find
3. See garbled text.

#### Expected Results
A normal org-find-file popup.

#### Actual Results
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/12987958/80925295-879de100-8d5c-11ea-8e98-5c3ea74f391f.png">

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- - Org-roam commit: https://github.com/jethrokuan/org-roam/commit/65d99e9

**Comment by zaeph** [comment]
>     1. I have a gpg.org file in my org-roam dir.

Is it `gpg.org` or `org.gpg`?

**Comment by zaeph** [comment]
I cannot reproduce it on my end with an `.org.gpg` file.

You seem to be running an older version of Org-roam: could you try grabbing the latest version from MELPA?  If that doesn't solve it, please run `M-x org-roam-db--clear` and then `M-x org-roam-db-build-cache` to rebuild the cache.

**Comment by teesloane** [comment]
Sorry, the file is a `.org.gpg` - I upgrade roam, and ran build cache, and the garbled text disappears (although the file is not showing up in org-roam-find-file. If it shows up again I will re-comment if/when that happens.

**Comment by teesloane** [comment]
Closing until I can recreate.
