### ISSUE TITLE
Add org-roam-capture-templates to documentation

### ISSUE THREAD

**Issue by edumerco** [jethrokuan/org-roam#573]
### Description
The template system is well documented, but where/how to define them is not. 

Maybe the variable org-roam-capture-templates could be included (surrounding?) the examples so as to try to make it easier for the new users to customize their templates.

**Comment by edumerco** [comment]
Thanks. :+1: :smiley:

**Comment by zoechi** [comment]
@edumerco 

> The template system is well documented

Do you mean org-mode capture templates?
I haven't used them yet (still an Emacs rookie).
I couldn't find much info about org-roam capture templates.

**Comment by edumerco** [comment]
It's in the documentation included. Online, it's  in https://org-roam.readthedocs.io/en/master/templating/

**Comment by christabella** [comment]
I believe the readthedocs is deprecated 😰  moving so fast! In the updated docs, it is at https://org-roam.github.io/org-roam/manual/Template-Walkthrough.html#Template-Walkthrough

**Comment by RaphaelPour** [comment]
https://www.orgroam.com/manual.html#Template-Walkthrough

@christabella Your link got deprecated, too :see_no_evil:
