### ISSUE TITLE
Mention the doc folder in the README.md

### ISSUE THREAD

**Issue by zoechi** [jethrokuan/org-roam#578]
I tried to find information about capture templates
and I only found something in https://github.com/jethrokuan/org-roam/tree/master/doc

Should this directory be not mentioned in the README.md?

**Comment by zaeph** [comment]
There's an [article on the manual](https://org-roam.readthedocs.io/en/latest/templating/), and there's a link to said manual at the top of the [homepage for the project](https://github.com/jethrokuan/org-roam).

**Comment by zoechi** [comment]
I completely missed the hamburger menu. I thought the menu on the right was the whole menu.
