### ISSUE TITLE
RFC: Removing the ID workflow

### ISSUE THREAD

**Issue by jethrokuan** [jethrokuan/org-roam#59]
I'm finding that manually keeping IDs unique is becoming much more of a hassle than it is worth.

I'm going to cut a 0.1.0 release soon, which will support both titles and IDs. After 0.1.0, I'm planning to move forward with:

1. Removing IDs -- files will be created with timestamped names
2. The `#+TITLE: ` of the Org file will be used in place of IDs, everywhere. Where the values must be unique, the file name is used instead, but this is generally invisible to the user.

This will greatly simplify the code-base, and allow me to push for more features.

Edit: When I say removing the ID workflow, I meant removing the choice between looking at IDs, and looking at titles with `org-roam-insert`, and `org-roam-find-file`. This mainly affects people who don't bother to add a `#+TITLE` to their org files. But now, org-roam also does that for you.

**Comment by l3kn** [comment]
What's your rationale for including timestamps in the generated file names?

I think it woud be nice to have some way to configure the way filenames are generated based on a notes title, e.g. to avoid cluttering filenames with timestamps when using them to generate a website using org-publish.

**Comment by jethrokuan** [comment]
> What's your rationale for including timestamps in the generated file names?

It's just a way to make unique filenames. I no longer care so much about how my files are named. The titles have been sufficient.

> I think it woud be nice to have some way to configure the way filenames are generated based on a notes title, e.g. to avoid cluttering filenames with timestamps when using them to generate a website using org-publish.

This is still possible with #62. With:

```
(setq org-roam-use-timestamp-as-filename nil)
```

The user will be prompted for a file name, pre-populated from the title. It is then the user's responsibility to choose a unique file name.

**Comment by jethrokuan** [comment]
Actually the changes in #62 really just simplify the code, without affecting the end user. If there is no title, the slug (relative file name to the org-roam directory) is used anyway. So I'm going ahead with the change
