### ISSUE TITLE
org-roam-insert no longer inserts relative file-links on existing paths

### ISSUE THREAD

**Issue by jethrokuan** [jethrokuan/org-roam#70]

**Comment by brookter** [comment]
Hi, 

I only downloaded org-roam this morning, so I think the version I have includes this fix, and I may have misunderstood what's going on, but....

org-roam-insert is inserting broken links for me, in this format:

`[file:Books/Code.org][Code]]`

i.e. it's inserting a relative link from org-roam-directory ("`~/Notes/"`), but as the file I'm is in a subdirectory (`~/Notes/Stuff/`), it can't find the link and I have to manually correct it.

What I would expect to see is 

`[[file:~/Notes/Books/Code.org]]`

Am I misunderstanding something? Thanks!

**Comment by jethrokuan** [comment]
Ah yes sorry this completely slipped my mind. I don't nest any of my files, so this never happened to me.

**Comment by brookter** [comment]
Gosh, that was quick!

**Comment by jethrokuan** [comment]
#78 should fix it

**Comment by brookter** [comment]
Just got back from walking the dog and you've fixed it already...  Yes, that looks fine.

Thank you very much for this, and for the whole package!
