### ISSUE TITLE
Possible to have more than one org-roam-directory?

### ISSUE THREAD

**Issue by anthrolisp** [jethrokuan/org-roam#80]
Is it possible to have more than one org-roam-directory for more than one separate org-roam zettelkastens?

**Comment by jethrokuan** [comment]
I'm unlikely to merge such functionality in, but you can write some simple elisp for this. Here's some pseudo-code:

```
((completing read for new org-roam-directory)
 (setq org-roam-directory new-dir)
 (org-roam--build-cache-async))
```

should work for the most part.

**Comment by jethrokuan** [comment]
I changed my mind about this, because I think it's not a particularly abusable feature and it might make sense for some to keep things separate (but not to me). I'll see what I can do.

**Comment by anthrolisp** [comment]
Great!!!! Thank you!!!!!

**Comment by herbertjones** [comment]
I developed a hacky workaround for the time being.  It relies on helm, though it would be easy to switch that to `completing-read` if needed.

https://gist.github.com/herbertjones/9718942aac44cd9f0ee5d353ad015fe3

**Comment by juergenhoetzel** [comment]
> Is it possible to have more than one org-roam-directory for more than one separate org-roam zettelkastens?

I myself am not a big fan of implementing this in org-roam myself.

There are already several packages for Emacs to handle multiple workspaces or projects. I use projectile for all my Project
Switching workspaces is wired in my muscle memory.

 in this case the functionality can be easily implemented using a [projectile-after-switch-project-hook](https://projectile.readthedocs.io/en/latest/configuration/)

The main advantage of Emacs is its extensibility and adaptability to your own workflow instead of  imposing a predefined workflow.

**Comment by juergenhoetzel** [comment]
How about adding another indirection to the cache: Using a new var `org-roam-current-dir`

Another new function `org-roam-set-current-dir`  could be called interactively or in a hook by `projectile`  to set this indirection.

**Comment by jethrokuan** [comment]
@herbertjones can I have you document how to enable multiple org-roam-directories in the configuration section? After which I think we can close this issue.

**Comment by anthrolisp** [comment]
Whenever I visit a file in the second org-roam instance, I keep getting the following prompt. It works for that session. But even after I answer with a "!", it re-prompts me the next time I open Emacs and visit a file in this directory. Any ideas?

The local variables list in /path/to/here/
contains values that may not be safe (*).Do you want to apply it?  You can type
y  -- to apply the local variables list.
n  -- to ignore the local variables list.
!  -- to apply the local variables list, and permanently mark these
      values (*) as safe (in the future, they will be set automatically.)  * org-roam-directory : "/path/to/here/"

Here is what is in my messages:

Saving file /home/user/.emacs.d/to-be-dumped.el...
Wrote /home/user/.emacs.d/to-be-dumped.el

**Comment by anthrolisp** [comment]
I was able to solve this by putting the following in my config:

(add-to-list 'safe-local-variable-values
             '(org-roam-directory . "."))

**Comment by AtomicNess123** [comment]
Is it possible to add several directories and how? Thanks.

**Comment by d12frosted** [comment]
@AtomicNess123 please checkout the [docs](https://www.orgroam.com/manual.html#How-do-I-have-more-than-one-Org_002droam-directory_003f)

**Comment by AtomicNess123** [comment]
Thanks, I did, but I don't do elisp so I can't implement.
I see that the syntax is the one below, but not sure how and where in the code to add several directories.

```
((nil . ((org-roam-directory . ".")
         (org-roam-db-location . "./org-roam.db"))))
```

**Comment by d12frosted** [comment]
@AtomicNess123 

> It does this by checking for a file named .dir-locals.el. 

This trick uses [Directory Variables][1]. Basically, you need to put this file in each of your roam directories. E.g.

```
- path/to/roam-1/.dir-locals.el
- path/to/roam-2/.dir-locals.el
```

  [1]: https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

**Comment by AtomicNess123** [comment]
Thanks, I will try to digest this.

**Comment by AtomicNess123** [comment]
Understood, thanks! One question though. How will Emacs know which folders contain those files? Will Emacs search across my whole computer HD?

**Comment by herop** [comment]
> Thanks, I did, but I don't do elisp so I can't implement.
> I see that the syntax is the one below, but not sure how and where in the code to add several directories.
> 
> ```
> ((nil . ((org-roam-directory . ".")
>          (org-roam-db-location . "./org-roam.db"))))
> ```

Nice and all, but:
* This will not be called with my config at start
* And still the local variable org-roam-db-location will be thrown an error by `Messages` buffer
* Finally, how con both list items combined (at the right place in the correct syntax)?

It would mean a great deal to me if you could help.
Regards,
Jochen

**Comment by Imymirror** [comment]
I've written a package that provides a function `mrds/roam-switch-directory` to simply solve this problem. maybe you can have a try. 

[mrds-mode : simple multiple roam directories support.](https://github.com/Imymirror/mrds-mode)

**Comment by rickalex21** [comment]
A list would have been nice for `org-roam-directory`.

```lisp
(add-to-list 'org-roam-directory "~/some-other-dir"))
```

**Comment by herbertjones** [comment]
Although it's possible to have more than one org-roam directory, I ended up copying someone else's idea to just have a single directory and placing multiple repositories inside that one so that I can link between the directories.  For example, at home I might have something like,

```
~/org-roam/
~/org-roam/personal/
~/org-roam/main/
```

and at work

```
~/org-roam/
~/org-roam/main/
~/org-roam/work-stuff/
~/org-roam/project-a/
~/org-roam/project-b/
```

Some of the directories are backed and synced using something like git or syncthing.  This way I don't have work stuff at home, and no personal stuff at work.  It also ensures grep-like tools or analysis tools are kept simple by only looking at a single top directory and not having to work on multiple directories in various locations, which some other tools aren't designed to do out the box.

**Comment by Kyonax** [comment]
How do you change between them? Org-roam reads everything inside the `~/org-roam` directory? or do you change the default directory whenever you need?

**Comment by herbertjones** [comment]
@Kyonax I don't change between them.  Everything is grouped together..

**Comment by rickalex21** [comment]
>How do you change between them? 

@Kyonax    You can drop everything together in one dir and filter them how ever you see fit.

**Comment by seflue** [comment]
> A list would have been nice for `org-roam-directory`.
> 
> ```commonlisp
> (add-to-list 'org-roam-directory "~/some-other-dir"))
> ```

I absolutely agree with this idea to support a list of directories. I actually [implemented](https://github.com/chipsenkbeil/org-roam.nvim/pull/55) this for [org-roam.nvim](https://github.com/chipsenkbeil/org-roam.nvim) which I mainly use. The idea is to be able to integrate existing org-files into the knowledge graph of org roam. Although this is not something every needs, it would be great, to make it even possible.

The way I use this is, that I typically create nodes on the fly in my main org-mode directory. But from time to time I clean things a little bit up and put file togethers, which have the same context. In org-roam.nvim I can just move them into separate folders and I am still able to connect them as nodes into my daily files etc. Actually it works similar like the agenda files - there I can also define an arbitrary list, which is read for the orgmode agenda.
