### ISSUE TITLE
Org-roam fails to find backlinks when both files reside in nested folder

### ISSUE THREAD

**Issue by nmartin84** [jethrokuan/org-roam#81]
Hey man, i've been testing and loving the progress you are making on this. I did come across this issue which i've actually seen since early on. So if a backlink is inserted for 2 files that reside in nested folder, org-roam fails to find the backlink and displays a blank window. It requires at least one of the files to be in the parent folder. I've tried rebuilding the cache a few times with no change.

(seq org-roam-directory "~/root/")

Folder structure:
```
./root/
./test.org #backlink: beta.org (works)
../nestedfolder1/
.../alpha.org #backlink: beta.org (fails)
.../beta.org
```

- test.org will display the backlink correctly
- alpha.org will display a blank org-roam buffer window

**Comment by jethrokuan** [comment]
Thanks for the clear bug report! I'm pushing a fix for this now.

**Comment by nmartin84** [comment]
Well, almost got it, it's displaying the org-roam buffer as it should but it's still not displaying any results or finding the backlink. Tossed a quick video together if it helps to demonstrate it.

https://youtu.be/n16BG6QxoKE

**Comment by jethrokuan** [comment]
Thank you, the video was very helpful. I replicated it on my end, and think I've fixed it. The focus for the next release would be a comprehensive test suite so I don't keep breaking things :sweat_smile: #79
