### ISSUE TITLE
Suggestion: automatic collection of tags

### ISSUE THREAD

**Issue by brabalan** [jethrokuan/org-roam#84]
I add `#+FILETAGS:` lines at the beginning of my notes (just after the title), and I wanted a quick way to list all the tags I use and easily access them. I've written these two functions to do this. They depend on dash and deft (I can remove the dependency of dash, but deft is very useful to do the tag search). I'm putting it here in case you find it useful. (And sorry for my bad elisp, I'm not very proficient in that language.)

```emacs-lisp
(defun as/open-in-deft (filter)
  (deft)
  (deft-filter filter t))

(defun as/collect-filetags ()
  (interactive)
  (let* ((command (concat "grep -h '^#+FILETAGS:' " org-roam-directory "/*.org"))
         (output (shell-command-to-string command))
         (lines (split-string output "[ \n]+" t "#\\+FILETAGS:"))
         (tags (sort (-flatten (mapcar (lambda (l) (split-string l ":" t)) lines)) #'string<))
         (counts (-reduce-from (lambda (plist tag)
                                 (if (string-match "^##" tag)
                                     plist
                                   (let* ((tagname (substring tag 1))
                                          (nb (lax-plist-get plist tagname)))
                                     (lax-plist-put plist tagname (if nb (+ nb 1) 1)))))
                               nil tags)))
    (let ((file (concat org-roam-directory "/taglist.org")))
    (write-region "#+TITLE: Tag List\n\n" nil file nil)
    (while counts
      (let ((tag (car counts))
            (nb  (cadr counts)))
        (write-region
         ;; The next line is a dirty hack to avoid the tag being explicitely in
         ;; the tag list, hence in deft search results
         (format "- [[elisp:(as/open-in-deft (concat \"#\" \"%s\"))][%s]] :: %d\n" tag tag nb)
         nil file t)
        (setq counts (cddr counts)))))))
```

**Comment by jethrokuan** [comment]
Hi @brabalan , thanks! w.r.t. `FILETAGS`, that's precisely what Org-roam is trying to solve, but instead of using the `#+FILETAGS` attribute, using actual files as tags. You can see me explicitly doing this in this gif:
![gif](https://d33wubrfki0l68.cloudfront.net/9b144b0c0f246ef781a7348e450fdc6cc226cb2f/a6895/ox-hugo/org-roam-insert-filetag.gif)
To see all files with the tags, it's just opening that file, and looking at the org-roam buffer!
![image](https://user-images.githubusercontent.com/1667473/74590421-201fa180-5049-11ea-96d5-cec7e1ca4767.png)

**Comment by brabalan** [comment]
This is a very interesting way to do it. I have two questions for you:
- why do you use a `TAGS` cookie at the top of your learning file?
- is there a way to refine the search? For instance, if you only want to see notes with both Learning and Note-taking links?

**Comment by jethrokuan** [comment]
> why do you use a TAGS cookie at the top of your learning file?

Same as why you use a FILETAGS cookie. It's usually there until it's tagged later on in the content.

> is there a way to refine the search? For instance, if you only want to see notes with both Learning and Note-taking links?

Not at the moment, but can be done relatively easily

**Comment by brabalan** [comment]
Nice. I'm going to give it a try.

I'm not sure it's needed to keep this issue opened.

**Comment by poligen** [comment]
Hello, I have a question about the tags. In this example, you create a tag "reading" by `org-roam-insert`, but if I open another org file; for example, call "thinking-slow.org", and then I use `org-roam-find-file`, I cannot find the file with the title `reading`, which `org-roam` create for me automatically with random file's name. 

Any solution for this problems?

> Hi @brabalan , thanks! w.r.t. `FILETAGS`, that's precisely what Org-roam is trying to solve, but instead of using the `#+FILETAGS` attribute, using actual files as tags. You can see me explicitly doing this in this gif:
> ![gif](https://camo.githubusercontent.com/47043bf107726d380dd65b94875e25c18274591f/68747470733a2f2f64333377756272666b69306c36382e636c6f756466726f6e742e6e65742f396231343462306330663234366566373831613733343865343530666463366363323236636232662f61363839352f6f782d6875676f2f6f72672d726f616d2d696e736572742d66696c657461672e676966)
> To see all files with the tags, it's just opening that file, and looking at the org-roam buffer!
> ![image](https://user-images.githubusercontent.com/1667473/74590421-201fa180-5049-11ea-96d5-cec7e1ca4767.png)

**Comment by jethrokuan** [comment]
Are you on latest develop commit? #107 should have fixed this

**Comment by poligen** [comment]
Thank you! I did use the master branch..., I will change to latest develop

**Comment by jcguu95** [comment]
I second for a refined way on searching with tags (e.g. more advanced filtering.. etc). Also, it might be useful to create a "link page". Similar as back link page, a link page will collect in the current file all links, which might be scattered around.
