### ISSUE TITLE
Adding support for encryption

### ISSUE THREAD

**Issue by chip2n** [jethrokuan/org-roam#85]
It would be useful to have support for encrypting individual notes using via GnuPG. These files have a `org.gpg` extension which are not picked up by org-roam currently.

Having just one encrypted note in your notes directory would require a password each time the cache is rebuilt (unless the password is cached). If this is done often it could be annoying, so perhaps the encrypted notes should only be cached once.

Would this feature be a useful addition to org-roam, or is it out of scope? Are there any potential problems adding a new file extension in addition to `.org` (this might be nice to have regardless of encryption)?

**Comment by jethrokuan** [comment]
>It would be useful to have support for encrypting individual notes using via GnuPG. These files have a org.gpg extension which are not picked up by org-roam currently.

Yes I agree. This is definitely in scope, hopefully it isn't too hard to add.

> Having just one encrypted note in your notes directory would require a password each time the cache is rebuilt.

Not really a problem, the cache is only built from scratch once each time Emacs is loaded.

> Are there any potential problems adding a new file extension in addition to .org (this might be nice to have regardless of encryption)?

Well the links are Org links, and making it extension-agnostic could be a hassle.

**Comment by chip2n** [comment]
It is possible to make emacs automatically decrypt files without .gpg extension:

```elisp
(setq epa-file-name-regexp "\\.\\(gpg\\|org\\)$")
(epa-file-name-regexp-update)
```

But this means that Emacs tries to decrypt all org files, which obviously doesn't work. An alternative is to not encrypt the file, but use `epa-encrypt-region` to encrypt the contents (or a part of it). That's not quite as nice when jumping to the file via a backlink though.

The nicest solution IMO would be having list of extensions or regexes that are considered roam links:
```elisp
(setq org-roam-link-extensions '(".org" ".org.gpg"))
```

**Comment by jethrokuan** [comment]
I'd imagine only files that are encrypted will have extension `.org.gpg`, and those that aren't have extension `.org`, and Emacs handles the decryption transparently right? If all that's needed is to include `.org.gpg` files into the list of roam files, then it should be easy. And also set create an option `org-roam-encrypt-files` for creation of new files (to be encrypted or not by default).

**Comment by chip2n** [comment]
Yep, I think so! Including an option for encryption of new files sounds pretty groovy as well - we'll have to see the performance impact when decrypting 1000s of org files during cache build though. At least the password is cached so you only need to enter it once :)

**Comment by jethrokuan** [comment]
> performance impact when decrypting 1000s of org files during cache build though

Good point. At some point I need to start doing benchmarking.
