### ISSUE TITLE
`org-roam-insert` mistakes temp files ended with "~"

### ISSUE THREAD

**Issue by hungpham2511** [jethrokuan/org-roam#96]
Hi Jethro,

`org-roam-insert` is a really nice enhancement of `org-insert-link` and I enjoy using it very much to create new forward links. However, it seems to return both `a-fictional-file.org` and `a-fictional-file.org~` as potential links, which is quite confusing.

**Comment by jethrokuan** [comment]
This is caused by this extremely strange behaviour :thinking: 

```
(file-name-extension "test.org~") ;; org
```

I'll push out a fix soon. Also hello from Singapore!

**Comment by hungpham2511** [comment]
Hey, I am from Singapore as well! 

Sound great! I see that you have already had a PR, that's really fast. Thanks!

**Comment by jethrokuan** [comment]
Let me know if it works for you, seems to work for me. I'd recommend adding [no-littering](https://github.com/emacscollective/no-littering) anyway to keep directories clean.
